Создание платежного счета BC-5769
CorporationX/account_service pull request #10
Opened 2023-09-01 16:14 UTC by czar777

2023-09-04 13:46 UTC, M437A approved these changes

2023-09-04 13:46 UTC, M437A commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    public AccountDto open(@RequestBody AccountDto accountDto) {
Нужно добавить аннотацию @Valid чтобы запустить аннотации из дто

2023-09-04 13:46 UTC, M437A commented on src/main/java/faang/school/accountservice/entity/Account.java
> +    AccountType type;
private

2023-09-04 13:46 UTC, M437A commented on src/test/java/faang/school/accountservice/controller/AccountControllerTest.java
> +
А это работает без SpringBootTest аннотации ?
Нет CI/CD не видно

2023-09-09 19:50 UTC, czar777 commented on src/test/java/faang/school/accountservice/controller/AccountControllerTest.java
> +
я наследовался от BaseContextTest

2023-09-12 13:51 UTC, InnMish requested changes

2023-09-12 13:51 UTC, InnMish commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private String numberPayment;
Смотри, нам вот тут надо подумать в сторону защиты данных: чтобы никто не смог просто взять и изменить это поле. Номер аккаунта должен быть неизменяемым полем. Тут может помочь аннотация @JsonProperty(access = JsonProperty.Access.READ_ONLY)
Почитай, как работает)

У нас в бэклоге есть задача на генерацию уникальных номеров счета. После ее реализации номер аккаунту будет присваиваться изнутри, то есть мы из базы будем доставать свободный номер и присваивать его счету. Таким образом, от пользователя эта информация поступать не будет. Соответственно, это поле нужно вообще защитить от внешнего изменения. Чтобы я, например, не могла руками поменять номер своего банковского счета

2023-09-12 13:51 UTC, InnMish commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private AccountType type;
Это поле тоже можно защитить от изменения, я думаю

2023-09-12 13:51 UTC, InnMish commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private Currency currency;
И это тоже, наверное

2023-09-12 13:51 UTC, InnMish commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private String numberPayment;
Таким образом, если мы будем эту аннотацию использовать здесь, то через постман, например, мы не сможем передать это поле - будет ошибочка. Но сможем изменять его сеттером, что нам и требуется здесь)

2023-09-12 13:51 UTC, InnMish commented on src/main/java/faang/school/accountservice/enums/Currency.java
> +    CNY
Тут можно подумать в сторону автоматического расширения. 
Сейчас, если "банк" захочет добавить еще один вариант валюты, то нам придется это значение сюда вот внести, потом проект пересобрать и снова задеплоить (ну, если мы типа в проде). Было бы классно дать "банку" возможность самому эти значения добавлять в базу. То есть сделать прям им возможность при создании аккаунта или выбрать валюту из тех, что у нас уже в базе, или добавить свою, если подходящей нет - больше гибкости будет, и нам не надо будет из-за одной валюты пересобирать приложение каждый раз.

2023-09-12 13:51 UTC, InnMish commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    @Retryable(retryFor = OptimisticLockException.class)
😎

2023-09-12 13:51 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Давай тут timestamptz сделаем - учитывает таймзону)

2023-09-12 13:51 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    status         VARCHAR(255) NOT NULL,
тут можно дефолтное значение добавить

2023-09-12 13:51 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    status         VARCHAR(255) NOT NULL,
С точки зрения оптимизации работы с базой, было бы классно хранить enum в ordinal, а не стрингой 
Число у нас будет занимать чуть-чуть прям места, можно сделать SMALLINT, например, и хранить там одно из значений enum (0, 1 и тд). Всегда полезно сокращать использование памяти, где это возможно. 
Например, тут можно же не хранить строчку из 255 символов? И в остальных enum тоже

2023-09-12 13:51 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +CREATE INDEX index_number_payment_owner_id ON account (number_payment, owner_id);
Помнишь, как работают индексы? 
Составной индекс будет  давать менее производительные поиск, чем индекс по одному полю. А еще обновление такого индекса достаточно дорогое выйдет. Плюс он вообще будет использовать в том случае, если поиск будет осуществляться именно по номеру и айди. А как часто такой поиск в целом будет производиться? 

Не будет ли чаще происходить поиск отдельно по номеру счета и отдельно по айди?

2023-09-12 13:51 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    currency       VARCHAR(255) NOT NULL,
А вот для currency нам и 3 символов хватит же, да? У нас аббревиатура валюты - три символа. Соответственно, можно не выделять аж 255)

2023-09-14 15:46 UTC, czar777 commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private AccountType type;
если я это поле сделаю неизменяемым, то я же не смогу при пост запросе указать тип этого аккаунта

2023-09-14 15:47 UTC, czar777 commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private Currency currency;
и тут тоже

2023-09-15 08:59 UTC, InnMish approved these changes

2023-09-15 08:59 UTC, InnMish commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private AccountType type;
ю а райт

2023-09-15 08:59 UTC, merged