Управление уникальными номерами счетов
CorporationX/account_service pull request #131
Opened 2024-05-16 07:52 UTC by adilbeknurmakov

2024-05-16 15:39 UTC, Ikhsanov-Nail-95 approved these changes
Выглядит круто!

2024-05-16 22:19 UTC, adilbeknurmakov commented on src/main/java/faang/school/accountservice/entity/AccountSeq.java
> +
есть неправильное формотирование - знаю, после ревью исправлю. забыл, не заметил пере пуллом

2024-05-17 12:16 UTC, guguggggu approved these changes

2024-05-26 00:49 UTC, pablo023 requested changes
В целом по комментам отметил, отдельный общий момент - форматирование, его в комментах не отмечал. Есть хоткеи для этого, но в целом лучше сразу привыкай писать красиво. Если уже запушил в неопрятном виде - не ленись пофиксить)

2024-05-26 00:49 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java
> +    private final static int MAX_ACCOUNT_LEADING_DIGITS_DEPO=5236;
Такс, вот это всё - не в код. Константы нужно в проперти.

2024-05-26 00:49 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java
> +    public void generateAccountNumber(AccountType accountType, long bucketSize){
Ты уверен, что здесь нужен параметр? У нас инкремент возможен на другое значение, кроме единицы? Если нет, то зачем нам возможность туда что-то иное здесь передавать?

2024-05-26 00:49 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java
> +        // Increment the counter for the specified account type
В целом метод слишком большой, его тяжело читать, и понимать, что тут происходит. Вынеси в пропы константы, и разбей этот метод на логические сотавляющие. У тебя здесь генерация самого номера, его валидация, и генерация списка FreeAccountNumber. Разбей это всё на несколько методов.

2024-05-26 00:49 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java
> +            generateAccountNumber(accountType, 1);
Есть такой антипаттерн - магическое число. Почитай про него, и исправь это.

2024-05-26 00:49 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java
> +        // Save the generated account numbers to the repository
Это можно убрать. В целом, на будущее - если код требует комментариев, задумайся - не нагружаешь ли ты метод излишней логикой, и подумай, что тут можно разбить.

2024-12-22 20:44 UTC, closed without merging