Создана миграция для создание таблицы balance
CorporationX/account_service pull request #15
Opened 2023-09-04 08:32 UTC by kxnvg

2023-09-05 22:05 UTC, kkkooolllyyyaaa requested changes
Есть комменты)

2023-09-05 22:05 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    account_number character(16) NOT NULL,
varchar должен быть, и от 12 до 20, так что varchar(20) давай просто)

2023-09-05 22:05 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    current_actual_balance bigint,
Почему int? А если у меня на счету 12 рублей 50 копеек?
Можно либо хранить varchar, либо numeric, либо bigint, при условии, что хранишь (x * 1_000_000) в миллион раз больше, и потом после чтения превращаешь в BigInteger и делишь на лям

2023-09-05 22:05 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    FOREIGN KEY (account_number) REFERENCES account(number) ON DELETE CASCADE
Мы тут скорее всего удалять ничего не будет, просто будем блокировать/закрывать счёт. Поэтому давай без ON DELETE CASCADE, а то может боком сыграть потом)

2023-09-18 21:07 UTC, Rvze approved these changes

2023-09-19 07:13 UTC, merged