Featue bc 5724
CorporationX/account_service pull request #17
Opened 2023-09-04 10:58 UTC by Hanibalai

2023-09-05 15:34 UTC, ipavelbel approved these changes
Всё гуд!! Пару рассуждений добавил)

2023-09-05 15:34 UTC, ipavelbel commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private Long id;
тут может примитив лучше использовать ?

2023-09-05 15:34 UTC, ipavelbel commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
наверное в реальной жизни id счёта надо было генерировать при помощи uuid, но для наших целей наверное будет strategy = GenerationType.IDENTITY отличное решение =)

2023-09-05 15:34 UTC, ipavelbel commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @Column(name = "account_number", nullable = false, unique = true, length = 20)
как Влад говорил что длину  лучше ограничивать числу приближенное к 2 в степени, но в нашем случае тут просто максимальное по заданию ты взял, тоже хороший вариант.

2023-09-05 15:34 UTC, ipavelbel commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public Account getAccount(long id) {
может этот метод  private, если не будем к нему обращаться из других классов.

2023-09-05 15:34 UTC, ipavelbel commented on src/test/java/faang/school/accountservice/controller/GlobalExceptionHandlerTest.java
> +        }.getClass().getEnclosingMethod();
тут поехала скобка, или так должно быть?

2023-09-05 15:34 UTC, ipavelbel commented on src/test/java/faang/school/accountservice/service/AccountServiceTest.java
> +        accountService.open(accountDto);
может сразу несколько проверок  verify написать в одном тесте, тогда меньше тестов будет с похожим кодом

2023-09-05 18:34 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private Long id;
если будет примитив, то по-умолчанию будет 0, это может быть некорректной информацией если в базе id-шники будут с нуля начинаться)

2023-09-05 18:35 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Да, вроде на многих проектах используются UUID, я решил сделать по аналогии, как у нас в других сервисах, но может ты прав и в данном сервисе правильнее было бы именно UUID использовать, пока не знаю)

2023-09-05 18:36 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @Column(name = "account_number", nullable = false, unique = true, length = 20)
ага, тут просто строгие границы заданы, поэтому получилось, что так ограничил)

2023-09-05 18:37 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public Account getAccount(long id) {
Я сделал сначала прайвет, но потом понял, что он точно будет в других сервисах использоваться еще, так как это основная сущность в этом сервисе)

2023-09-05 18:39 UTC, Hanibalai commented on src/test/java/faang/school/accountservice/controller/GlobalExceptionHandlerTest.java
> +        }.getClass().getEnclosingMethod();
даже не знаю как лучше, так-то я специально перенес, потому что фигурная скобка и когда они обе вместе пустые стоят, как-то зрительно меня напрягало) но наверное есть правильный вариант, как стоит делать в таких случаях)

2023-09-05 18:40 UTC, Hanibalai commented on src/test/java/faang/school/accountservice/service/AccountServiceTest.java
> +        accountService.open(accountDto);
тоже хороший вопрос, который для меня пока не раскрыт, как лучше делать в подобных тестах, я разделял на несколько, потому что не мог название придумать для метода который тестирует сразу несколько вызовов, надо Инну тут тоже спросить)

2023-09-06 09:14 UTC, ipavelbel commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private Long id;
А ну да, точняк)

2023-09-09 08:22 UTC, InnMish requested changes

2023-09-09 08:22 UTC, InnMish commented on src/main/java/faang/school/accountservice/entity/account/Currency.java
> +}
Получается, сейчас, чтобы добавить новую валюту, нам обязательно нужно будет перекомпилировать программу каждый раз, потому что это хардкод здесь. Давай сделаем так, чтобы мы за этим не следили. Если банк (условный) хочет добавить юани, пусть добавляет в запросе. Наше ограничение - трехзначная форма записи. В идеале потом сюда можно прикрутить кэш, который будет предлагать (банку как будто бы) на выбор все типы валют, которые у нас есть в базе, а если таких нет, то можно будет создать новую

2023-09-09 08:22 UTC, InnMish commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    }
Получается, если у нас одновременно запустятся, допустим, две транзакции, то они могут законфликтовать между собой и вызвать исключение OptimisticLockingFailureException или подобное, если они попытаются обновить сущность с устаревшей версией. 

Если две транзакции одновременно попытаются изменить одну и ту же сущность Account, они могут вызвать конфликт оптимистической блокировки, когда пытаются изменить одно и то же поле версии. Например, банк хочет заблокировать счет, а человек в это же самое время хочет этот счет закрыть. 

Я бы предложила тут сделать обработку возможной ошибки OptimisticLockingFailureException  
Надо подумать, что мы хоти сделать, если встретили эту ошибку? Попробовать повторить операцию, может быть, или пользователя проинформировать. 
А ещееее :D 

Это, конечно, дебри уже, но что если аккаунт заблокирован прямо сейчас, а я хочу его переоткрыть. У меня есть возможность? Что, если его заблокировал "банк", а я как пользователь такая ха-ха а вот и нет! и открываю снова. Как нам избежать такой возможности?

2023-09-09 08:22 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    created_at timestamptz DEFAULT current_timestamp,
timestamptz круто)

2023-09-09 08:22 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    currency       SMALLINT DEFAULT 0 NOT NULL,
varchar(3) здесь можно, если будем не в энуме хранить

2023-09-09 08:22 UTC, InnMish commented on src/test/java/faang/school/accountservice/service/AccountServiceTest.java
> +        accountService.open(accountDto);
Мне нравится, когда один тест - одна проверка 
Но это вкусовщина, правильного ответа тут нет) 
Просто когда одна проверка, то сразу понятно, в какое место идти)

2023-09-09 09:13 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +@RequestMapping("/accounts")
ага, точно) поправил)

2023-09-09 09:16 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private String accountNumber;
Да, хорошая штука, надо теперь использовать, спасибо)

2023-09-09 11:14 UTC, Hanibalai commented
На счет UUID, после 2 часов перенестройки на тип UUID, я сумел добиться автогенерации этого поля) Поставил дополнительное расширение для postgres  в миграцию, для добавления функции автогенерации этого типа данных, при сохранении сущности, но после реализации почему-то пересатают работать функции по авторегистрации даты при создании и обновлении сущности, а само поле id, которым все коллеги будут оперировать превратилось в 32-значную строку, что я думаю вызвало бы недовольство) В общем, я вернул лонг, потому что, как мне кажется, необходимо коллегам отдельно рассказать про то, что это такое и как с этим работать, решить проблему с конфликтом генерации дат, а потом отдельной задачей отрефакторить при необходимости)

2023-09-09 11:16 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/entity/account/Currency.java
> +}
Сделал, отдельную сущность)

2023-09-09 11:29 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private String accountNumber;
Правда возникает проблема, при создании аккаунта, поле не читается если ставить эту аннотацию..

2023-09-09 14:09 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/entity/account/Currency.java
> +}
В самом начале меня посещала эта мысль, что enum не очень подходит, но не сделал и сейчас пришлось кучу всего переписывать)

2023-09-09 14:31 UTC, Hanibalai commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    }
погуглил, первое что нашел это аннотация retryable(), повесил ее, показалось хорошим решением, но если это не так, то жду замечания) В первый раз ее использую и не знаю, хорошее ли это решение в данном случае)

Ну в текущей реализации у нас нет возможности переоткрыть счет, ее нужно сделать дополнительно, если она нужна) А счет у нас имеет уникальный номер, поэтому просто так это тоже не сделать)
Возможно ты конечно о другом писала)

2023-09-10 18:04 UTC, merged