BJS2-25874-1
CorporationX/account_service pull request #186
Opened 2024-08-26 15:46 UTC by Caveri95

- Созданы сущности Account Balance и настроена связь между ними
- Добавлен контроллер с методами на создание/получение/редактирования баланса
- Добавлены соответствующие методы в сервис
- Создан обработчик ошибок
- Написаны интерфейсы-репозитории

2024-09-06 03:59 UTC, pablo023 requested changes

2024-09-06 03:59 UTC, pablo023 commented on src/main/java/faang/school/accountservice/controller/BalanceController.java
На самом деле, это вряд ли нужно, т.к. вся работа с балансами будет осуществляться через аккаунты, которые с ними связаны, и скорее тут надо бы добавлять в контроллер аккаунтов методы, а из аккаунт сервиса дергать сервис балансов.

2024-09-06 03:59 UTC, pablo023 commented on src/main/java/faang/school/accountservice/entity/Account.java
Эта сущность есть в мастере, надо подтянуть из него

2024-09-06 03:59 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +
Вот видишь - оно идёт из через связь с аккаунтами. Само по себе создание баланса должно быть частью создания счёта

2024-09-06 03:59 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    public BalanceDto updateBalance(BalanceDto balanceDto) {
Тут не совсем правильно реализовано. Баланс изменяется через операции оплаты, либо пополнения. Нужно создать такую логику, добавить туда валидаций по уму, констрейнтов - не может же баланс в минус уйти, и так далее.

2024-09-06 03:59 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    public BalanceDto updateBalance(BalanceDto balanceDto) {
Иначе у нас сейчас на этот метод дто с миллионом можно отправить, и себе баланс миллион установить

2024-09-06 13:53 UTC, Caveri95 commented on src/main/java/faang/school/accountservice/entity/Account.java
да, окей, возьму

2024-09-06 13:54 UTC, Caveri95 commented on src/main/java/faang/school/accountservice/controller/BalanceController.java
хорошо, перенесу

2024-09-06 14:20 UTC, Caveri95 commented on src/main/java/faang/school/accountservice/controller/BalanceController.java
Странно конечно получается, если мне нужно получить баланс, то пойду в контроллер аккаунта, там будет метод получить баланс аккаунта, в сервисе аккаунтов мне нужно будет идти в сервис балансов, искать баланс. По итогу возвращать BalanceDto в контроллерах балансов?

2024-09-10 02:18 UTC, pablo023 requested changes

2024-09-10 02:18 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    }
Зачем нам один метод для разных операций по балансу? Разнеси это

2024-09-10 02:18 UTC, pablo023 commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +        )*/
С этим что? Так не оставляем

2024-09-10 02:19 UTC, pablo023 commented
Раскидай ответственности, и пофикси конфликты.

2024-09-10 16:36 UTC, Caveri95 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    }
хорошо

2024-09-10 16:48 UTC, Caveri95 commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +        )*/
согласен, забыл раскомментить

2024-09-10 23:39 UTC, pablo023 approved these changes

2024-09-10 23:40 UTC, merged