Управление уникальными номерами счетов + Генерация уникальных номеров счетов
CorporationX/account_service pull request #188
Opened 2024-08-27 21:14 UTC by legionerkz

Centaur master bc5 bjs2 25821

2024-08-29 07:40 UTC, malkov34 commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    @ResponseStatus(HttpStatus.FOUND)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302
Немного не то

2024-08-29 07:40 UTC, malkov34 commented on src/main/java/faang/school/accountservice/validator/AccountValidator.java
> +            throw new DataValidationException("Owner project_id and Owner user_id cannot be both null");
Выполнение log.error можно переложить в DataValidationException, чтобы не дублировать текст

2024-09-02 14:28 UTC, malkov34 commented on src/main/java/faang/school/accountservice/dto/UpdateAccountDto.java
> -    private AccountType accountType;
Подскажи, как теперь будет определяться тип счета при его открытии?

2024-09-02 14:31 UTC, legionerkz commented on src/main/java/faang/school/accountservice/dto/UpdateAccountDto.java
> -    private AccountType accountType;
ты когда заводишь новый счет, в DTO передаешь его тип. Согласно префикасам и длине:  
    CORPORATE(4200, 18),
    INDIVIDUAL(4400, 18),
    INVESTMENT(5400, 16),
    RETIREMENT(5600, 16);
он сгенерирует новый счет. 
Если в update будешь передавать новый тип акаунта, то он сохранить номер, но поменяет его тип

2024-09-06 04:24 UTC, pablo023 requested changes
Немного надо исправить. Кстати, ты тесировал руками это?

2024-09-06 04:24 UTC, pablo023 commented on src/main/java/faang/school/accountservice/config/account/AccountGenerateConfig.java
> +    private Map<AccountType, Integer> accountsQuantity =new HashMap<>();
Тут надо бы ConcurrentHashMap, наверное, т.к. в неё ломиться будут скорее всего множеством потоков.

2024-09-06 04:24 UTC, pablo023 commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +    }
Я бы вот так сделал

          default AccountNumberSequence createSequenceIfNecessary(AccountType accountType) {
              return findByAccountType(accountType)
                      .orElseGet(() -> save(new AccountNumberSequence(accountType)));
          }

Просто имей ввиду, что так можно, и так это более конвенционально, и проще, чтоли

2024-09-06 04:24 UTC, pablo023 commented on src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java
> +        }
Это сервисная логика)

2024-09-06 19:34 UTC, legionerkz commented on src/main/java/faang/school/accountservice/config/account/AccountGenerateConfig.java
> +    private Map<AccountType, Integer> accountsQuantity =new HashMap<>();
исправил

2024-09-06 19:35 UTC, legionerkz commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +    }
понял. спасибо за пример.

2024-09-06 19:39 UTC, legionerkz commented on src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java
> +        }
перенес метод в сервис

2024-09-10 01:16 UTC, merged