Feature bjs2 25819 - Работа с балансами
CorporationX/account_service pull request #195
Opened 2024-09-01 21:08 UTC by grisatkac

https://faang-school.atlassian.net/browse/BJS2-25819

2024-09-11 00:47 UTC, pablo023 requested changes

2024-09-11 00:47 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        Balance foundedBalance = balanceRepository.getByAccountId(accountId)
foundBalance*

2024-09-11 00:47 UTC, pablo023 commented on src/main/java/faang/school/accountservice/validator/BalanceValidator.java
> +//    }
?

2024-09-11 00:47 UTC, pablo023 commented on src/main/java/faang/school/accountservice/validator/BalanceValidator.java
> +        if (balanceRepository.getByAccountId(accountId).isPresent()) {
Такая логика запретит одному пользователю иметь более одного баланса. Это противоречит тому, что у нас есть разные типы счетов, и каждый из счетов может иметь баланс соответственно.

2024-09-11 00:47 UTC, pablo023 commented on src/main/java/faang/school/accountservice/validator/BalanceValidator.java
> +    }
Название метода - проверяет что баланс нулл, а суть метода - проверить айдишник аккаунта. Тут расхождение.

2024-09-11 00:47 UTC, pablo023 commented on src/main/java/faang/school/accountservice/validator/BalanceValidator.java
> +    }
Это можно запетить просто на уровне дто или сущности, чтобы они нуллами не были - не придется писать этот код, и выполнять такие проверки.

2024-09-11 00:47 UTC, pablo023 commented on src/main/java/faang/school/accountservice/repository/BalanceRepository.java
> +    Balance create(BigDecimal authorizedBalance, BigDecimal actualBalance, String currency, Long accountId);
Зачем нам тут кверя, если мы наследуясь от JpaRepository, имеем метод save? Мы можем в сервисе создать сущность, которая нам нужна, и засэйвить её вот так же?

2024-09-11 00:47 UTC, pablo023 commented on src/main/java/faang/school/accountservice/repository/BalanceRepository.java
> +    Balance create(BigDecimal authorizedBalance, BigDecimal actualBalance, String currency, Long accountId);
Или в этом подходе есть смысл?

2024-09-14 22:07 UTC, grisatkac commented on src/main/java/faang/school/accountservice/model/Balance.java
> +    }
> Это лучше через аннотации генерить - точно не ошибешься)

принято)

2024-09-14 22:08 UTC, grisatkac commented on src/main/java/faang/school/accountservice/validator/BalanceValidator.java
> +//    }
> ?

упс, ненужное видимо забыл удалить

2024-09-17 20:42 UTC, grisatkac commented on src/main/java/faang/school/accountservice/validator/BalanceValidator.java
> +    }
> Это можно запетить просто на уровне дто или сущности, чтобы они нуллами не были - не придется писать этот код, и выполнять такие проверки.

действительно, я делал запрет на уровне дто, но хз, почему тут ещё проверял, спасибо)

2024-09-17 20:46 UTC, grisatkac commented on src/main/java/faang/school/accountservice/repository/BalanceRepository.java
> +    Balance create(BigDecimal authorizedBalance, BigDecimal actualBalance, String currency, Long accountId);
> Или в этом подходе есть смысл?
 я лишь это делал потому что при сохранении надо было подтянуть сначала Account сущность, мне этого не захотелось делать

2024-09-18 19:08 UTC, merged