Tasks BJS2-25833 BJS2-25834 BJS2-25838
CorporationX/account_service pull request #198
Opened 2024-09-03 19:23 UTC by fokinms

BJS2-25833
BJS2-25834
BJS2-25838

2024-09-06 00:22 UTC, pablo023 requested changes

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    FROZEN,
Не критично, но такое называют SUSPENDED, или HOLD. Frozen это замороженный, буквально как покрытый коркой льда, переводится.

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/repository/AccountOwnerRepository.java
> +""")
Лучше сделать через upsert. На больших данных это будет лучше работать, потому что выполняет проверку на наличие записи и вставку данных в одной операции. Плюс это будет атомарно, что позволит меньше нагружать базу. 

INSERT INTO owner_account (owner_id, owner_type)
VALUES (:accountOwnerId, :ownerType)
ON CONFLICT (owner_id, owner_type) 
DO NOTHING
RETURNING *;

Почитай про это. Только ещё индекс надо для этого, чтобы оно работало

CREATE UNIQUE INDEX idx_owner_account_unique ON owner_account (owner_id, owner_type);

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public AccountDto get(AccountDto accountDto) {
getAccount*

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public AccountDto open(AccountDto accountDto) {
openAccount*

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        Account account = Account.builder()
Добавь в сущность конструктор, который принимает на вход номер, баланс, оунера, и дто вот это вот, чтобы тут не расписывать эту логику создания объекта.

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public AccountDto block(AccountDto accountDto) {
blockAccount / suspendAccount

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public AccountDto open(AccountDto accountDto) {
У тебя этот метод никак не отреагирует, если уже есть такой аккаунт у такого пользователя. Наверное эксепшен было бы кинуть ему неплохо, ну и как-то залогировать. Нужен метод приватный для этого.

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        account.setAccountStatus(AccountStatus.FROZEN);
Мне кажется, нужна проверка какая-то тут. Нельзя заблокировать закрытый, или заблоченый аккаунт, например.

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public AccountDto close(AccountDto accountDto) {
closeAccount*

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        account.setAccountStatus(AccountStatus.CLOSED);
Тоже проверить бы, что это можно вообще сделать. И вообще, добавить бы проверок, которые позволят это делать только со своим собственным аккаунтом. А то я зная апишку примерно, могу любой аккаунт заблочить, не являясь владельцем.

2024-09-06 00:22 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java
> +            return new RuntimeException("Cache is not exist for this account type " + accountType);
does not exist*

2024-09-06 00:22 UTC, pablo023 commented on src/main/resources/db/changelog/changeset/V001__account-service_account_balance_sequences.sql
Огромная получается, их лучше дробить, чтобы по названию было понятно, что она делает. Тот же Single Responsibility принцип.

2024-09-08 09:13 UTC, fokinms commented on src/main/java/faang/school/accountservice/cache/AbstractFreeAccountNumbersCache.java
> +    private boolean lessThanMin() {
Done

2024-09-08 09:15 UTC, fokinms commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    FROZEN,
Done

2024-09-08 09:16 UTC, fokinms commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public AccountDto get(AccountDto accountDto) {
Done

2024-09-08 10:30 UTC, fokinms commented on src/main/java/faang/school/accountservice/cache/AbstractFreeAccountNumbersCache.java
> +            cacheKeySet.add(createFreeNumber(number, numberOfDigits));
а здесь работает в таком виде, и это потокобезопасно согласно пункту 3.2 статьи (https://www.baeldung.com/java-concurrent-hashset-concurrenthashmap#2-the-newkeysetdefaultvalue-method). инициализация сэта через метод keySet с дефолтным value-параметром дает возможность использовать методы add и addAll потокобезопасно. Проверил несколько раз создав таску из рекомендации выше, использовал 5 потоков с 30 тасками в каждом. Возможно, более глубокие тесты можно провести и попробовать уронить, но таким количеством не получилось)

2024-09-08 10:30 UTC, fokinms commented on src/main/java/faang/school/accountservice/cache/AbstractFreeAccountNumbersCache.java
> +        cache.remove(number);
Действительно, в таком варианте падало в многопоточке. Переписал. Получаю потокобезопасный сэт с помощью статического метода класса ConcurrentHashMap. При этом не страдает производительность (эквивалентна HashSet)

2024-09-08 10:37 UTC, fokinms commented on src/main/java/faang/school/accountservice/cache/AbstractFreeAccountNumbersCache.java
> +                .valueOf(prefix * (long) Math.pow(10, numberOfDigits - numberOfDigitsInPrefix));
Переписал. Так код чище) Не знал про эти возможности, спасибо

2024-09-08 10:57 UTC, fokinms commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        account.setAccountStatus(AccountStatus.FROZEN);
Доработал. Первую версию писал без проверок, протестировать такой формат генерации в принципе. Возможно, ошибку стоит кастомизировать? Или использовать существующие подходящие. Как обычно обрабатывают такие вещи в проде?

2024-09-08 11:08 UTC, fokinms commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public AccountDto open(AccountDto accountDto) {
Тут по заданию условие такое: каждая сущность, у которой может быть счет, может иметь их несколько, в том числе однотипных, как я понял ("Любой пользователь, а также проект, может иметь несколько личных платежных счетов для совершения платежей."). Здесь в методе при попытке создания счета метод сервиса владельцев счетов через репозиторий либо возвращает этого владельца если он уже есть и позволяет создать новый счет, либо если это первое обращение к сервису то создает владельца и возвращает его для дальнейшего создания счета. Можно запретить создавать счета одного типа, в принципе, но подумал что банки такое позволяют делать (несколько накопительных счетов в одном ЛК, несколько дебетовых, или один дебетовый с несколькими картами), наверное и тут тоже можно. Как решим?

2024-09-08 11:54 UTC, fokinms commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        Account account = Account.builder()
Done. Это частая практика на проектах множество конструкторов под разные нужды?

2024-09-08 12:02 UTC, fokinms commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        account.setAccountStatus(AccountStatus.CLOSED);
По проверке что уже закрыт - добавил условие, а по проверке собственник или нет - я бы посоветовался на созвоне. собственник счета сборная сущность, это может быть не только юзер, но и проект, думаю что нужно будет концепцию определить, т.к. в UserContext кроме айдишника из другого сервиса ничего нет

2024-09-08 12:54 UTC, fokinms commented on src/main/java/faang/school/accountservice/cache/CompanyFreeAccountNumbersCache.java
> +    }
Done

2024-09-10 02:30 UTC, merged