BJS2-25839
CorporationX/account_service pull request #199
Opened 2024-09-03 20:21 UTC by fraifree

2024-09-06 00:44 UTC, pablo023 requested changes

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/entity/Balance.java
> +    private double balance;
Не лучший тип данных для отображения баланса

https://www.baeldung.com/java-money-and-currency

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/enums/Operation.java
> +    TOP_UP,
RECEIVING

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/enums/Operation.java
> +    PAY,
SPENDING

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/enums/Operation.java
> +    REFUND
С точки зрения логики внутри бэкенда самой операции зачисления - лишнее

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    public void freezeBalance(Balance balance, double sum) {
suspendBalance*

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    private boolean isEnough(double paySum, double balanceSum) {
private boolean isBalanceSufficient*

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    private boolean isEnough(double paySum, double balanceSum) {
Я бы здесь ещё добавил различные статусы для состояния платежа - например, недостаточный баланс, или успех, или что-то ещё. Так как логика отмены может быть гибкой, например - из-за того, что баланс то позволяет, но вот пользователь поставил ограничение на транзакции - например, чтобы нельзя было за раз тратить больше чем n денег. Либо такое ограничение наложил банк. по сути, это - не ошибка, просто можно было бы развить немного.

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +            newBalance.setBalance(newBalance.getBalance() - sum);
Было бы логичнее вот это до balanceRepository.save(balance) делать, а то как-то оно задом наперед тут.

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        Balance newBalance = balanceRepository.save(balance);
Опять таки, сохраняешь перед тем, как проапдейтить. На звонке решили, что этот метод вообще разносим.

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    @Async
Когда ты кидаешь метод в асинк, он выполняется в отдельном потоке. А транзакции по дефолту завязываются на текущий поток. Что это значит? Транзакция будет открыта в одном потоке (в том, который вызвал метод), а выполнение метода уйдёт в другой поток, где транзакция не будет активной. И всё, ты думаешь, что всё под контролем с транзакциями, а на деле ты вне транзакции, и это может привести к тому, что изменения не сохранятся или откатятся неправильно.

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    )
Тут история в том, что Retryable по сути работает как обёртка, которая пробует несколько раз выполнить метод при ошибках (в твоём случае, если случается OptimisticLockException). Но если ты закинул это всё в асинк, то ретрай тоже работает в другом потоке и может вести себя не так, как ты ожидаешь. В итоге — конфликты, не срабатывающие ретраи или странные результаты.

2024-09-06 00:44 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    @Transactional
Короче, транзакцию и ретрай оставляешь на методе, а асинк - кидаешь на внешний вызывающий конкретный апдейт метод. updateBalanceAsync как-то так назвать можно.

2024-09-10 02:36 UTC, pablo023 requested changes

2024-09-10 02:36 UTC, pablo023 commented on src/main/java/faang/school/accountservice/entity/Balance.java
> +// TODO: прописать миграцию после merge, проверить связь и раскомментировать
Об этом не забудь

2024-09-10 02:36 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    public PaymentStatus suspendBalance(Balance balance, BigDecimal sum) {
suspend - это приостановить, синоним "заблокировать".

2024-09-10 02:36 UTC, pablo023 commented
Пофикси конфликты, и дополни из того, что вмержили Мишино

2024-09-12 05:24 UTC, pablo023 requested changes
Вынеси логику по ансихронному хэндлингу в приватный метод сервиса, и это будет похоже на то, что нам нужно.

2024-09-12 05:24 UTC, pablo023 commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +                    return null;
Ой ей. Зачем же это всё? У тебя вот эта цепочка просто билдит http ответ, который из сервиса итак придет, и в ResponseEntity обернётся, т.к. у тебя аннотация RestController стоит. И ошибку ты тоже там обработать можешь. На API слой не нужно это всё выносить.

2024-09-12 05:24 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    public CompletableFuture<PaymentStatus> suspendBalance(Long accountId, BigDecimal sum) {
Писал уже, suspend - это блокировка. Тебе не нужно, чтобы метод, который блокирует баланс, принимал какую-то сумму. Где-то ошибка - либо в названии метода, либо в логике того, что он делает.

2024-09-12 05:24 UTC, pablo023 commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    public DeferredResult<ResponseEntity<PaymentStatus>> processPayment(@PathVariable Long accountId, BigDecimal sum) {
Вытащи везде здесь обёртку ResponseEntity, у тебя аннотация RestController в неё оборачивает по дефолту.

2024-09-20 00:32 UTC, pablo023 requested changes

2024-09-20 00:32 UTC, pablo023 commented on src/main/java/faang/school/accountservice/entity/Account.java
> +import jakarta.persistence.*;
Вот это, кстати, неправильно. Никогда так не делаем - тащим импортов ровно столько, сколько нужно, через звездочку не тянем всю либу.

2024-09-20 00:32 UTC, pablo023 commented on src/main/java/faang/school/accountservice/entity/Balance.java
> +import jakarta.persistence.*;
Аналогично.

2024-09-20 00:32 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +            balance.setBalance(balance.getBalance().subtract(sum));
balance.getBalance() - точно? Не balance.getAuthorizedBalance()?

2024-09-20 00:32 UTC, pablo023 commented on src/main/java/faang/school/accountservice/service/BalanceService.java
Методы transferToAuthorizedBalance, spendFromAuthorizedBalance, и processPayment не защищены от того, что несколько потоков загонят их в негативные. У тебя для этого есть isBalanceSufficient, и ты оптимистик локом от этого пытаешься защититься, но в конце я бы добавлял такую проверку дополнительно, что баланс не ушел в негатив.

2024-09-20 06:26 UTC, fraifree commented on src/main/java/faang/school/accountservice/entity/Account.java
> +import jakarta.persistence.*;
Переустанавливал идею и забыл поставить настройку в код стайле, поменял

2024-09-20 06:26 UTC, fraifree commented on src/main/java/faang/school/accountservice/entity/Balance.java
> +import jakarta.persistence.*;
Переустанавливал идею и забыл поставить настройку в код стайле, поменял

2024-09-20 06:27 UTC, fraifree commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +            balance.setBalance(balance.getBalance().subtract(sum));
Да, затуп, тут же изменяется значение AuthorizationBalance

2024-09-20 07:09 UTC, fraifree commented on src/main/java/faang/school/accountservice/service/BalanceService.java
я об этом даже не подумал, очень важный момент, который отразится на дальнейшей логике программы, когда уже перейду к операциям

2024-09-20 14:48 UTC, merged