BJS2-27510 initial commit
CorporationX/account_service pull request #212
Opened 2024-10-22 07:02 UTC by soulasphyxia

Описал сущность Account в соответствии с задачей https://faang-school.atlassian.net/browse/BJS2-27510, написал миграции. Решил вынести владельцев счета в отдельную таблицу, для того, чтобы не хранить дублирующиеся данные, сделал пару (owner_id, owner_type) уникальными, чтобы предотврадить возможность дублирования этой записи в таблице. для упрощения поиска по владельцу сделал индекс по owner_id в таблице accounts и индекс по уникальной паре (owner_id, owner_type) в accounts_owners. еще прикреплю схемку, может кому-то так проще будет 
![image](https://github.com/user-attachments/assets/4b0a9eb8-fd66-460b-b0d4-d78b165c2588)

2024-10-22 07:07 UTC, soulasphyxia commented
вопрос: мы хотим добавлять каскадность в сущность AccountsOwners, чтобы при удалении владельца, его счета также удалялись? что думаете?

2024-10-22 08:57 UTC, ArstanSubanov approved these changes
Молодец!) Вроде всё логично, но я лекции ещё не смотрел, поэтому могу оценить только небольшим багажом знаний) По поводу каскадного удаления, я бы вообще ничего не удалял, юзера мы вроде не удаляем, а просто ставим статус неактивный, счета мы не удаляем и ставим статус заморожен/закрытый. Ничего не удаляем, храним для отчётов/статистики)

2024-10-22 09:16 UTC, aassylkhan commented
> вопрос: мы хотим добавлять каскадность в сущность AccountsOwners, чтобы при удалении владельца, его счета также удалялись? что думаете?

скорее не удалять, а сделать неактивным. Влад говорил про это, не знаю в какой лекции

2024-10-22 09:19 UTC, aassylkhan approved these changes

2024-10-22 09:19 UTC, aassylkhan commented on src/main/java/faang/school/accountservice/model/Account.java
> +    private Long version;
я не совсем понял про версию, для чего он нужен?)

2024-10-22 09:48 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/model/Account.java
> +    private Long version;
это требование такое) в описании задачи можешь прочитать, там подробно расписано зачем этот аттрибут нужен. если вкратце - для того чтобы контролировать состояние сущности в многопоточной среде

2024-10-22 10:31 UTC, SharkB38 approved these changes

2024-10-22 10:31 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @Enumerated(EnumType.STRING)
Единственное что хочу заметить это EnumType. Много где в проекте, стоит ORDINAL а не STRING. Возможно это сделано для удобства межсервисного взаимодействия, но я не уверен. Считаю над этим надо подумать

2024-10-22 11:01 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @Enumerated(EnumType.STRING)
да, я думал над этим, это хороший вопрос в каком формате хранить enum, я почитал https://stackoverflow.com/questions/6789342/jpa-enum-ordinal-vs-string, но так и не понимаю как нам конкретно рассуждать в этом случае) ordinal немного быстрее, но есть проблема, что им могут изменить порядок(решается тестом), также ordinal читается хуже, если нет доп. таблиц-справочников(у нас я нашел только таблицу country). наверное тоже поменяю на ordinal, надеюсь смогу найти обоснование и какая практика лучше)

2024-10-22 11:12 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @Enumerated(EnumType.STRING)
Читается действительно хуже тут ты прав

2024-10-22 11:20 UTC, RuslanIovlev commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @Enumerated(EnumType.STRING)
Как я понял ordinal экономит место, но string легче читается, и вопрос если в таблицу добавить значение в начало, как поведет себя ordinal

2024-10-22 11:21 UTC, RuslanIovlev commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @Enumerated(EnumType.STRING)
Надо узнать у маши как лучше

2024-10-22 11:39 UTC, RuslanIovlev approved these changes

2024-10-22 12:29 UTC, wmwmaks commented on src/main/java/faang/school/accountservice/model/Account.java
> +    private String accountNumber;
а если попробовать сделать его UUID?

2024-10-22 12:34 UTC, wmwmaks approved these changes
Спасибо за краткое пояснение по задаче👍

2024-10-22 12:39 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/model/Account.java
> +    private String accountNumber;
да, я тоже досмотрел лекцию и пошел все менять) насчет accountNumber не уверен, что его надо таким делать, а вот ID можно, для интересно) хотя уже представляю ситуацию, когда нужно проверить в контроллере какой-то ендпоинт и надо идти в базу копировать этот uuid гигантский)

2024-10-22 20:29 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @Enumerated(EnumType.STRING)
Вы здесь всё верно написали) ordinal используется только в случае оптимизации. Это не так уже часто нужно на самом деле) По умолчанию всегда используется строка - как вы и написали - это и безопаснее, и читается легче. Так что ordinal нужно использовать только тогда, когда есть явная аргументация - зачем. Например, "сейчас у нас база данных занимает 10 гб, мы хотим сократить используемую память. Если поменяем string на ordinal, то будет 8 гб." - тогда точно меняем =) 
Если в проекте везде используется ordinal, то скорее всего как раз предполагается большое количество этих объектов в базе данных (т.е. можно полагать, что уже до вас было обсуждение, где решили, что экономить место важно), а значит лучше выдержать заданный стиль

2024-10-22 20:42 UTC, mysosnovskaya requested changes

2024-10-22 20:42 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/enums/Currency.java
> +    RUB
Вообще говоря запятую рекомендуется оставлять после последнего значения) Это мелочь, но удобнее будет добавлять следующие значения)

2024-10-22 20:42 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "accounts_id_seq")
Поясни, почему не подходит IDENTITY?

2024-10-22 20:42 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/model/Account.java
> +    private String accountNumber;
Согласна, что uuid не подойдет. Как я поняла, это номер счета, который вообще говоря не мы генерируем, он нам приходит от пользователя.

2024-10-22 20:42 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/model/AccountOwner.java
> +    @Enumerated(EnumType.STRING)
Тут тогда тоже ordinal нужен?

2024-10-22 20:42 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    owner_id bigint NOT NULL,
Тут должен быть id из accounts_owners, наверное?

2024-10-22 20:42 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    status varchar(128) NOT NULL DEFAULT 'ACTIVE',
В коде у тебя это целое число (ORDINAL), а здесь по умолчанию ACTIVE

2024-10-22 20:42 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +CREATE INDEX IF NOT EXISTS idx_accounts_owners_owner_id_owner_type ON public.accounts_owners(owner_id, owner_type);
Если у тебя на этих колонках уже висит unique, то отдельно индекс создавать не нужно, он уже будет создан (из-за UNIQUE)

2024-10-23 13:03 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "accounts_id_seq")
Identity конечно подходит, просто в лекции сказали, что лучше, как и например в случае с тредпулами, создать свой, чтобы было больше контроля за данным компонентом. я сам всегда полагался на последовательности в postgreSQL, решил попробовать создать свою последовательность для автоинкремента id

2024-10-23 13:04 UTC, soulasphyxia commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +CREATE INDEX IF NOT EXISTS idx_accounts_owners_owner_id_owner_type ON public.accounts_owners(owner_id, owner_type);
спасибо, не знал!

2024-10-23 15:27 UTC, mysosnovskaya requested changes

2024-10-23 15:27 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/model/Account.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "accounts_id_seq")
Поняла, ок. Больше контроля это, конечно, хорошо, так что пусть остается. Но на моей практике обычно этого не делаем, если ничего специфичного не нужно

2024-10-23 15:27 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    owner_type varchar(128) NOT NULL,
Если используешь ordinal, то тип колонки должен быть целочисленный. Для колонок в таблице accounts тоже актуально. Это поправь и можешь сам смержить, чтобы не блокировать команду)

2024-10-23 20:12 UTC, soulasphyxia commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    owner_type varchar(128) NOT NULL,
затестил, вроде все работает, сущности вставляются, замержил

2024-10-23 20:12 UTC, merged