BJS2-26200 - Created payment account
CorporationX/account_service pull request #216
Opened 2024-10-22 18:13 UTC by GusevVrn

2024-10-23 17:02 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    }
Все нашел где оно надо, интересно конечно, но на первый взгляд не понятно

2024-10-23 18:50 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    }
Ну просто чтоб ты закрытый аккаунт например не мог заморозить, это же бессмысленно.
Либо Активный не перевел в активный, это же бесполезная операция тоже.
Тут просто некий контракт, как этими статусами пользоваться, возможно еще добавятся. На этих 3х конечно это не особо очевидно.
Ну если Маша скажет что фигня, то удалю

2024-10-23 19:02 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/owner/Owner.java
> +    private int id;
Ну я чет решил что мы не сделаем больше чем int

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/owner/OwnerService.java
> +        Optional<Owner> owner = ownerRepository.findByName(ownerName);
тоже мб сразу return без Optional?

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/type/TypeService.java
> +        Optional<Type> type = typeRepository.findByName(typeName);
и тута

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DDL.sql
> +CREATE TABLE as_owner (
тут тоже тогда нужно поменять bigint, если на long айдишники изменишь

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DDL.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
Не уверена, что в updated_at нужно сразу время устанавливать, как-то странно. Я бы пустым оставила

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/config/generator/AccountNumberGenerator.java
> +
лишний отступ

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/account/AccountController.java
> +
лишний отступ

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/account/AccountController.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
а вот тут статус не HttpStatus.NO_CONTENT должен быть?

2024-10-23 19:15 UTC, StepnovaVarvara commented on src/test/java/faang/school/accountservice/service/owner/OwnerServiceTest.java
> +
лишний отступ

2024-10-23 19:25 UTC, GusevVrn commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DDL.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
хз, на моей памяти так всегда делалось, пока оставлю

2024-10-23 19:26 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    static {
пока ничего лучше в голову не пришло

2024-10-23 19:47 UTC, mysosnovskaya requested changes
Даа, Паша, я не ожидала, что ты сразу всю задачу сделаешь =) Вообще задумывалось так, что сначала ты сделаешь ПР с entity и миграциями, чтобы разблокировать команду, а потом всё остальное. А то сейчас этап ревью может затянуться, а команда всё это время будет ждать. Ну и к тому же я бы хотела, чтобы основной код поревьювили как можно больше человек, а не только Сергей (и Варя - уже успела после того, как ты мне в ревью отправил). Я очень тебя прошу разделить ПРы, чтобы мы уже разблокировали всех. Я завтра утром/днем смогу зайти и проверить именно твой ПР с моделями (тут замечаний-то по сути нет). А может даже сегодня ещё успеешь)
Но вообще ты, конечно, поразил меня своей работоспособностью - эта задача была на неделю рассчитана)) Крутой результат!! 
Если есть сомнения с разделением ПРов - пиши в чат, обсудим)

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/config/generator/AccountNumberGenerator.java
> +    public String generateRandomStringInRange(int min, int max) {
А где в условии задачи написано, что мы должны сами генерировать номер счета? Я просто думала, что это приходит извне, нет?)

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/controller/account/AccountController.java
> +    @PostMapping("/{accountNumber}/block")
Не лучше ли тут Patch подходит?

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/controller/account/AccountController.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Почему NOT_FOUND? Наверное, ты хотел no content написать?)

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    private long id;
А где ты этим id пользуешься? У тебя в эндпоинтах запросы идут по number. Может тогда стоит только его оставить? Или наоборот - в эндпоинтах работать по id?

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @Column(name = "number")
Column можно не писать, если имя совпадает

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/owner/Owner.java
> +@Data
Аннотацию Data лучше не использовать с entity. Подробнее об этом здесь:
https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/type/Type.java
> +public class Type {
Дать бы больше конкретики в названии. AccountType например

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/type/Type.java
> +    private List<Account> accounts;
Тебе точно это здесь нужно?

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    private static final Map<AccountStatus, List<AccountStatus>> actionsMap = new EnumMap<>(AccountStatus.class);
Надо переименовать, чтобы было понятно, что это возможные переходы между статусами. И назвать надо КАК_КОНСТАНТУ

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/exception/ExceptionApiHandler.java
> +                .body(exception.getMessage());
У нас используются только json, никаких обычных строк. Нужно создать отдельный dto класс для ошибок и отдавать здесь его (без ResponseEntity). Статус код определяется соответствующей аннотацией

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        log.info("getAccounts() - start");
Это в debug

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    public List<AccountStatus> getAvailableActions() {
А может быть сразу сделать метод, который принимает как параметр желаемый новый статус и возвращает true/false - можно в него перейти или нельзя?) Просто как идея. 
В целом всю эту логику вообще можно было бы вынести в отдельный класс, но тут пока принципиальной разницы нет. Можно оставить. Просто обычно такую логику в модельных классах (в том числе и в перечислениях) не пишут

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/config/generator/AccountNumberGenerator.java
> +    public String generateRandomStringInRange(int min, int max) {
И если оставляем это, то надо определиться, у тебя это всё-таки максимально общий метод, который просто генерирует случайную строку (исходя из названия метода) или здесь генерируется именно номер счета (исходя из названия класса)? Если второе, то тогда можно сюда AccountProperties заижектить, так логичнее будет

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DDL.sql
> +CREATE TABLE as_owner (
А зачем ты везде as подписываешь?

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DDL.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
Да, это ок, пусть остается)

2024-10-23 19:47 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DML.sql
> +INSERT INTO as_owner("name")
Вообще для вставки данных существует более красивый подход (с использованием scv), но это скорее на будущее. 
https://docs.liquibase.com/change-types/load-data.html

2024-10-23 20:01 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/config/generator/AccountNumberGenerator.java
> +    public String generateRandomStringInRange(int min, int max) {
мы создаем счет и нам кто-то будет указывать какой номер будет у счета? ну не

2024-10-24 19:55 UTC, GusevVrn commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DML.sql
> +INSERT INTO as_owner("name")
У меня вообще вопросы почему мы не используемся xml версионированием, сразу бы и changeSet бы попробовали в одном файле, а так кучу файлов плодим.
Везде где бы не находил доку, пишут что для liquibase лучше всего использовать старомодный xml, так он на удивление в этом случае более удобней в использовании.

2024-10-24 19:55 UTC, GusevVrn commented on src/main/resources/db/changelog/changeset/V001__account-service_account_DDL.sql
> +CREATE TABLE as_owner (
account service) не знаю)

2024-10-24 19:55 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/type/Type.java
> +    private List<Account> accounts;
Ну если в теории мы будем работать с типами, сможем получить список счетов с таким типом.
Ну и обычно всегда же указывается связь с двух сторон.

2024-10-24 19:55 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/owner/Owner.java
> +@Data
Да, я знаю про эту тему, просто у нас во всех сервисах использовалась Data. решил сюда тоже залепить

2024-10-24 19:55 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @Column(name = "number")
Пусть будет, странно выглядит когда что-то указано а что-то нет

2024-10-24 19:58 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        log.info("getAccounts() - start");
вот тут не совсем понимаю, в чем отличие от остальных методов, мы же не выводим тут весь список в конце что получили.
если из расчета что этим методом чаще будем пользоваться - ну не знаю, мы таким же макаром просто перебором по айдишнику можем пройтись

2024-10-24 20:52 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/enums/AccountStatus.java
> +    private static final Map<AccountStatus, List<AccountStatus>> actionsMap = new EnumMap<>(AccountStatus.class);
а почему snake case? это же не константа

2024-10-24 21:44 UTC, GusevVrn commented
@mysosnovskaya ну я попытался статусы вынести, через boolean тож попробовал но тогда как-то не оч в сервисе будет, больше кода причем с if-else. может до меня не дошло как можно иначе

по самим статусам - мне не нравится как у нас собирается мапа эта но я вообще не понимаю как можно по другому реализовать, под каждый статус создавать свой отдельный бин с вариантами статусов, это еще хуже чем сейчас будет.

2024-10-26 18:37 UTC, mysosnovskaya reviewed
Мелочи остались и будем мержить) Класс 👍

2024-10-26 18:37 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/config/generator/AccountNumberGenerator.java
> +        if (minLength >= maxLength) {
Наверное нет смысла проверять это при каждом вызове метода? Параметры же не изменятся? Можно в конструкторе это сделать, если хочется)

2024-10-26 18:37 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/status/AccountStatusActions.java
> +public class AccountStatusActions {
Класс всегда называется существительным)

2024-10-26 18:37 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/status/AccountStatusActions.java
> +    public List<AccountStatus> getAvailableActions(AccountStatus currentStatus) {
А по-моему неплохо получилось в отдельном классе. 
Я ещё предлагала сделать метод, который пример два статуса (from и to) и скажет, возможен ли переход (boolean). Как думаешь, так не лучше в коде будет смотреться, не удобнее будет? Если нет, оставляй так

2024-10-26 18:37 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/status/AccountStatusActions.java
> +            throw new NoSuchElementException("Status " + this + " is unknown");
this? Тут должен быть currentStatus видимо

2024-10-26 18:37 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +    public AccountDto getAccountByNumber(long accountId) {
ByNumber или ById всё-таки?

2024-10-26 18:37 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        log.info("closeAccount() - start, accountNumber - {}", accountId);
Или accountId вместо accountNumber?

2024-10-27 18:35 UTC, mysosnovskaya approved these changes
Посмотри мой единственный коммент и можешь мержить самостоятельно)

2024-10-27 18:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/config/generator/AccountNumberGenerator.java
> +    private final AccountProperties accountProperties;
Точно нужно это поле отдельно? Вроде нигде не пользуемся)

2024-10-28 17:42 UTC, merged