Создание платежного счета BJS2-26951
CorporationX/account_service pull request #219
Opened 2024-10-23 09:23 UTC by Peregruzochka

1. Не реализовывал здесь логику генерации уникальных номеров для счетов, т.к. это требуется делать в другой задаче
2. Счет пока что не несет в себе информацию о балансе, т.к это требуется сделать в другой задаче
3. По условию задачи счет можно прикрепить как к проекту, так и к пользователю, здесь это обозначается как externalId. Для того что избежать ситуаций, когда userId и projectId одинаковые, используется OwnerType.

2024-10-23 16:07 UTC, mrkorolev reviewed
Можно было ссылку на таску оставить в описании PR, а так мне понравилось)

2024-10-23 16:07 UTC, mrkorolev commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    @PutMapping("/freezing")
freeze, unfreeze

2024-10-23 16:07 UTC, mrkorolev commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    @PutMapping("/closing")
close

2024-10-23 16:07 UTC, mrkorolev commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    }
Можно постараться и один метод сделать для этого (а может и нельзя :))

2024-10-23 16:07 UTC, mrkorolev commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +                .orElse(createOwner(externalId, ownerType));
Мне нравится этот кусок - если нет владельца сделали его, норм

2024-10-23 16:07 UTC, mrkorolev commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    }
Попробуй через UUID

2024-10-23 20:45 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    }
Прост это не моя задача вроде как😅

2024-10-23 20:47 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/dto/account/AccountDto.java
> +    private String accountNumber;
Я просто не понимаю концепцию от 12 до 20 символов, если можно сразу сделать 20 символов и не париться

2024-10-23 20:48 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    }
Люблю когда один метод реализует одну логику без регистрации и смс

2024-10-23 21:48 UTC, mrkorolev commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +    }
Все, дочитал

2024-10-24 07:09 UTC, Peregruzochka commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
хороший вопрос, я прост смотрел как делается в других микросервисах
GENERATED ALWAYS AS IDENTITY - это нужно, чтобы значение генерировалось при каждой вставке
А вот UNIQUE тут как раз таки не нужен

2024-10-24 20:20 UTC, 20cognosce requested changes
Ну, микроправочки не будут лишними

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    public List<AccountDto> getAccountByNumber(@RequestParam Long externalId, @RequestParam OwnerType type) {
getAccountByOwner

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    public List<AccountDto> getAccountByNumber(@RequestParam Long externalId, @RequestParam OwnerType type) {
/owner - не должно быть в пути, это просто фильтр, как и номер

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/account/Account.java
> +    @Enumerated(EnumType.STRING)
Экономить на буквах...

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/account/Account.java
> +    private Long id;
Может пора переходить на uuid

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/account/AccountStatus.java
> +    FROZEN,
SUSPENDED

frozen - это пельмени в морозилке

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/owner/Owner.java
> +    private Long id;
uuid

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/owner/Owner.java
> +    private Long externalId;
user_service?

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/OwnerRepository.java
> +    Optional<Owner> findOwner(Long externalId, OwnerType type);
externalId о чем говорит?

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        Owner exsistOwner = ownerRepository.findOwner(externalId, ownerType)
exsist
можно переименовать

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        if (account.getStatus().equals(AccountStatus.ACTIVE)) {
NPE

2024-10-24 20:20 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        Object ownerDto = switch (type) {
switch так умеет? ну и фокусник...

2024-10-24 20:20 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +CREATE INDEX idx_payment_owners_external_type ON payment_owners (external_id, type);
Зачем был создан этот индекс?

2024-10-24 20:20 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    type VARCHAR(32) NOT NULL,
Форматирование Ctrl + Alt + L

2024-10-24 20:21 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/owner/Owner.java
> +    private Long externalId;
Реально, что это за поле

2024-10-25 09:00 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/model/owner/Owner.java
> +    private Long externalId;
Счет можно создать как для пользователя user_service, так и для проекта project_service

2024-10-25 09:45 UTC, Peregruzochka commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +CREATE INDEX idx_payment_owners_external_type ON payment_owners (external_id, type);
Для того чтобы ускорить выполнение выборки, когда необходимо получить счета на основе данных пользователя

2024-10-25 09:49 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        if (account.getStatus().equals(AccountStatus.ACTIVE)) {
У меня из базы приходит Optional, который я обрабатываю

2024-10-25 10:02 UTC, Peregruzochka commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +    type VARCHAR(32) NOT NULL,
в комьюнити не поддерживается автоформатирование SQL, чуть позже займусь тем, чтобы поставить ultimate

2024-10-26 11:52 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        if (account.getStatus().equals(AccountStatus.ACTIVE)) {
Тебе приходит аккаунт, а статус на null ты не проверяешь
но он у базе у тебя not null, так что ок

2024-10-26 11:52 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/OwnerRepository.java
> +    Optional<Owner> findOwner(Long externalId, OwnerType type);
Как одно поле может ссылаться одновременно и на человека, и на проект

2024-10-26 11:58 UTC, 20cognosce approved these changes

2024-10-26 11:58 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +CREATE INDEX idx_payment_owners_external_type ON payment_owners (external_id, type);
Я понимаю, но это поле у тебя не UNIQUE, конечно, я предполагаю, распределение значений этого поля будет хорошее, но всё же

2024-10-26 11:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/dto/account/AccountDto.java
> +    @NotNull(message = "\"externalOwnerId\" cannot be NULL")
Одинарные кавычки используй, не надо экранировать

2024-10-26 11:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    }
Криво всё равно
public getAccount

/accounts?q=NUMBER / q=USER / q=PROJECT
и в зависимости от енама мапь на методы

if else переделай

2024-10-26 11:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    }
Отдельный коммитом правки залей, вмёрджу пока так

2024-10-26 11:58 UTC, merged