Решение задачи "Работа с балансами"
CorporationX/account_service pull request #222
Opened 2024-10-23 17:14 UTC by lexus-74

2024-10-24 07:46 UTC, Peregruzochka reviewed
Ждем тесты

2024-10-24 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/dto/balance/BalanceDto.java
> +    private Long version;
Version в Entity необходим, для того чтобы разные потоки могли правильно взаимодействовать со строкой в таблице. Это значение в таблице/сущности меняется автоматически. Тот кто пользуется твоим API не должен как-то управлять этим значением.

2024-10-24 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/model/account/Account.java
> +}
А зачем ты сделал чужую задачу? Тебе не требуется реализовывать Account

2024-10-24 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/model/account/Account.java
> +    private BigDecimal amount;
Несмотря на то что тебе не надо было делать, не совсем понятно что такое amount и для чего он здесь нужен? у тебя есть Balance

2024-10-24 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        return savedAccount.getBalance();
Нужно нужно, ну он так тоже добавиться скорее всего
Тут просто логичнее работать с balanceRepository
Хотя с другой стороны так производится валидация того, что Account существует
Я бы пока не менял ничего

2024-10-27 15:16 UTC, 20cognosce requested changes

2024-10-27 15:16 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/dto/balance/BalanceDto.java
> +    private Long version;
Соглашусь, версия в ДТО не нужна

2024-10-27 15:16 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        return balanceRepository.save(storedBalance);
как ты обрабатываешь случай OptimisticLockException?

2024-10-27 15:16 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/balance/Balance.java
> +    @GeneratedValue(generator = "UUID")
Зачем ты тут поставил генерацию uuid

2024-10-27 15:16 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V001__account-service_create_balance.sql
> +    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
Если тут ты делаешь то же самое

2024-10-27 15:16 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V001__account-service_create_balance.sql
> +    ADD FOREIGN KEY (balance_id) REFERENCES balances (id);
А можно объединить?

2024-10-27 15:16 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/service/BalanceServiceTest.java
> +public class BalanceServiceTest {
1. Интеграционный тест попробуй написать
2. Ты добавил логику, что при создании аккаунта автоматом создается баланс, где на это тест?

2024-10-29 17:11 UTC, 20cognosce requested changes
В таком виде задача никуда не годится, не реализован весь необходимый функционал и крайне поверхностно исполнена имеющаяся бизнес-логика

Нужна серьёзная переработка задачи

Прошу усердно ознакомится с аналогичным решением:
https://github.com/CorporationX/account_service/pull/236/files
Не копировать, а вникнуть и разобраться. При необходимости - задавать вопросы в чате команды.

2024-10-29 17:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +            throw e;
И такая обработка ошибки - это шляпа

Когда запись в балансе изменяется, значение поля версии и время обновления также обновляются. Это позволяет системе отслеживать и контролировать версии записей и обнаруживать, если два или более процесса пытаются изменить одну и ту же запись одновременно. Если два процесса пытаются обновить запись с одинаковым значением версии, система может определить конфликт и предпринять соответствующие действия, например, откатить одно из изменений или предоставить уведомление о конфликте для разрешения. Поле версии используется для реализации механизма оптимистической блокировки и контроля версий данных

2024-10-29 17:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        storedBalance.setActual(balance.getActual());
Это все обновление? Где обновление таймстэмпов? Где проверка баланса, -1.000.000 мы присвоим и это будет ок?

2024-10-29 17:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +public class BalanceService {
Где авторизация и списание, Лёш, ты читал условие?

2024-11-03 14:35 UTC, Alginin commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        validateCurrency(money.currency());
А если валюта будет бакс?

2024-11-04 20:04 UTC, 20cognosce requested changes

2024-11-04 20:04 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +public class BalanceService {
Чет я реально может не понимаю, почему авторизация так сделана, объясни пожалуйста

Actual = 10.000
Приходит запрос на авторизацию 7.000

Ты оставляешь Actual 10.000
Authorization = 7.000

А я это понимаю как
Actual = 3.000
Authorization = 7.000

При клиринге ты просто из Authorization вычтешь сумму транзакции
А actual не будешь трогать.

В твоей реализации просто не понятен размер актуального счета, нужно одно с другим складывать и вычитать.
И в случае когда Authorization > Actual ты вообще не дашь больше ничего купить.

2024-11-05 16:28 UTC, lexus-74 commented on src/main/resources/db/changelog/changeset/V001__account-service_balance_auth_payment_drop_owner.sql
> +    DROP COLUMN owner_id,
вроде на дейли решили убрать  проверку действительности карты и  проверку ее владельца

2024-11-05 19:23 UTC, 20cognosce requested changes

2024-11-05 19:23 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        BigDecimal newActualBalance = balance.getActual().add(payment.getAmount());
Если мы делаем клиринг, то с авторизационного счета деньги списываются и всё
Ты же уже с актуального на авторизационный деньги перевел для резервирования

2024-11-05 19:23 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/service/BalanceServiceTest.java
> +        assertEquals(authPayment.getStatus(), AuthorizationStatus.CONFIRMED);
а то что Actual остался равен 400 ты не проверил

2024-11-07 14:52 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        validateActualBalanceToBeWrittenOff(authPayment);
А это почему не убрал
Тут нужна такая же проверка, но на авторизационный баланс

2024-11-07 14:54 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/service/BalanceServiceTest.java
> +        balance.setAuthorization(BigDecimal.valueOf(100));
Леш, опять баг
Если текущий баланс был бы 50 рублей, а в резерве так же 100, то из-за твоей валидации не пропустит платёж.

2024-11-07 14:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    }
Write off происходит с авторизационного баланса

2024-11-07 15:52 UTC, 20cognosce approved these changes

2024-11-07 15:52 UTC, merged