Работа с балансами BJS2-27149
CorporationX/account_service pull request #236
Opened 2024-10-24 19:29 UTC by sultan-inked

2024-10-25 06:33 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +package faang.school.accountservice.service.balance;
Помимо сущности баланс, пришлось создать сущность для авторизационного платежа, что бы помнить какая сумма была зарезервирована, и при утверждении сравнить с изначальной суммой, что необходимо в случае нескольких авторизационных платежей.

2024-10-25 06:46 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +package faang.school.accountservice.service.balance;
```java
public Balance multiplyCurrentBalance(UUID balanceId, Double value) {
```
метод Александра

2024-10-25 07:33 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/model/Account.java
> +package faang.school.accountservice.model;
Заглушка, PR Семена дополнит

2024-10-26 10:18 UTC, 20cognosce commented
Почему твой ПР линкуется к задаче Семёна по платёжному счету
Не тот номер

2024-10-26 11:35 UTC, 20cognosce requested changes

2024-10-26 11:35 UTC, 20cognosce commented on build.gradle.kts
> +    implementation("com.github.f4b6a3:uuid-creator:4.4.0")
Что это
Зачем...

2024-10-26 11:35 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        return authPaymentRepository.save(payment);
OptimisticLockException ты ловить будешь в ExceptionHandler?

2024-10-26 11:35 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +                .build();
В отдельный класс Mapper / Builder можно это вынести

2024-10-26 15:42 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        return authPaymentRepository.save(payment);
Сделал как у Семена, работает, проверил

2024-10-27 10:24 UTC, 20cognosce approved these changes

2024-10-27 10:24 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +            balanceRepository.flush();
saveAndFlush метод

2024-10-27 10:24 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceValidator.java
> +@EnableAsync
для чего это

2024-10-27 10:24 UTC, merged

2024-10-27 12:16 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/balance/BalanceValidator.java
> +@EnableAsync
Незнаю) Надо убрать

2024-10-27 12:17 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +            balanceRepository.flush();
Спасибо, изменил