Feature/bc 5720 add request table
CorporationX/account_service pull request #24
Opened 2023-09-06 18:22 UTC by YuliaQueen

https://faang-school.atlassian.net/browse/BC-5720

2023-09-06 20:00 UTC, tarrasoff approved these changes

2023-09-07 17:22 UTC, YuliaQueen commented on src/main/java/faang/school/accountservice/entity/request/RequestType.java
> +}
Я не знаю просто какие типы событий будут еще

2023-09-12 14:39 UTC, InnMish requested changes

2023-09-12 14:39 UTC, InnMish commented on src/main/java/faang/school/accountservice/dto/request/RequestDto.java
> +    private Integer version;
version - это внутреннее поле, пользователь не должен передавать его извне, или вообще кто-то вне приложения не должен его знать
Предлагаю убрать из dto. Мы его обновляем при изменениях, и используем только для внутренних операций

2023-09-12 14:39 UTC, InnMish commented on src/main/java/faang/school/accountservice/entity/request/Request.java
> +    private Integer userId;
Для id лучше Long

2023-09-12 14:39 UTC, InnMish commented on src/main/java/faang/school/accountservice/entity/request/Request.java
> +    private Instant lastModified;
😎

2023-09-12 14:39 UTC, InnMish commented on src/main/java/faang/school/accountservice/entity/request/Request.java
> +    private Map<String, Object> inputData;
А вот в этом поле значения сейчас успешно конвертируются в json? 
Не нужно тут @Convert(converter = MapToJsonConverter.class) использовать?

2023-09-12 14:39 UTC, InnMish commented on src/main/resources/db/changelog/changeset/V002__account-service_request.sql
> +                         user_id INT NOT NULL,
тут лучше BIGINT, особенно, если в сущности лонг будет 
Ну и вообще это стандарт для айди

2023-09-14 06:28 UTC, YuliaQueen commented on src/main/java/faang/school/accountservice/entity/request/Request.java
> +    private Instant lastModified;
> 😎

Это хорошо или плохо? )))

2023-09-14 06:31 UTC, InnMish commented on src/main/java/faang/school/accountservice/entity/request/Request.java
> +    private Instant lastModified;
Хорошо! Выбор Instant тут очень кстати)

2023-09-15 08:50 UTC, InnMish approved these changes

2023-09-15 08:56 UTC, merged