Initial commit BJS2-27510-logic
CorporationX/account_service pull request #242
Opened 2024-10-26 07:49 UTC by soulasphyxia

2024-10-26 07:56 UTC, soulasphyxia commented
такой вопрос, я знаю, что не очень хорошо использовать глаголы по REST'у, но я не совсем понял, как в таком случае сделать гибко обновление статуса (закрытие, заморозка счета и обратные операции), очень хотелось написать в ендпоинты /close и /freeze, чтобы было расширяемо и не нужно было менять метод update, а просто дописать новые методы в сервисе. вроде бы как REST это только рекомендации, и мне кажется, что если в таком случае можно сделать по SOLID, то может стоит пренебречь этим пунктом) что думаете? я долго сидел над этим и пока решил сделать через один метод... может кто видит как это можно вынести?

2024-10-26 09:16 UTC, SharkB38 requested changes

2024-10-26 09:16 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +    }
Может вот эти два метода объединить?

2024-10-26 09:16 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/filter/Filter.java
> +public interface Filter<T, E> {
Почему решил через дженерик сделать?

2024-10-26 09:16 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +        }
Здесь наверное проверку бы как в создании счета, на соответствие типа аккаунта и типа владельца

2024-10-26 09:16 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/service/account_owner/AccountOwnerService.java
> +public interface AccountOwnerService {
Мне нравится что в отдельный сервис это дело выделил

2024-10-26 09:16 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/enums/AccountType.java
> +    }
Кстати может вместо List сделать Set?

2024-10-26 12:11 UTC, aassylkhan commented on src/main/java/faang/school/accountservice/controller/AccountsController.java
> +    public void createAccount(@RequestBody @Valid CreateAccountDto createAccountDto) {
может лучше вернуть данные который создал?

2024-10-26 12:11 UTC, aassylkhan commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +@Slf4j
добавить бы логи)

2024-10-26 12:11 UTC, aassylkhan commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +        final List<Violation> violations = new java.util.ArrayList<>(ex.getBindingResult().getFieldErrors().stream()
java.util.ArrayList? может просто ArrayList?

2024-10-26 12:11 UTC, aassylkhan commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +        return new ConstraintErrorResponse(violations);
длинный метод. может создать для него дто?

2024-10-26 12:11 UTC, aassylkhan commented on src/main/java/faang/school/accountservice/enums/AccountType.java
> +    }
> Кстати может вместо List сделать Set?

плюс Set быстрее работает чем List

2024-10-26 13:04 UTC, ArstanSubanov reviewed
Что-то я много комментов оставил) Как ты посмотришь, я апрувну, просто я некоторые моменты не понял)

2024-10-26 13:04 UTC, ArstanSubanov commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +            } else {
Этот else вроде и не нужен?)

2024-10-27 06:16 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/filter/Filter.java
> +public interface Filter<T, E> {
я посмотрел на примере project_service, там мы для каждой сущноси писали свой интерфейс фильтра, хотя все они одинаковые, различаются только сущности

2024-10-27 06:16 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +        final List<Violation> violations = new java.util.ArrayList<>(ex.getBindingResult().getFieldErrors().stream()
да, что то плохо оно сымпортировалось...

2024-10-27 06:20 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +        AccountOwner accountOwner = accountOwnerService.getAccountOwnerById(accountDto.getOwnerId());
да, согласен, я когда писал, то не много не понял как это реализовать, щас появились идеи, сделаю!

2024-10-27 06:20 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +        AccountOwner accountOwner = accountOwnerService.getAccountOwnerById(accountDto.getOwnerId());
да, согласен, я когда писал, то не много не понял как это реализовать, щас появились идеи, сделаю!

2024-10-27 08:48 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/enums/AccountType.java
> +    }
да, спасибо, сделаю set

2024-10-27 08:50 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +@Slf4j
хорошо, добавлю больше логов

2024-10-27 08:51 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +        return new ConstraintErrorResponse(violations);
немного не понял.. я взял этот обработчик из предыдущих наших сервисов

2024-10-27 08:51 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +        return new ConstraintErrorResponse(violations);
немного не понял.. я взял этот обработчик из предыдущих наших сервисов

2024-10-27 08:53 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/dto/account/CreateAccountDto.java
> +    private final AccountStatus status = AccountStatus.ACTIVE;
да, согласен, тут не логично. вообще я думал, что создавать сразу замороженный или заблокированный счёт нет смысла, созданный счет по дефолту активный. тут забыл поправить

2024-10-27 08:59 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +            } else {
тут вообще какая-то ерунда написана) я переделаю, но изначально в задумке было, что если пришел статус закрыт, то проставляем время закрытия, а если, например, мы открываем закрытый аккаунт, то соответственно это поле нужно убрать)

2024-10-27 09:00 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +            } else {
не соглашусь, если мы делаем снова активным закрытый счёт, то мне кажется, что нужно это поле обратно в null ставить

2024-10-27 09:30 UTC, ArstanSubanov commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +            } else {
Ааа, тогда ок) Просто у нас в банках обычно создают новый счёт, а не открывают старый, поэтому написал, если закрытый счёт можно открыть, то ты прав)

2024-10-27 09:49 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/controller/AccountsController.java
> +    }
когда писал также не придумал как это реализовать, щас вроде идейка есть, попробую что то сделать

2024-10-27 12:49 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/controller/AccountsController.java
> +        return accountService.getAllAccounts(filterDto);
да, посмотрел лекцию, теперь фильтрация в памяти не прокатит)

2024-10-31 20:50 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +        Specification<Account> ownerIdSpec =
вот тут был вопрос. как я понял, эти спецификации нельзя мешать с запросами, где мы сами пишем что-то вроде findAllByOwnerId. поэтому я решил вручную добавить сюда эту спецификацию для корректной работы

2024-10-31 21:27 UTC, SharkB38 approved these changes
Ну с фильтрацией, пока не понятно будем разбираться

2024-10-31 21:27 UTC, SharkB38 commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +            IllegalAccountTypeForOwner.class,NotUniqueAccountNumberException.class})
Может пробел между ошибками?

2024-11-01 08:47 UTC, ArstanSubanov approved these changes
Класс👍

2024-11-01 08:47 UTC, ArstanSubanov commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +        Specification<Account> ownerIdSpec =
Когда я предложил добавить поиск аккаунтов по ownerId, я предполагал что будет два эндпоинта, один getAll( с Pageable и спецификациями) и getByOwnerId, так как мне кажется, что у одного owner вряд ли будет много аккаунтов) Но мне нравится твоя реализация, да и Маша вчера показала, что можно только одним методом возвращать разные списки, поэтому я бы тебе предложил, как вариант, вынести спецификацию ownerIdSpec в отдельный класс, также как и с другими фильтрами, в AccountFilterDto добавить поле ownerId и сделать его jsonIgnore, поле  @RequestParam Long ownerId сделать required = false, и в этом методе в filterDto добавить accountOwnerId, тогда он тоже автоматически применится) Конечно это при условии что нужно accountOwnerId получать через RequestParam, а не через ДТО. Это только моё предложение, может у Маши будет более лучшее решение)

2024-11-01 08:47 UTC, ArstanSubanov commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
Нужно не забыть про OptimisticLock)

2024-11-01 16:45 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
я на самом деле думал про случаи, когда один и тот же аккаунт будут обновлять в одно время разные потоки, не совсем понимаю, когда это может произойти. если пользователь один, то он один и может менять его состояние и проблем быть не должно. если у нас в проекте несколько менеджеров, то они оба могут менять состояние счета и как потестил(попытался одновременно обратиться из нескольких потоков), то вроде  просто последний, кто нажал, того результат и запишется) спасибо, что обратил на это внимание, возможно я как то не так изобразил ситуацию, например с ачивками постоянно такая ошибка была, тут ниразу не получилось. в любом случае, опыт размышления над этим очень ценен, может Маша скажет, что я неправ и тут может такая ситуация произойти, но у меня не получилось ее имитировать. возможно, если сделать какой то scheduler, который будет закрывать какие то неактивные счета и в этот момент кто то что то задумал там поменять и как тогда будет вести себя программа я тоже не уверен

2024-11-01 16:45 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
я на самом деле думал про случаи, когда один и тот же аккаунт будут обновлять в одно время разные потоки, не совсем понимаю, когда это может произойти. если пользователь один, то он один и может менять его состояние и проблем быть не должно. если у нас в проекте несколько менеджеров, то они оба могут менять состояние счета и как потестил(попытался одновременно обратиться из нескольких потоков), то вроде  просто последний, кто нажал, того результат и запишется) спасибо, что обратил на это внимание, возможно я как то не так изобразил ситуацию, например с ачивками постоянно такая ошибка была, тут ниразу не получилось. в любом случае, опыт размышления над этим очень ценен, может Маша скажет, что я неправ и тут может такая ситуация произойти, но у меня не получилось ее имитировать. возможно, если сделать какой то scheduler, который будет закрывать какие то неактивные счета и в этот момент кто то что то задумал там поменять и как тогда будет вести себя программа я тоже не уверен

2024-11-01 16:49 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
не могу ответить на твой коммент про получение всех аккаунтов по id в том топике, надеюсь увидишь. мне кажется засовывать ownerId в фильтр не совсем хорошая идея, так мы развязываем руки клиентам, позволяя им опускать этот параметр, хотя он вроде как является обязательным, сейчас без него запрос не отправится. думаю так пока оставлю, мб Маша знает как обойти это ограничение, я не нашел...

2024-11-01 16:52 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +            IllegalAccountTypeForOwner.class,NotUniqueAccountNumberException.class})
могу в любой момент в пп поделиться опытом как я понимаю эту штуку, она на самом деле не такая сложная и мне кажется очень крутая

2024-11-01 16:52 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java
> +            IllegalAccountTypeForOwner.class,NotUniqueAccountNumberException.class})
могу в любой момент в пп поделиться опытом как я понимаю эту штуку, она на самом деле не такая сложная и мне кажется очень крутая

2024-11-01 16:56 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +        Specification<Account> ownerIdSpec =
мне кажется засовывать ownerId в фильтр не совсем хорошая идея, так мы развязываем руки клиентам, позволяя им опускать этот параметр, хотя он вроде как является обязательным, сейчас без него запрос не отправится. думаю так пока оставлю, мб Маша знает как обойти это ограничение, я не нашел...

2024-11-01 20:07 UTC, mysosnovskaya requested changes
С фильтрами и спецификациями классно получилось, молодец 👍 А ещё я жду интеграционный тест)
И отвечу на твой вопрос про глаголы в REST: их всё равно иногда используют, т.к. rest не идеален и с ним не получается описывать все возможные ситуации. Поэтому такого рода необычные эндпоинты можно писать через глаголы. Главное не делать этого для create/update/delete (для которых уже есть подходящие http методы). Но ты тоже хорошо (и в стиле rest) реализовал - через update. Так тоже делают. Как выбирать между подходами:
1. Если тела запросов одинаковые для всех операций (close/open/block), тогда проще один update реализовать с нужным типом операции (у тебя это статус). Иначе лучше разные эндпоинты делать
2. И ещё можно обсудить с фронтенд-разработчиком, будет ли ему удобен один эндпоинт или лучше разные.

2024-11-01 20:07 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
1. У нас в Account уже есть version, так что оптимистичная блокировка уже имеется)
2. Ситуация произойти может, ты ведь даже сам пишешь про двух менеджеров) Скорее всего у тебя просто не получилось поймать такое состояние? А как ты тестировал, расскажи?

2024-11-01 22:13 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public Page<AccountDto> getAllAccounts(AccountFilterDto filterDto, Long accountOwnerId, int page, int size) {
да, но не думаю, что это критично, чтобы переделывать, в следующий раз так поступлю

2024-11-01 22:19 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +            account.setClosedAt(null);
тут опять довольно абстрактно, без каких-то требований, я сделал, что из любого статуса в любой можно обновить(вот Арстан написал, что закрытый счет обычно не трогают), и т.к метод универсальный, то сюда может попасть любой статус: ACTIVE, FROZEN, CLOSED. если мы счет закрыли, то у него проставляется closed_at. но если мы его возвращаем в ACTIVE или FROZEN, я подумал, что наверное это поле нужно обратно делать null. и вот тут я посчитал, что в целом не сильно критично, что мы постоянно это поле null делаем. возможно, это неправильно(лишнее действие), и надо эту проверку расписать (типа если у нас счет закрыт и передается другой статус, то только тогда null ставим), или вообще пересмотреть это требование, что после закрытия счета его статус нельзя менять

2024-11-01 22:22 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto createAccount(CreateAccountDto accountDto) {
я наоборот всегда стараюсь их располагать в порядке, в котором обычно про них расказывают) типа GET POST PUT DELETE. я такой логикой руководствуюсь, можешь рассказать почему обычно поступают так, как ты пишешь?

2024-11-01 22:24 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
да, я согласен, что у меня не получилось поймать такую ситуацию. я пытался воспроизвести ее, как это получилось у меня, когда я тестировал ачивки: просто попросил несколько потоков обновить статус одного счёта, прогнал раз 10, не поймал такой ситуации. возможно потому что эта операция выполняется достаточно быстро, чтобы потоки успели поймать блокировку.

2024-11-01 22:34 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +        Specification<Account> ownerIdSpec =
работает, спасибо, переделал под твой вариант!

2024-11-01 22:54 UTC, soulasphyxia commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountsWithFilters() throws Exception {
написал интеграционные тесты, вроде все работает, но нарисовалась проблема: когда запускаю именно этот тест индивидуально, то все тест работает корректно, но когда тестирую весь класс, то только этот тест падает (должно найти 2 элемента, нашлось 0)...

2024-11-01 22:56 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/validation/AccountOwnerValidator.java
> +                //todo: здесь нужна интеграция с user_service, чтобы удостовериться, что пользователь участник проекта и узнать его роли
да, почему то был уверен, что в юзере есть инфа по его проектам и нам будет достаточно одной интеграции, а она только в project_service

2024-11-01 22:57 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/validation/AccountOwnerValidator.java
> +        //todo: здесь нужна интеграция с user_service, чтобы удостовериться, что пользователь есть в системе
да, я написал, потому что функционал вроде как необходимый для корректной работы метода, но не входит в данную задачу. на планинге постараюсь напомнить, может я возьмусь это делать

2024-11-01 22:59 UTC, soulasphyxia commented on src/test/resources/db/account/test_accounts.sql
> +    id         bigserial PRIMARY KEY,
не стал тут тоже создавать доп sequence и индексы, вроде как конфликтов из-за того, что в ентити стоит стратегия генерации SEQUENCE нету

2024-11-02 18:20 UTC, mysosnovskaya requested changes

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/filter/SpecsUtils.java
> +     * @return комбинированная спецификация, включающая в себя все переданные фильтры
подпиши, что через условие and

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/filter/SpecsUtils.java
> +     * @param <T> класс дто с параметрами фильтрации ex. AccountFilterDto
Было бы круто создать абстрактный класс или интерфейс FilterDto, от которого наследовать все фильтры. Тогда здесь было бы T extends FilterDto. Аналогично для Entity. Тогда уже на уровне компиляции проверялось бы, что метод используется корректно

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/filter/SpecsUtils.java
> +    public static <T,E> Specification<E> combineSpecsWithAndFromFilters(List<Filter<T,E>> filters, T filterDto) {
Я бы ещё condition добавила: combineSpecsWithAndConditionFromFilters

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/validation/AccountOwnerValidator.java
> +        //todo: здесь нужна интеграция с user_service, чтобы удостовериться, что пользователь есть в системе
Хорошо) Можешь завести задачу, пожалуйста? Ну или вместе на планировании заведем, только напомни обязательно)

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
Добавить в этот метод Thread.sleep(1000) после getAccountById, но до save и тогда должен поймать. Получится, что несколько потоков прочитают данные из базы, потом все потоки поспят, и кто-то успеет сохранить обновленные данные, а другим исключение выпадет)

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +            account.setClosedAt(null);
Поняла логику. Пусть тогда так остается. В текущей ситуации наиболее обоснованное решение)

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto createAccount(CreateAccountDto accountDto) {
По логике работы с объектом: ты его сначала создаешь/обновляешь, потом работаешь с ним (получаешь) и в конце удаляешь

2024-11-02 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/dto/filter/AccountFilterDto.java
> +        @NotNull
Хорошо, что так получилось) А то другие решения были бы костыльными, а так очень всё красиво и удобно)

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/AccountServiceApplicationTests.java
> +import org.springframework.boot.test.context.SpringBootTest;
Это зачем?) Тогда и аннотацию надо добавлять)

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +@AutoConfigureMockMvc
Эти аннотации уже есть в BaseContextTest, их не нужно дублировать

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountOk() throws Exception {
testGetAccountByOwner? Это же владелец получает?

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +                .andExpect(jsonPath("$.id").value(1));
Я бы побольше проверок добавила) Обычно вообще все поля тестируются. Это как гарантия того, что в json возвращаются все поля, которые мы ожидаем. Можно вернуть json через .andReturn().getResponse().getContentAsString() и через objectMapper превратить его в объект, а дальше уже как с объектом работать

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +                .andExpect(status().isForbidden());
А в теле ответа что? Есть какое-то описание?

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountsBadRequest() throws Exception {
В название теста всегда лучше добавить причину. testGetAccountsWithoutOwnerIdParam

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountsWithFilters() throws Exception {
Посмотри, в каком порядке тесты запускаются. Может быть предыдущие как-то изменяют базу? Тут явно другие тесты влияют на этот, а должно быть всё изолированно. Можно добавить костыльное решение - через аннотацию Order вызвать этот тест самым первым, но мне такой подход не нравится. Лучше написать тесты так, чтобы они были независимы. 
Можешь заинжектить сюда accountRepository и в самом начале теста вызвать accountRepository.findAll(), чтобы посмотреть, какие данные сейчас есть в таблице. Это должно помочь найти проблему)

2024-11-02 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +public class AccountControllerIT extends BaseContextTest {
Молодец, что написал интеграционные тесты 👍 Они как правило намного сложнее юнит тестов, поэтому их писать не так просто) Не забудь об этом навыке в резюме упомянуть!)

2024-11-03 09:56 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/filter/Filter.java
> +public interface Filter<T, E> {
да, я перепутал куда его добавлять)

2024-11-03 10:08 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/filter/SpecsUtils.java
> +     * @param <T> класс дто с параметрами фильтрации ex. AccountFilterDto
крутая идея, обязательно сделаю!

2024-11-03 10:56 UTC, soulasphyxia commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountsWithFilters() throws Exception {
да, тест на обновление счета запускался раньше, чем на получение всех счетов, соответственно они меняли состояние и выдавался правильный(с точки зрения работы программы), но не ожидаемый результат. решил проблему, добавив отдельно владельца и счёт для обновления

2024-11-03 11:05 UTC, soulasphyxia commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +                .andExpect(status().isForbidden());
да, добавил проверку на тело сообщения

2024-11-03 20:30 UTC, mysosnovskaya reviewed
Не на все вчерашние комментарии получила ответ, поэтому возвращаю на доработку. Новых комментариев не добавляла)

2024-11-03 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
Получилось протестировать и поймать ошибку? Я предлагала через Thread.sleep сделать

2024-11-03 20:30 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/AccountServiceApplicationTests.java
> +import org.springframework.boot.test.context.SpringBootTest;
Тут не вижу исправления. Нужно либо импорт удалить, либо аннотацию над классом повесить

2024-11-03 20:30 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +@AutoConfigureMockMvc
Тут тоже не увидела исправления или ответа. Вчера писала, что эти аннотации уже есть в BaseContextTest и дублировать их здесь не нужно

2024-11-03 20:30 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountOk() throws Exception {
Вчера предлагала переименовать в testGetAccountByOwner, если это верно)

2024-11-03 20:30 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +        AccountDto accountDto = objectMapper.readValue(result, AccountDto.class);
Вот это хорошо 👍

2024-11-03 20:30 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +                .andExpect(jsonPath("$.message").value("User 2 has no appropriate privileges"));
Отлично 👍

2024-11-03 20:30 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountsWithFilters() throws Exception {
Хорошо, что костылить через Order не стал. У тебя хорошее решение проблемы получилось)

2024-11-04 08:00 UTC, soulasphyxia commented on src/test/java/faang/school/accountservice/AccountServiceApplicationTests.java
> +import org.springframework.boot.test.context.SpringBootTest;
я пролистывал по 2 раза все комментарии к ПР, не вижу их :(

2024-11-04 08:06 UTC, soulasphyxia commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +@AutoConfigureMockMvc
круто, не знал, что так работает, убрал!

2024-11-04 08:09 UTC, soulasphyxia commented on src/test/java/faang/school/accountservice/controller/AccountControllerIT.java
> +    public void testGetAccountOk() throws Exception {
да, хорошее название, исправил

2024-11-04 08:13 UTC, soulasphyxia commented on src/main/java/faang/school/accountservice/service/account/AccountServiceImpl.java
> +    public AccountDto updateAccount(Long accountId, UpdateAccountDto updateAccountDto) {
да, в таком случае получается поймать это исключение, спасибо!

2024-11-04 18:16 UTC, mysosnovskaya approved these changes

2024-11-04 18:16 UTC, merged