BJS2-27151 Управление уникальными номерами счетов
CorporationX/account_service pull request #247
Opened 2024-10-26 17:12 UTC by vestmen

2024-10-26 20:07 UTC, sultan-inked commented on src/test/java/faang/school/accountservice/mapper/FreeAccountNumberMapperTest.java
> +
строчка

2024-10-26 20:07 UTC, sultan-inked commented on src/test/java/faang/school/accountservice/integration/FreeAccountNumberServiceIntegrationTest.java
> +
строчка

2024-10-26 20:07 UTC, vestmen commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +    @Retryable(retryFor = PersistenceException.class,
Этот метод потом будет использоваться для создания в "кэше" определённого количества свободных счетов. В следующей таске я буду делать Джону, которая в нескольких потоках создаёт новые счета

2024-10-26 20:08 UTC, vestmen commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +    private int typeCodeLength;//4
Да, спасибо)

2024-10-27 07:38 UTC, evgenywork commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +            RETURNING account_type, current_number, version
а ты проверял , что версия увеличивается спрингом с нативными запросами?

2024-10-30 13:27 UTC, vestmen commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +            RETURNING account_type, current_number, version
я переделал, посмотрел видео, там если через запрос делаем, то на уровне БД и так будет блокировка. А если бы я в коде получал и обновлял на новое значение, то тогда нужно было бы использовать version.

2024-11-01 20:58 UTC, 20cognosce requested changes
Объясни как пользоваться твоим решением, каким образом ты используешь базу, если ты её не используешь

2024-11-01 20:58 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/account_V004__create_free_accounts_numbers_and_account_numbers_sequence.sql
> +       ('5200');
Ключевые слова пиши заглавными, форматируй столбцы

2024-11-01 20:58 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/mapper/FreeAccountNumberMapperTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Ай ай ай

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java
> +            """, nativeQuery = true)
Давай не будем соревноваться в написании самого навороченного sql запроса, а ты разобьешь этот запрос на 2 отдельных и выполнишь их в одной транзакции

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java
> +            """, nativeQuery = true)
Твой метод называется getFreeAccountNumber, ты тут что-то хитро удаляешь, это совсем непрозрачно, что тут происходит, сделать понятно

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java
> +            """, nativeQuery = true)
Ты заполнил таблицу free_account_numbers свободными номера, удаляешь номер из одной таблицы и возвращаешь, окей

Но всё равно это два sql запроса:
1. залочить строку с номером
2. (1) вытащить номер
3. (2) удалить строку
4. снять лок

2024-11-01 20:58 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/account_V004__create_free_accounts_numbers_and_account_numbers_sequence.sql
> +);
А может тебе тут необходим составной первичный ключ?

Если есть номер 10
То он же свободен и для кредита № 10 и для вклада № 10, нет?

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/FreeAccountNumber.java
> +    private String accountType;
Почему не енам, у тебя же есть енам?

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/enums/account/AccountType.java
>  public enum AccountType {
?

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +                .orElseGet(() -> generateAccountNumbers(accountType, 1, false).get(0).getAccountNumber());
Отрефакторить эту строчку

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +                .incrementCounter(accountType.getCode(), batchSize);
в чем смысл batchSize, если он у тебя всегда = 1

2024-11-01 20:58 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +        log.info("Generated free account numbers: {}", freeAccountNumbers.size());
Отрефакторить весь этот метод

Я вообще не понял задумки, есть таблица со свободными номерами
Но ты никогда туда ничего не сохраняешь, и ничего оттуда не удаляешь, ты просто генерируешь toFreeAccountNumber и сразу отдаешь

???

2024-11-07 12:46 UTC, vestmen commented on src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java
> +            """, nativeQuery = true)
в условии написано можно или как ты описал или использовать DELETE RETURNING

2024-11-07 12:48 UTC, vestmen commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +                .orElseGet(() -> generateAccountNumbers(accountType, 1, false).get(0).getAccountNumber());
добавил отдельный метод для генерации единственного номера для того, чтобы если при запросе свободного номера из AccountService если ранее сгенерированного не окажется, то создастся один новый

2024-11-07 12:51 UTC, vestmen commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +        log.info("Generated free account numbers: {}", freeAccountNumbers.size());
сделал, разнес в 2 разных метода, для генерации определенного количества с сохранением, который будет использоваться в джобе потом, и с генерацией единственного, который мы просто отдаем если на момент запроса из акаунт сервиса у нас его не окажется - без сохранения, но с увеличением счетчика последовательности в репозитории AccountNumberSequence

2024-11-07 13:01 UTC, vestmen commented on src/main/resources/db/changelog/changeset/account_V004__create_free_accounts_numbers_and_account_numbers_sequence.sql
> +);
account_number в себя включает первые цифры, которые соответствуют каждому типу, и 2 номера не могут быть одинаковыми

2024-11-07 13:01 UTC, vestmen commented on src/main/resources/db/changelog/changeset/account_V004__create_free_accounts_numbers_and_account_numbers_sequence.sql
> +       ('5200');
ОК

2024-11-07 13:22 UTC, vestmen commented on src/main/java/faang/school/accountservice/enums/account/AccountType.java
>  public enum AccountType {
Каждый тип счета содержит в себе уникальный номер(который используется в начале каждого счета)

2024-11-07 13:24 UTC, vestmen commented on src/main/java/faang/school/accountservice/model/FreeAccountNumber.java
> +    private String accountType;
чтобы проще создавать с помощью последовательности новые номера счетов я в базе храню код каждого типа счета, они тоже уникальны для каждого типа

2024-11-08 18:06 UTC, 20cognosce approved these changes

2024-11-08 18:06 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java
> +                .getFreeAccountNumber(accountType.name())
лучше написать не get, а take например, потому что ты фактически удаляешь, а не селектишь

2024-11-08 18:06 UTC, merged