feature-BJS2-26201 / Работа с балансами /AccountService
CorporationX/account_service pull request #260
Opened 2024-10-28 14:16 UTC by Varrankin

2024-10-28 14:40 UTC, Silencemess1ah reviewed
Пробегись по классам alt+ctl+L, отступы и по мелочи

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/dto/Balance/ReturnedBalanceDto.java
> +    private long id;
id - шник не будет никогда зироу

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/dto/Balance/ReturnedBalanceDto.java
> +    private long accountId;
тоже только позитив

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/dto/Balance/ReturnedBalanceDto.java
> +    private int version;
Не уверен что в Dto нужно это

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        balance = balanceRepository.save(balance);
А есть в этом смысл? передаешь и перезаписываешь в один и тот же объект

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        );
В идеале в Account Service вынести

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/mapper/BalanceMapper.java
> +
Лишний отступ

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +
Лишний отступ

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/controller/BalanceController.java
> +    }
Не принципиально но что-то Put что то Post, на подумать

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/dto/Balance/BalanceDtoWhenUpdate.java
> +
Лишний отступ

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/entity/balance/Balance.java
> +    //@Temporal(TemporalType.TIMESTAMP) есть ли смысл добавлять данную строку? как я понимаю JPA и так сохранит в TIMESTAMP тип LocalDateTime.
Думаю описывать стоит с двух сторон, я бы сделал так, но не уверен

2024-10-28 14:40 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +    public ReturnedBalanceDto create(long accountId, BalanceDtoWhenCreate balanceDtoWhenCreate) {
@Transactional аннотации над методами

2024-10-28 17:30 UTC, GusevVrn reviewed
Я не совсем понял к чему dto when update и when create.

Вообще логику создания наверное засунуть в создание аккаунта, а не через контроллер, у тебя при создании аккаунта просто создается некий счет и все.

2024-10-28 17:30 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/dto/Balance/ReturnedBalanceDto.java
> +    @PositiveOrZero
а я не уверен что в returned надо вообще все эти аннотации указывать, ты ее через маппер только используешь и проверок как таковых нету

2024-10-28 17:30 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/balance/Balance.java
> +    //@Temporal(TemporalType.TIMESTAMP) есть ли смысл добавлять данную строку? как я понимаю JPA и так сохранит в TIMESTAMP тип LocalDateTime.
скорей всего timestamp по дефолту стоит в хибере поэтому все нормально сохраняет

2024-10-28 17:30 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/balance/Balance.java
> +    private long actualBalance;
копейки теряешь

2024-10-29 06:02 UTC, Varrankin commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        balance = balanceRepository.save(balance);
сначала собрал объект баланса, сохранил его в бд и перезаписал переменную объектом который пришел из БД, а что конкретно не так?

2024-10-29 06:11 UTC, Varrankin commented on src/main/java/faang/school/accountservice/dto/Balance/ReturnedBalanceDto.java
> +    @PositiveOrZero
думаю ты прав, это излишне, я навесил все что можно было, чтобы посмотреть что вы скажете, просто с одной стороны это излишне, с другой может показать нам ошибки логики которые мы по какой-то причине пропустили, хотя от всего не защитишься, так что удалю эти аннотации. @mysosnovskaya ты что думаешь?

2024-10-29 06:16 UTC, Varrankin commented on src/main/java/faang/school/accountservice/entity/balance/Balance.java
> +    private long actualBalance;
точно

2024-10-30 20:35 UTC, mysosnovskaya requested changes

2024-10-30 20:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/dto/balance/BalanceDtoWhenUpdate.java
> +public class BalanceDtoWhenUpdate {
UpdateBalanceRequest

2024-10-30 20:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/dto/balance/ReturnedBalanceDto.java
> +public class ReturnedBalanceDto {
Можно просто BalanceDto

2024-10-30 20:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        log.debug("balance has been created");
Можно айди аккаунта подписать)

2024-10-30 20:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    public void create(Account account) {
Это ты классно придумал, что баланс создается сразу с аккаунтом)

2024-10-30 20:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        Balance balance = balanceMapper.toBalance(balanceDtoWhenUpdate);
В реквесте должна приходить информация об изменении баланса (увеличился/уменьшился и какой тип), а то так как-то совсем ненадежно - кто угодно сможет переписать значения баланса на любые. Мы должны как минимум проверять, что не станет меньше 0

2024-10-30 20:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        log.debug("balance has been updated, balance: {}", balance);
Не вижу, а где сохранение баланса в базу?

2024-10-30 20:35 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/dto/Balance/ReturnedBalanceDto.java
> +    @PositiveOrZero
Согласна, эти аннотации не нужны)

2024-10-31 09:58 UTC, Varrankin commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    public void create(Account account) {
спасибо Паше за идею

2024-10-31 10:22 UTC, Varrankin commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        Balance balance = balanceMapper.toBalance(balanceDtoWhenUpdate);
согласен, но тут надо разобраться в архитектуре, пока не знаю как именно должно все работать, думаю, что должен быть какой то сервис по работе с финансовыми операциями и он должен вызывать метод update внутри сервиса AccoutService, и он должен провалидировать и произвести все необходимые операции с балансом и передать данные в balanct service,  т.е надо вообще удалить controller, думаю вообще опасно делать api для такой операции она должна быть изолирована, а balanct service просто сохраняет данные в БД и все, проверка на минус, тоже от логики зависит, может ли быть у нас отрицательный баланс? если нет то да надо проверку. Или если мы считаем что операции с балансом должны проиходить на стороне  balanct service, тогда нам надо передавать в метод фин. операции и производить расчеты в balanct service. Ты как считаешь как сделать?

2024-11-02 12:19 UTC, Varrankin commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        Balance balance = balanceMapper.toBalance(balanceDtoWhenUpdate);
я понял где был пробел, все дело было в задаче: Оплата через DMS. Там происходят все операции, balance service просто предоставляет методы для получения, создания и обновления баланса. Плюсом зашил проверки что баланс не может быть отрицательным в в класс сущность и сущность в БД

2024-11-02 18:31 UTC, mysosnovskaya reviewed
У тебя в условии задачи есть

> Написать контроллер с методом для получения баланса счёта и сервис с методами create и update. Учесть изменение версии баланса при каждой новой операции с ним

А ты это удалил) Надо бы нам с тобой с этим разобраться

2024-11-06 11:55 UTC, Varrankin commented
@mysosnovskaya Маша, привет) написал основную логику, пока не тестировал и тесты не писал, хочу сначала убедиться что в логике все ок, после напишу тесты и наведу красоту

2024-11-06 18:52 UTC, mysosnovskaya requested changes
С логикой всё ок, жду тестов)

2024-11-06 18:52 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/dto/balance/TransactionDto.java
> +    long account;
А модификаторы доступа?)

2024-11-06 18:52 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/dto/balance/TransactionDto.java
> +    long account;
Это accountId? Он же приходит в контроллер как PathVariable, зачем здесь дублировать?)

2024-11-06 18:52 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        if (account.getCurrency() != dto.getCurrency()) {
Это ты хорошо подумал. Я уже почти собралась писать комментарий в духе "а может из dto вообще удалить поле currency", но потом поняла =)

2024-11-06 18:52 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    private String getMethodName() {
Идею поняла, но этому методу не место в сервисе. Сервис про бизнес логику, а этот метод относится к красоте логирования. Да и я не очень понимаю, в чем здесь упрощение: ведь и в логах несложно написать, внутри какого метода это происходит. Можешь аргументировать - зачем это?)

2024-11-06 18:52 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/balance/TransactionService.java
> +            throw new IllegalArgumentException("Invalid transaction type");
В логах нужно написать - какой тип оказался неверным

2024-11-06 18:52 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/balance/TransactionService.java
> +    private final Map<TransactionType, TransactionHandler> handlers;
Круто! Молодец, что применил здесь такой подход, красиво!) В целом очень хорошее решение выбрано

2024-11-07 09:38 UTC, Varrankin commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    private String getMethodName() {
да не зачем, я просто решил попробовать, хотел удалить, но забыл

2024-11-12 19:08 UTC, mysosnovskaya reviewed
С моей стороны всё ок, но в github actions не все тесты прошли, поэтому смержить не могу. Нужна зелененькая сборка)

2024-12-09 12:55 UTC, mysosnovskaya approved these changes

2024-12-09 12:55 UTC, merged