create Managing Unique Account Numbers
CorporationX/account_service pull request #262
Opened 2024-10-28 18:56 UTC by DankeVilletti

https://faang-school.atlassian.net/jira/software/c/projects/BJS2/boards/59?assignee=712020%3A0cb7097a-312b-4b8a-a593-447732e8a1ea&selectedIssue=BJS2-26954

БЕЗ ТЕСТОВ )

2024-10-30 08:00 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/model/number/FreeAccountNumber.java
> +    public FreeAccountNumber(AccountNumberType type, String accountNumber) {
Не совсем понимаю, зачем тебе этот конструктор, если у тебя есть билдер

2024-10-30 08:05 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +    long incrementToValueAndGet(@Param("type") String type, @Param("increment") long increment);
Минутка душноты:
Инкремент это когда +1
Тут лучше по смыслу использовать 
updateAndFetchCounter
или
addToCounterAndGet

2024-10-30 08:15 UTC, Peregruzochka commented on src/main/java/faang/school/accountservice/model/number/FreeAccountNumber.java
> +    private Long id;
Мы тут решили, что UUID самый крутой в качестве Primary Key

2024-10-30 08:17 UTC, Peregruzochka commented on src/main/resources/application.yaml
> +    clear-checksums: true
не нада так, пожалуйста

2024-10-30 08:19 UTC, Peregruzochka commented on src/test/java/faang/school/accountservice/manager/AccountNumberManagerIntegrationTest.java
> +        if (!executorService.awaitTermination(10, TimeUnit.MINUTES)) {
мб все таки SECONDS?

2024-10-30 09:00 UTC, DankeVilletti commented on src/main/java/faang/school/accountservice/enums/AccountNumberType.java
> +public enum AccountNumberType {
Не думаю что это лишнее, всякие инвестиции для стартапа, если есть иерархия пользователей, то наверное какие-то ЗП и т.д.
если это отдельный сервис, то он не сильно связан с соц сетью, а значит можно использовать многое для бухгалтерии) 
я добавил, чтобы было если что, на будущее)

2024-10-30 09:00 UTC, DankeVilletti commented on src/main/java/faang/school/accountservice/model/number/FreeAccountNumber.java
> +    public FreeAccountNumber(AccountNumberType type, String accountNumber) {
Билдер уберу, он лишний

2024-10-30 09:05 UTC, DankeVilletti commented on src/main/java/faang/school/accountservice/model/number/FreeAccountNumber.java
> +    private Long id;
Primary Key - id сделал, просто чтобы не делать комбинированный ключ из type и number
По факту он бесполезен, так как таблица не статичная и постоянно удаляются данные
нет смысла тратить ресурсы на UUID, так как id вообще нигде не используется

2024-10-30 09:06 UTC, DankeVilletti commented on src/main/resources/application.yaml
> +    clear-checksums: true
пхехех, забыл убрать

2024-10-30 09:08 UTC, DankeVilletti commented on src/test/java/faang/school/accountservice/manager/AccountNumberManagerIntegrationTest.java
> +        if (!executorService.awaitTermination(10, TimeUnit.MINUTES)) {
при изменении параметров в yaml, время теста сильно меняется
даже этот тест не самый быстрый
больше 1000 записей вроде в двух таблицах (на каждый вид счета по 110)

2024-10-31 18:29 UTC, mrkorolev reviewed
👉👈

2024-11-01 21:37 UTC, 20cognosce requested changes

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/AccountServiceApplication.java
> +@Async
Именно, Async тут ни к чему

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/number/AccountUniqueNumberCounter.java
> +@Data
Посмотри, что дата под собой генерирует

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/model/number/FreeAccountNumber.java
> +    private Long id;
Я за составной ключ @EmbeddableId погугли

2024-11-01 21:37 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/V005__account-number.sql
> +        )
Так, зачем это делать на стороне базы

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +    long upCounterAndGet(@Param("type") String type, @Param("increment") long increment);
Реально, зачем ты аннотацию @Param тут используешь из феинга к тому же...

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +    long upCounterAndGet(@Param("type") String type, @Param("increment") long increment);
Насчет @Modifying - мы же все равно в транзакции будем это запускать, я надеюсь.

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/NumbersSequenceService.java
> +@AllArgsConstructor
Required

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/NumbersSequenceService.java
> +            accountNumbersSequenceRepository.upCounterAndGet(type.toString(), accountNumberConfig.getMaxNumberOfFreeAccounts() - 1);
Это выглядит жутко
Напиши попроще, декомпозируй

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/NumbersSequenceService.java
> +                return null;
???
Это бан

2024-11-01 21:37 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/manager/AccountNumberManagerIntegrationTest.java
> +public class AccountNumberManagerIntegrationTest extends BaseContextTest {
А че так мало тестов-то? Жиденько совсем

2024-11-01 21:37 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/manager/AccountNumberManagerIntegrationTest.java
> +    }
?)

2024-11-01 21:37 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/AccountNumbersManager.java
> +public class AccountNumbersManager {
Я правильно понял, что ты этот класс используешь только в тестах? Что он тогда в основном коде делает?

2024-11-02 05:28 UTC, DankeVilletti commented on src/main/java/faang/school/accountservice/service/account/numbers/AccountNumbersManager.java
> +public class AccountNumbersManager {
Этот менеджер как раз для предоставления уникальных счетов и обращения в коде, а сервис имеет default видимость, чтобы только менеджер мог взаимодействовать с ним, это решение связано с async методом и транзакциями в сервисе

2024-11-02 05:29 UTC, DankeVilletti commented on src/main/java/faang/school/accountservice/service/account/numbers/AccountNumbersManager.java
> +    public <T> T getAccountNumberAndApply(AccountNumberType type, Function<FreeAccountNumber, T> action) {
Счета не знаю где будут использоваться и как, было задание реализовать передачу лямбды, чтобы с этим счетом сразу что-то сделать

2024-11-02 05:34 UTC, DankeVilletti commented on src/main/java/faang/school/accountservice/service/account/numbers/NumbersSequenceService.java
> +                return null;
Почему, я же возвращаю Optional.empty
И менеджер при таком исходе выполняет другую процедуру получения счета и запускает асинхронную генерацию(если пул пустой)

2024-11-02 05:38 UTC, DankeVilletti commented on src/main/resources/db/changelog/changeset/V005__account-number.sql
> +        )
Не совсем понимаю что в этом плохого?

2024-11-05 20:02 UTC, 20cognosce requested changes
Короче в сервисе всё мутно очень, сделай прозрачный процесс работы программы и отрефактори этот сервис

2024-11-05 20:02 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/DigitSequenceService.java
> +            accountNumbersSequenceRepository.upCounterAndGet(type.toString(), accountNumberConfig.getMaxNumberOfFreeAccounts() - 1);
И это всё идет в одной транзакции где мы взяли лок на account_unique_number_counter, мне кажется это перебор и не оптимально

2024-11-05 20:02 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +            WHERE type = :type
Вот ты запустил асиинхронную генерацию, и залочил таблицу, и мы пришли в метод generateNewAccountNumberWithoutPool на котором встали в этом запросе пока идет генерация

2024-11-05 20:02 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/DigitSequenceService.java
> +        if (!counter.getGeneration_state()) {
Что это за нейминг

2024-11-07 10:29 UTC, DankeVilletti commented on src/main/java/faang/school/accountservice/service/account/numbers/DigitSequenceService.java
> +    public void checkForGenerationSequencesAsync(AccountNumberType type) {
.findAndLockByTypeForUpdate блокирует строку для дальнейшей генерации для пула(асинхронно)
Все другие потоки просто пропустят генерацию, потому-что ею занимается уже кто-то
а вызов происходит всегда в ситуации когда пул пустой или не получилось достать номер(а сам номер будет вне пула создан)

2024-11-08 16:51 UTC, DankeVilletti commented
![image](https://github.com/user-attachments/assets/d03499ad-6ee8-482e-8831-6820470f004c)

транзакция блокировки заканчивается и потом начинается транзакция для генерации

2024-11-08 18:18 UTC, 20cognosce requested changes

2024-11-08 18:18 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +    @Query("SELECT a FROM AccountUniqueNumberCounter a WHERE a.type = :type")
Всё еще хочу видеть логи
@Query тебе не нужен

2024-11-08 18:18 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/sequence/DigitSequenceGenerator.java
> +        return freeAccountNumbersRepository.countFreeAccountNumberById_Type(type);
Что за нейминг

2024-11-08 18:18 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java
> +    Optional<AccountUniqueNumberCounter> findAccountUniqueNumberCounterByType(String type);
skip locked нужно
Ты это реально протестировал со всеми блокировками?

2024-11-08 18:18 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/numbers/sequence/DigitSequenceManager.java
> +        Optional<AccountUniqueNumberCounter> counterOpt = accountNumbersSequenceRepository.findAccountUniqueNumberCounterByType(type.toString());
Или у тебя тут скорее вылетит ошибка, что попытка обращения к залоченой строке

2024-11-08 18:18 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/service/DigitSequenceServiceTest.java
> +//        //verify(accountNumbersSequenceRepository, never()).setActiveGenerationState(anyString());
Что это всё...

2024-11-08 18:44 UTC, 20cognosce commented
> ![image](https://private-user-images.githubusercontent.com/103098161/384454658-d03499ad-6ee8-482e-8831-6820470f004c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwOTE3NDYsIm5iZiI6MTczMTA5MTQ0NiwicGF0aCI6Ii8xMDMwOTgxNjEvMzg0NDU0NjU4LWQwMzQ5OWFkLTZlZTgtNDgyZS04ODMxLTY4MjA0NzBmMDA0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxODQ0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDg3N2E3MGI3MzI1YjQ3NTlmNTI2NTdiYWVmMmE5NDlkNTJkZTNhMzUwMTdkNWY1ZGNhNjRlMTlkOTk4NzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ErzGiS1ta2gs0iXSyuVAjFBxq9dVdjQOc_aexusvYAM)
> 
> транзакция блокировки заканчивается и потом начинается транзакция для генерации

Блокировок там не видно

2024-11-10 14:09 UTC, 20cognosce approved these changes
Очень намудрил ты конечно с реализацией, ладно, пойдем дальше

2024-11-10 14:10 UTC, merged