Оплата через DMS BJS2-27146
CorporationX/account_service pull request #264
Opened 2024-10-28 22:39 UTC by sultan-inked

2024-11-03 12:07 UTC, sultan-inked commented
Интеграционные тесты будут, пишу

2024-11-06 12:20 UTC, 20cognosce requested changes
Доделать функционал, местами отрефакторить

Подготовить демо вместе с Ильей

ТЩАТЕЛЬНО продебажить блокировки на базе

2024-11-06 12:51 UTC, sultan-inked commented on src/test/resources/db/changelog/changeset-test/test_users_project_country.sql
> +                         id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
Это для тестов, копипастил с других сервисов

2024-11-06 12:51 UTC, sultan-inked commented on src/test/resources/db/changelog/changeset-test/test_users_project_country.sql
> +                       id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
Только для тестов, скопировал из Юзер сервиса

2024-11-06 12:55 UTC, sultan-inked commented on build.gradle.kts
> +    testAnnotationProcessor("org.projectlombok:lombok:1.18.26")
Дублировал, в тестах не было, а то не работает

2024-11-07 08:34 UTC, sultan-inked commented on src/test/resources/db/changelog/changeset-test/V001__account-service_account.sql
> +    version        INT NOT NULL,
Потому что разные люди писали в разных ПР, это все для тестов копировал, боюсь менять чужую таблицу, вдруг что то сломается

2024-11-07 08:35 UTC, sultan-inked commented on src/test/resources/db/changelog/changeset-test/test_users_project_country.sql
> +                       email varchar(64) UNIQUE NOT NULL,
Это в юзер сервисе талицы, они изначально были)

2024-11-07 08:37 UTC, sultan-inked commented on src/test/resources/db/changelog/changeset-test/test_users_project_country.sql
> +    id                BIGSERIAL PRIMARY KEY,
Я не создавал эти таблицы, скопировал для тестов из прожект сервиса, потому что в таблице аккаунт стоит контстрейнт

2024-11-09 13:06 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        balanceValidator.checkFreeAmount(operation, sourceBalance, money);
Написал интергационный тест который воспроизваодит оптимстик лок, спринг автоматитчески следит за версией

2024-11-09 14:10 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/aspect/publisher/payment/AspectPaymentPublisher.java
> +}
Таким образом использовать пост констракт норм? Что не делать итерацию каждый раз

2024-11-09 14:19 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
>      }
Сделал так как ты просил, при авторизационном платеже снимается с основного и пополняется автроизационный баланс.
При клиринге снимается с авторизационного и пополяется целевой баланс.

2024-11-09 14:20 UTC, sultan-inked commented on src/main/resources/db/changelog/changeset/account_V002__balance.sql
> +    source_balance_id UUID NOT NULL,
Ты писал что надо юник прописывать, но в эту таблицу не получиться, иначе у одного баланса может быть только один платеж

2024-11-09 14:23 UTC, sultan-inked commented on src/test/java/faang/school/accountservice/integration/service/balance/BalanceServiceIntegrationTest.java
> +                }));
В цикле вторым потоком обновляю баланс что бы основной поток выпал с оптимистик локом

2024-11-10 13:49 UTC, 20cognosce approved these changes
Да это жёстко

2024-11-10 13:49 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/listener/kafka/listeners/payment/AuthPaymentKafkaListener.java
> +public class AuthPaymentKafkaListener {
То же что и в payment - в одном классе все лисенеры

2024-11-10 13:53 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/aspect/publisher/payment/AspectPaymentPublisher.java
> +    public void execute(PublishPayment publishPayment, Object returnedValue) {
Асинхронно вызывать аспекты, иначе они будут внутри транзакции

2024-11-10 13:53 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/aspect/publisher/payment/AspectPaymentPublisher.java
> +}
Пост констракт норм, но это же можно сделать в конструкторе

Но не очень одобряю мапить класс на интанс

2024-11-10 13:57 UTC, merged