BJS2-26202 FEAT: Управление уникальными номерами счетов
CorporationX/account_service pull request #265
Opened 2024-10-29 11:31 UTC by lowerKamaCase

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequence.java
> +    // getters and setters
?

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    @Transactional
а зачем здесь transactional

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    @Transactional
Здесь тоже зачем transactional

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    default AccountNumbersSequence createCounter(AccountEnum accountType) {
Я бы вынес это в сервис

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    default FreeAccountNumber createFreeAccountNumber(AccountEnum accountType, Long freeAccountNumber) {
Это тоже бы в сервис

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    @Query(value = "WITH deleted_row AS (DELETE FROM free_account_numbers WHERE id = (SELECT id FROM free_account_numbers WHERE account_type = :accountType ORDER BY id LIMIT 1) RETURNING free_account
Тяжело читать запрос в одну строчку.
Тут точно надо WITH deleted_row AS ?

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +    public FreeAccountNumbersService(FreeAccountNumbersRepository freeAccountNumbersRepository, AccountNumbersSequenceRepository accountNumbersSequenceRepository) {
Почему не RequiredArgConstructor?

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +@Service
Логов не хватает

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    int incrementCounterIfEquals(AccountEnum accountType, Long currentCounter);
кому equals

2024-10-30 06:49 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +    public void processAccountNumber(AccountEnum accountType, Consumer<Long> action) {
Этот метод бы разбить, тяжело читается
accountNumbersSequenceRepository - работу с этим репозиторием вообще вынести в отдельный сервис

2024-10-30 19:15 UTC, mysosnovskaya requested changes

2024-10-30 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    @Query("UPDATE AccountNumbersSequence ans SET ans.currentCounter = ans.currentCounter + 1 WHERE ans.accountType = :accountType AND ans.currentCounter = :currentCounter")
Последнее условие (про currentCounter здесь лишнее). В базе данных хранится актуальное значение счетчика, нам нужно увеличить его на 1 и вернуть (для этого используй оператор RETURNING в sql)

2024-10-30 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +                .orElseThrow(() -> new IllegalStateException("Counter not initialized"))
Такого не должно быть. Пусть в базе данных при создании таблицы сразу инициализируется

2024-10-30 19:31 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequence.java
> +    // getters and setters
убрал это

2024-10-30 19:32 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
точно) поправил

2024-10-30 19:34 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    @Transactional
убрал отсюда     @Transactional
и оставил его только в сервисе

2024-10-30 19:35 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    @Query("UPDATE AccountNumbersSequence ans SET ans.currentCounter = ans.currentCounter + 1 WHERE ans.accountType = :accountType AND ans.currentCounter = :currentCounter")
а как же оптимистик лок?

2024-10-30 19:35 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    int incrementCounterIfEquals(AccountEnum accountType, Long currentCounter);
метод переименован в incrementCounterForAccountType

2024-10-30 19:49 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    default AccountNumbersSequence createCounter(AccountEnum accountType) {
1. вынес в сервис. 
2. насколько я понимаю из пункта 5 задания, этот метод может вызываться еще и в процессе работы программы при некотрых  условиях. сейчас метод называется createFreeAccountNumber

2024-10-30 19:50 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    @Query(value = "WITH deleted_row AS (DELETE FROM free_account_numbers WHERE id = (SELECT id FROM free_account_numbers WHERE account_type = :accountType ORDER BY id LIMIT 1) RETURNING free_account
нет, поправил sql

2024-10-30 19:50 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    default FreeAccountNumber createFreeAccountNumber(AccountEnum accountType, Long freeAccountNumber) {
вынес в сервис

2024-10-30 19:54 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +                .orElseThrow(() -> new IllegalStateException("Counter not initialized"))
метод исправлен

2024-10-30 20:00 UTC, lowerKamaCase commented on src/main/resources/db/changelog/changeset/V003__account_service-account_numbers.sql
> +CREATE TYPE account_type AS ENUM ('DEBIT', 'SAVINGS');
поправил на 
account_type VARCHAR(20) NOT NULL

2024-10-30 20:13 UTC, lowerKamaCase commented on src/main/resources/db/changelog/changeset/V003__account_service-account_numbers.sql
> +    free_account_number BIGINT UNIQUE NOT NULL
нет, поправил на VARCHAR(20)

2024-10-30 20:27 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +@Service
добавил логи

2024-10-31 19:04 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    @Query("UPDATE AccountNumbersSequence ans SET ans.currentCounter = ans.currentCounter + 1 WHERE ans.accountType = :accountType AND ans.currentCounter = :currentCounter")
Короче этот метод не пашет, он не апдейтит как нужно, я подгрузил что ты закоммитил чтоб от чего отталкиваться было и он один раз заходит в базу делает один раз апдейт и дальше все не проходит инкремент

2024-10-31 20:38 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +    private FreeAccountNumber createFreeAccountNumber(AccountEnum accountType, String freeAccountNumber) {
Думаю, что этот метод должен быть публичным, т.к. нам нужна возможность генерировать свободные номера по расписанию, а не только в случае, когда предыдущий свободный удалился. И в целом можно добавить возможность генерировать сразу n таких номеров

2024-10-31 20:38 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +        boolean hasIncremented = accountNumbersSequenceRepository.incrementCounterForAccountType(accountType, sequence.getCurrentCounter());
Я думаю, что тут лучше за один запрос к базе инкрементировать счетчик и вернуть его. 
У тебя здесь не будет оптимистичной блокировки, т.к. равенство counter проверится во время выполнения этого метода (внутри транзакции), а когда транзакция завершится, то эта проверка уже происходить не будет. А нам как раз надо сделать проверку перед завершением. Тут лучше использовать version для AccountNumbersSequence, тогда спринг сам всё корректно сделает)

2024-10-31 20:38 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    @Query("UPDATE AccountNumbersSequence ans SET ans.currentCounter = ans.currentCounter + 1 WHERE ans.accountType = :accountType AND ans.currentCounter = :currentCounter")
> а как же оптимистик лок?

ответила в ревью)

2024-10-31 20:39 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/account/AccountNumbersSequenceRepository.java
> +    @Query("UPDATE AccountNumbersSequence ans SET ans.currentCounter = ans.currentCounter + 1 WHERE ans.accountType = :accountType AND ans.currentCounter = :currentCounter")
> Короче этот метод не пашет, он не апдейтит как нужно, я подгрузил что ты закоммитил чтоб от чего отталкиваться было и он один раз заходит в базу делает один раз апдейт и дальше все не проходит инкремент

а на что ругается?
@lowerKamaCase перед мерджем нужно обязательно убедиться, что код работает

2024-11-01 08:17 UTC, lowerKamaCase commented
> Можешь объяснить логику сервиса? Мне кажется сейчас у тебя неправильно реализовано. Как я понял, если ты сейчас ходишь в таблицу свободных номеров и там ничего нету ты создаешь новый сиквенс с нуля, но если у нас уже был сиквенс будет дубликат.

действительно, я неправильно понял задание.
поправил. 
сейчас реализовано через шедулер, как Влад Мишустин показал в одном из видео к 13ому уроку.

всем спасибо за комменты:)

2024-11-01 08:18 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +        boolean hasIncremented = accountNumbersSequenceRepository.incrementCounterForAccountType(accountType, sequence.getCurrentCounter());
сейчас реализовано через шедулер, как Влад Мишустин показал в одном из видео к 13ому уроку.

2024-11-01 08:18 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +    private FreeAccountNumber createFreeAccountNumber(AccountEnum accountType, String freeAccountNumber) {
сейчас реализовано через шедулер, как Влад Мишустин показал в одном из видео к 13ому уроку.

2024-11-01 08:45 UTC, Silencemess1ah commented
> > Можешь объяснить логику сервиса? Мне кажется сейчас у тебя неправильно реализовано. Как я понял, если ты сейчас ходишь в таблицу свободных номеров и там ничего нету ты создаешь новый сиквенс с нуля, но если у нас уже был сиквенс будет дубликат.
> 
> действительно, я неправильно понял задание. поправил. сейчас реализовано через шедулер, как Влад Мишустин показал в одном из видео к 13ому уроку.
> 
> всем спасибо за комменты:)

то есть вместо того чтобы поправить метод апдейта, ты решил новых сущностей добавить, перелопатить логику свободных номер, добавил зачем то шедулер из моего задания, я только все сделал под каркас, вообще все по другому теперь...

2024-11-01 08:47 UTC, Silencemess1ah commented
@mysosnovskaya короче жду мержа ибо без него это бессмысленно, я все сделал протестил все поменялось, будет мерж буду делать уже по готовому

2024-11-01 11:20 UTC, lowerKamaCase commented
> > > Можешь объяснить логику сервиса? Мне кажется сейчас у тебя неправильно реализовано. Как я понял, если ты сейчас ходишь в таблицу свободных номеров и там ничего нету ты создаешь новый сиквенс с нуля, но если у нас уже был сиквенс будет дубликат.
> > 
> > 
> > действительно, я неправильно понял задание. поправил. сейчас реализовано через шедулер, как Влад Мишустин показал в одном из видео к 13ому уроку.
> > всем спасибо за комменты:)
> 
> то есть вместо того чтобы поправить метод апдейта, ты решил новых сущностей добавить, перелопатить логику свободных номер, добавил зачем то шедулер из моего задания, я только все сделал под каркас, вообще все по другому теперь...

да, именно так

2024-11-01 18:51 UTC, mysosnovskaya reviewed
Вижу, что ты многое переделал как в видео разборе от Влада. Написала некоторые комментарии, связанные с условием задачи (шедулер лишний, его по условию не должно быть, а вот кое-какой логики не хватает). Давай это поправим и будем мержить)

2024-11-01 19:09 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/scheduler/account/AccountNumbersScheduler.java
> +public class AccountNumbersScheduler {
окей, шедулер выпиливаю

2024-11-01 19:29 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +        FreeAccountNumber freeAccountNumber = freeAccountNumbersRepository.findAndRemoveFreeAccountNumber(type.name());
поправил, добавил метод generateFreeAccountNumber и вызываю его в orElseGet

2024-11-01 19:29 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +    public void retrieveAccontNumber(AccountEnum type, Consumer<FreeAccountNumber> numberConsumer) {
поправил

2024-11-01 20:10 UTC, mysosnovskaya approved these changes

2024-11-02 00:15 UTC, merged