feature-BJS2-26204: Накопительные счета и тарифы
CorporationX/account_service pull request #273
Opened 2024-10-31 05:58 UTC by StepnovaVarvara

2024-10-31 06:35 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/controller/tariff/TariffController.java
> +    @PutMapping
обычно в put урле айдишник присутствует, потому что мы точно знаем, какую сущность обновляем

2024-10-31 06:37 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private Tariff tariff;
а точно тариф ван-ту-ван ? не может быть так, что разные аккаунты имеют один и тот же тариф?

2024-10-31 06:38 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private int version;
версию обычно для оптимистик лока добавляют.
можно ли без обойтись без версии и вместо нее использовать updatedAt ?

2024-10-31 06:40 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/entity/tariff/Tariff.java
> +    private String tariffType;
как будто енам должен быть, не?

2024-10-31 06:45 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +            log.info("Thread name: {} save Account id: {}", Thread.currentThread().getName(), savingsAccount.getId());
точно нужно имя треда в логе?

2024-10-31 06:49 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +                    Rate newRate = Rate.builder()
вот это можно в отдельный метод вынести, типа createRateByInterestRate

2024-10-31 06:51 UTC, lowerKamaCase commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +        Tariff existedTariff = tariffRepository.findByTariffType(tariffRequestDto.getTariffType())
почему existed, а не existing ? он ведь сейчас существует в БД. ну и дальше с existedRate то же самое

2024-10-31 09:33 UTC, segaTk reviewed
Супер))

2024-10-31 09:33 UTC, segaTk commented on src/main/java/faang/school/accountservice/config/executor/ExecutorServiceConfig.java
> +        return Executors.newFixedThreadPool(treadCount);
Может лучше через BlockingQueue, для более гибкой настройки и возможности дальнейшего переиспользования для других задач?

2024-10-31 09:36 UTC, Varrankin reviewed
Красотка! столько кода написала

2024-10-31 09:36 UTC, Varrankin commented on src/main/java/faang/school/accountservice/controller/account/SavingsAccountController.java
> +    public SavingsAccountDto openSavingsAccount(@RequestBody @Valid SavingsAccountCreatedDto savingsAccountCreatedDto) {
как я знаю если ты ставишь @Valid, над классом надо вешать аннотацию валидации иначе @Valid работать не будет

2024-10-31 09:36 UTC, Varrankin commented on src/main/java/faang/school/accountservice/dto/account/SavingsAccountDto.java
можно аннотации валидации навесить

2024-10-31 09:36 UTC, Varrankin commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private BigDecimal balance;
это же у тебя сущность, разве сопоставления через column не нужно?

2024-10-31 09:36 UTC, Varrankin commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private Account account;
не вижу чтоб ты определяла главную сущность через mappedBy, кроме owner

2024-10-31 09:36 UTC, Varrankin commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Scheduled(cron = "${scheduler.calculatePercents.cron}")
я сильно в логику не вникал, но тут @Retryable не нужен?

2024-10-31 09:36 UTC, Varrankin commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +        SavingsAccount savingsAccount = SavingsAccount.builder()
сущность думаю надо как минимум в отдельном методе собирать а лучше через маппер

2024-10-31 09:36 UTC, Varrankin commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +        log.info("start openSavingsAccount with dto - {}", savingsAccountCreatedDto.toString());
есть такая штука Аспектно-ориентированное программирование, в общем я сам еще не делал, но хочу попробовать, если интересно тоже можешь вот статья https://habr.com/ru/articles/428548/

2024-10-31 13:04 UTC, segaTk commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private BigDecimal balance;
оно и так смаппится по идее

2024-10-31 16:09 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/account/SavingsAccountController.java
> +@RequestMapping("/v1/savingsAccounts")
я бы не стала так делать, тк это общепринятый подход + а если будет эндпоинт, у которого не будет пути

2024-10-31 16:10 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/account/SavingsAccountController.java
> +    @GetMapping("/account/{ownerId}")
потому что мы тут с аккаунтом работаем и получаем в итоге аккаунт, а не пользователя

2024-10-31 16:17 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/account/SavingsAccountController.java
> +    public SavingsAccountDto openSavingsAccount(@RequestBody @Valid SavingsAccountCreatedDto savingsAccountCreatedDto) {
такс, про аннотацию @Valid над самим классом dto - не, ее там не нужно ставить, про аннотации над полями - я забыла их поставить. Щас добавила)

2024-10-31 16:18 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/tariff/TariffController.java
> +    @PutMapping
Думала об этом, но поскольку у меня dto содержит поле с названием, то я решила не ставить тут айди

2024-10-31 16:20 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/dto/account/SavingsAccountDto.java
тут наверное не имеет смысла, тк эта дтошка возвращается, а не приходит к нам из вне. В той дто, которая приходит из вне я валидацию добавила)

2024-10-31 16:26 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private Account account;
я это не делала, когда есть связь @OneToOne, тк это делать не обязательно

2024-10-31 16:31 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/entity/tariff/Tariff.java
> +    private String tariffType;
это обсуждали на дейлике - тут строка

2024-10-31 16:37 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Scheduled(cron = "${scheduler.calculatePercents.cron}")
как я понимаю -  @Retryable нужен чтобы повторять действия, которые определены в этом методе, в случае если в процессе его выполнения вылетели ошибки. По логике тут это важно, тк мы юзерам деньки начисляем. По идее надо добавить, но я ничего про это не знаю)) Мааааша, жду твой коммент!)

2024-10-31 16:45 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +        SavingsAccount savingsAccount = SavingsAccount.builder()
ну да, можно и вынести. будет почище метод выглядеть

2024-10-31 16:48 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +        log.info("start openSavingsAccount with dto - {}", savingsAccountCreatedDto.toString());
посмотрю, спасибочки))

2024-10-31 16:51 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +            log.info("Thread name: {} save Account id: {}", Thread.currentThread().getName(), savingsAccount.getId());
тут затрудняюсь ответить, я его тут поставила, чтобы проверить работу метода) Не могу ответить на этот вопрос, тк сама не знаю как правильно

2024-10-31 16:54 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +                    Rate newRate = Rate.builder()
гатова))

2024-10-31 17:24 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +        Tariff existedTariff = tariffRepository.findByTariffType(tariffRequestDto.getTariffType())
Да, ты прав, я затупила

2024-10-31 17:35 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private Tariff tariff;
Думаю, ты прав! Я на этом месте супер долго сидела, подустала от этой задачки видно)

2024-10-31 17:51 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/config/executor/ExecutorServiceConfig.java
> +        return Executors.newFixedThreadPool(treadCount);
Често говоря, я не знаю... Как я понимаю, BlockingQueue используется в сценарии "производитель-потребитель", те производитель генерирует задания, потребитель их забирает для работы, по мере их появления. У нас же вроде бы не такая ситуация... Мааааша, плиз, поясни)))

2024-10-31 20:59 UTC, mysosnovskaya reviewed
Варя, ответила на твои вопросы, но полное ревью сегодня сделать не смогу, уже голова не соображает :) Так что давай пока эти комментарии посмотри, а я в следующий раз полностью всё проверю

2024-10-31 20:59 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private Tariff tariff;
Тут разве не ManyToOne? Один тариф у многих аккаунтов. Значит тариф - один, значит к нему - one, а аккаунтов - много, к ним - many. Тогда просто аннотацию поменять, а здесь никакого списка не будет) 

Вообще вы про разное говорите, Сергей как раз про то, что нужно заменить на ManyToOne, а ты про то, что у аккаунта много тарифов (история) и как тут выбирать последний. Но с этим у тебя вроде проблем нет, как я вижу?)

2024-10-31 20:59 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/config/executor/ExecutorServiceConfig.java
> +        return Executors.newFixedThreadPool(treadCount);
@segaTk можешь пояснить, почему ты про BlockingQueue написал? 
Я пока тоже не поняла

2024-10-31 20:59 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Scheduled(cron = "${scheduler.calculatePercents.cron}")
Варя, ты всё верно написала. Тут главное понять, какие вообще исключения могут возникнуть и какие из них нужно ретраить. Например, если ты получаешь NullPointerException, то тут нет смысла повтор делать, он никуда не уйдет. А если OptimisticLockException, то да, определенно нужно повтор сделать, т.к. в следующий раз эта ошибка может не возникнуть. Вот нужно об этом подумать, какие у тебя есть варианты, что может пойти не так) И если найдется что-то такое, для чего можно повтор сделать, то стоит повесить аннотацию Retryable с указанием соответствующего исключения. Это нужно ещё подумать, поисследовать свой код)

2024-11-01 04:39 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Scheduled(cron = "${scheduler.calculatePercents.cron}")
Ну вот я пока до такого додумалась)

2024-11-01 04:56 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/entity/account/SavingsAccount.java
> +    private Tariff tariff;
Я тут прям жестко тупить начала! Понимаю, что ВанТуВан не подходит, но и ВанТуМени не ложится. А про ManyToOne я просто забыла или я даже не знаю... По истории - я сделала историю для тарифов и ставок в формате JSON, но при этом для них же сделала ентити. Те тариф и ставка это полноценные ентити. Думаю, что памяти много на себя не возьмет, но нам так будет удобнее. На мой взгляд нерацианально для получения значения процентной ставки каждый раз парсить JSON и вытаскивать оттуда последнее значение

2024-11-01 13:29 UTC, segaTk commented on src/main/java/faang/school/accountservice/config/executor/ExecutorServiceConfig.java
> +        return Executors.newFixedThreadPool(treadCount);
Гибкая настройка пула потоков, где если очередь заполнена (достигла своего максимального размера), поток, пытающийся добавить элемент, будет заблокирован до тех пор, пока не освободится место. Потоки могут безопасно добавлять и удалять задачи из очереди, избегая гонок данных и ненужных задержек. 
Случаи применения: 
 **Пулы потоков**
Одно из самых распространённых применений — реализация пула потоков (ThreadPoolExecutor), где BlockingQueue<Runnable> служит хранилищем задач. В пуле потоков:
Основной поток добавляет задачи в очередь.
Потоки из пула извлекают задачи из очереди и выполняют их.
**Производитель-потребитель**
В паттерне «Производитель-потребитель» BlockingQueue<Runnable> можно использовать для передачи задач от потока производителя (который создает задачи) к потоку потребителя (который исполняет их). Этот подход позволяет:
Синхронизировать работу потоков. Поток-потребитель будет ожидать, пока появится задача, не занимая ресурсы.
Избежать потерь данных. Задачи сохраняются в очереди, если потребитель занят выполнением других задач.
**Недостатки**
Может вызвать блокировки. Если очередь заполнена или пуста, потоки блокируются, что может привести к снижению производительности в критически загруженных системах.
Не подходит для real-time задач. Время выполнения задач может быть непредсказуемым, особенно если задачи накапливаются в очереди.

BlockingQueue<Runnable> является мощным инструментом для управления задачами в многопоточных системах. Он применяется в пуле потоков, паттернах «Производитель-потребитель» и в случаях, где требуется ограничение нагрузки на систему. Выбор реализации BlockingQueue (таких как ArrayBlockingQueue, LinkedBlockingQueue, или SynchronousQueue) и настройка её размера играют ключевую роль в эффективности работы многопоточной системы. 
Это всё к тому, что если мы захотим переиспользовать ExecutorService для других задач, будем иметь гибкую настройку, а так не настаиваю оставить такой вариант.

2024-11-01 19:23 UTC, mysosnovskaya requested changes
Вот сегодня я внимательно поревьювила, оставила комментарии) И ещё жду интеграционный тест)

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/config/executor/ExecutorServiceConfig.java
> +        return Executors.newFixedThreadPool(treadCount);
А, теперь поняла, про что ты. 
Мы не думаем о будущем, т.к. не знаем, что там будет. В текущей задаче как будто бы необходимости в этой очереди нет и мы сейчас не знаем, понадобится ли нам она когда-то. Поэтому предлагаю оставить как есть, а если вдруг когда-то будет задача, где лучше будет применить очередь, то сделать такую доработку - не проблема)

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/controller/account/SavingsAccountController.java
> +    @GetMapping("/account/{ownerId}")
/savingsAccounts/account -это странно =) Думаю, тут лучше подойдет то, как предлагал Сергей /savingsAccounts/owner

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
> +    tariff_type VARCHAR(24) UNIQUE NOT NULL,
Если у тебя тип уникальный, то может быть он может выступать в качестве первичного ключа? Зачем тебе ещё id?

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/controller/tariff/TariffController.java
> +    @PutMapping
Написала в миграции, нужен ли тебе вообще id?

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/entity/tariff/Tariff.java
> +    private String tariffType;
Название как будто бы намекает на enum, может быть лучше назвать tariffName? или title? Так не лучше будет?

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Retryable(retryFor = {IOException.class, OptimisticLockException.class}, maxAttempts = 5)
maxAttempts лучше вынести в конфиг

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/repository/account/SavingsAccountRepository.java
> +    @Query("SELECT sa FROM SavingsAccount sa WHERE sa.lastInterestDate IS NULL OR sa.lastInterestDate < CURRENT_DATE")
А через запросный метод такое нельзя написать? Там есть IsNull, а текущую дату можно параметром передать LocalDateTime.now()

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Retryable(retryFor = {IOException.class, OptimisticLockException.class}, maxAttempts = 5)
maxAttempts лучше вынести в конфиг

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/repository/account/SavingsAccountRepository.java
> +    @Query("SELECT sa FROM SavingsAccount sa WHERE sa.lastInterestDate IS NULL OR sa.lastInterestDate < CURRENT_DATE")
А через запросный метод это нельзя сделать? Там есть IsNull, а текущую дату можно параметром передать LocalDate.now()

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +    private void updateTariffHistory(Tariff tariff, SavingsAccount savingsAccount) {
может addTariffToHistory?

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +                    .divide(BigDecimal.valueOf(100), RoundingMode.HALF_UP)
BigDecimal.valueOf(100) - в константы

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +    private void calculate(List<SavingsAccount> savingsAccounts) {
Как будто бы эту логику можно вынести в отдельный класс-калькулятор, в сервисе она смотрится немного неуместно. А вот в отдельный класс очень хорошо выделяется) Сервис обычно выступает в качестве "дирижёра": вызывает базу данных, другие классы, сторонние сервисы (через классы-клиенты), публикует событие в редис, между этим проверяет ответы и на этой основе делает другие действия. А если есть подобная логика вычислений, то это будет отдельный класс, который просто будет вызван в сервисе

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +    public Rate getRateByInterestRate(Double interestRate) {
Из названия метода неочевидно, что ещё и создание будет происходить в некоторых случаях. Нужно либо разбить это на два метода, либо придумать другое название)

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +    private void updateRateHistory(Tariff tariff, TariffRequestDto tariffRequestDto) {
Можно аналогично тому, как писала в другом классе - addRateToHistory

2024-11-01 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +            log.info("Failed to updated rate in tariff - {}", tariff);
Это error уровень должен быть. А разве gloabal exception handler не залоггирует? Зачем здесь лог?

2024-11-02 05:01 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/entity/tariff/Tariff.java
> +    private String tariffType;
Да, я тоже про это думала!) Думаю, что лучше поменять, чтобы никого не смущало)

2024-11-02 08:45 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/config/executor/ExecutorServiceConfig.java
> +        return Executors.newFixedThreadPool(treadCount);
Такс, тогда оставляем как есть)

2024-11-02 08:52 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
> +    rate_history TEXT NOT NULL,
Слушай, хороший вопрос, я гуглила этот момент и как поняла - можно как JSON, так и TEXT использовать, тк проблем не возникнет. Как в итоге правильно я так и не поняла) Я руководствовалась тут тем, что фактически в таблице у нас лежит именнто текст, но давай поставим JSON

2024-11-02 08:59 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +            log.info("Failed to updated rate in tariff - {}", tariff);
Маш, я вот тут плаваю капец! С логами и ошибками у меня прям непонимание. Я уберу, но понимания у меня нет!

2024-11-02 09:06 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +    private void updateRateHistory(Tariff tariff, TariffRequestDto tariffRequestDto) {
Поменяла

2024-11-02 09:10 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Retryable(retryFor = {IOException.class, OptimisticLockException.class}, maxAttempts = 5)
сделала

2024-11-02 09:10 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Retryable(retryFor = {IOException.class, OptimisticLockException.class}, maxAttempts = 5)
сделала

2024-11-02 09:23 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/account/SavingsAccountController.java
> +    @GetMapping("/account/{ownerId}")
хорошо, переделала

2024-11-02 09:25 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +    private void updateTariffHistory(Tariff tariff, SavingsAccount savingsAccount) {
да, переделала

2024-11-02 09:42 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +                    .divide(BigDecimal.valueOf(100), RoundingMode.HALF_UP)
забыла) сделала

2024-11-02 09:46 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/account/SavingsAccountService.java
> +    private void calculate(List<SavingsAccount> savingsAccounts) {
Хорошо, учту. Большое спасибо за развернутый комментарий!!)

2024-11-02 10:04 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
> +    tariff_type VARCHAR(24) UNIQUE NOT NULL,
Думала об этом и решила оставить id только из-за того, что отсутствие id у ентити лично у меня вызвало жесткий эрор)) давай убирать id!)

2024-11-02 10:19 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/controller/tariff/TariffController.java
> +    @PutMapping
убрала id

2024-11-02 10:43 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +    public Rate getRateByInterestRate(Double interestRate) {
додумалась только до такого))

2024-11-02 11:07 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/repository/account/SavingsAccountRepository.java
> +    @Query("SELECT sa FROM SavingsAccount sa WHERE sa.lastInterestDate IS NULL OR sa.lastInterestDate < CURRENT_DATE")
попробую

2024-11-02 11:07 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/repository/account/SavingsAccountRepository.java
> +    @Query("SELECT sa FROM SavingsAccount sa WHERE sa.lastInterestDate IS NULL OR sa.lastInterestDate < CURRENT_DATE")
попробую

2024-11-02 16:12 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
> +    rate_history TEXT NOT NULL,
Короче, я все перепроверила и если вместо TEXT делать JSON, то у меня вылетает ошибка, что я некорректные данные пытаюсь запихать в это поле. В итоге я предлагаю оставить как есть - TEXT

2024-11-02 19:47 UTC, StepnovaVarvara commented
> Вот сегодня я внимательно поревьювила, оставила комментарии) И ещё жду интеграционный тест)

Я просто афигела писать эти тесты, я просто закончилась!

2024-11-03 20:10 UTC, mysosnovskaya requested changes

2024-11-03 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Retryable(retryFor = {IOException.class, OptimisticLockException.class}, maxAttempts = 5)
Это как правило хорошего тона - все настраиваемые параметры всегда выносить в конфиг. Я точно знаю, что с maxAttempts это можно сделать. Давай разберемся, как это делается. Там не через Value)

2024-11-03 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/moderation/InterestCalculator.java
> +package faang.school.accountservice.moderation;
А почему калькулятор в пакете moderation? Можно завести отдельный пакет calculator

2024-11-03 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +    public Rate generateRateByInterestRate(Double interestRate) {
Можно getOrCreateRateByInterestRate

2024-11-03 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +            throw new RuntimeException(ex);
Давай поговорим про логи и ошибки, напомни на встрече)

2024-11-03 20:10 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
Тут версию миграции нужно поменять на V004, т.к. в мастере последняя V003

2024-11-03 20:10 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/controller/tariff/TariffControllerMockMvcIT.java
> +class TariffControllerMockMvcIT {
Отличные тесты получились 👍 Интеграционные всегда сложнее юнит-тестов, но как и в любом другом деле самое сложное - это начать) И обязательно укажи навык написания интеграционных тестов в резюме - это важно)

2024-11-05 02:22 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
> +    tariff_name VARCHAR(24) PRIMARY KEY UNIQUE NOT NULL,
убрала

2024-11-05 02:22 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
хорошо, поменяла

2024-11-05 02:26 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/moderation/InterestCalculator.java
> +package faang.school.accountservice.moderation;
сделала

2024-11-05 02:27 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +    public Rate generateRateByInterestRate(Double interestRate) {
блин, я думала так нельзя называть!

2024-11-05 02:27 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +            throw new RuntimeException(ex);
поговорили

2024-11-05 02:31 UTC, StepnovaVarvara commented on src/test/java/faang/school/accountservice/controller/tariff/TariffControllerMockMvcIT.java
> +class TariffControllerMockMvcIT {
Маша, спасибо тебе большое за отличный видос с разбором этих тестов!) Про резюме - поняла

2024-11-05 02:41 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/moderation/ModerationScheduler.java
> +    @Retryable(retryFor = {IOException.class, OptimisticLockException.class}, maxAttempts = 5)
Хорошо, сделала через конфигурационный класс

2024-11-05 04:11 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
> +    rate_history TEXT NOT NULL,
Ошибка в том, что если мы указываем тип JSON вместо TEXT, то БД не может себе сохранить результаты выполнения маппинга. Мы хотели бы хранить в БД JSON-объект, а сами пихаем в туда строку: "[1.0,2.0]" (ошибка: Caused by: org.postgresql.util.PSQLException: ERROR: column "rate_history" is of type json but expression is of type character varying). Если мы оставляем JSON, то тип данных в нашем поле rateHistory сущности Tariff нужно менять. Там должно быть не String, а что-то другое. Пробовала сделать там JSONString и JsonNode, в итоге добавилась часть кода (не маленькая) , тк пошла цепная реакция, но результата пока 0. Можно, конечно, пробовать еще, и возможно все получится) Но из того что я попробовала вижу, что у нас увеличивается код + он становится менее понятным чтоли (из-за перегонок типов туда сюда: при использовании objectMapper или в TariffMapper и тд). Я просто не уверена, что эта корректировка "JSON" стоит всех этих изменений в коде с учетом того, что при использовании TEXT все работает именно так как мы хотим. Я же когда код пишу, то иду от обратного: типо я щас изменила "50" строк кода из-за одного слова - это того стоило? Как-то так пояснила))

2024-11-05 18:19 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V001__account-service_savings-account.sql
> +    rate_history TEXT NOT NULL,
Тип поля нужно было обновить на List<Double> и всё заработало бы, 50 строк кода не появилось бы) Но в целом ты уже где-то выше писала, что хочешь оставить именно String, чтобы избежать лишних конвертаций (пусть даже не мы сами их делаем, а спринг), это ок. Пусть остается как есть

2024-11-05 18:23 UTC, mysosnovskaya reviewed
Обнови ПР и можешь смержить сама)

2024-11-05 18:23 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/V004__account-service_savings-account.sql
> +    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
UNIQUE остался :)

2024-11-05 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/config/retry/RetryConfig.java
> +public class RetryConfig {
Можно было проще: у аннотации Retryable есть параметр maxAttemptsExpression, в него можно было подставить "${retry.interestCalculator.maxAttempts}" и всё заработало бы :)

2024-11-05 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +    public Rate getOrCreateRateByInterestRate(Double interestRate) {
Так называть (через OR или AND) плохая практика, но иногда по-другому никак)

2024-11-05 19:17 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/V004__account-service_savings-account.sql
> +    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
Я думала, что мы стобой говорили только про значение UNIQUE на поле tariff_name в таблице tariffs. Я уберу во всех таблицах, но видимо я тебя не так поняла + у нас во всех таблицах на всех айдишниках этот UNIQUE. Короче, я поняла, что если мы его уберем с PRIMARY KEY, то ничего не изменится)

2024-11-05 19:22 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/service/rate/RateService.java
> +    public Rate getOrCreateRateByInterestRate(Double interestRate) {
Поняла, спасибо!)

2024-11-05 19:24 UTC, StepnovaVarvara commented on src/main/java/faang/school/accountservice/config/retry/RetryConfig.java
> +public class RetryConfig {
Блин, я вроде бы так тыкалась, но у меня ничего не вышло. Видимо не так тыкалась!((

2024-11-05 19:42 UTC, merged