Feature BJS2 26199
CorporationX/account_service pull request #284
Opened 2024-11-06 20:03 UTC by Silencemess1ah

Generating unique free account numbers in schedule

2024-11-07 07:01 UTC, segaTk reviewed
Посмотрел, понял что не понял, тест лайк!

2024-11-07 07:01 UTC, segaTk commented on src/main/java/faang/school/accountservice/enums/account/AccountEnum.java
> +    BUDGET("3388");
А здесь должны быть значения?

2024-11-07 07:29 UTC, GusevVrn reviewed
Нрациа. 
Единственное т.к. у нас много типов счетов, каждый тип можно асинхронно обрабатывать, а можно и не заморачиваться.

2024-11-07 07:29 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +        String sql = properties.getAccountNumbers().getBatchSaveSQL();
Я в первый раз вижу реализацию где sql засунули в проперти, обычно его прям в коде и хардкодят.

2024-11-07 07:29 UTC, GusevVrn commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    int countAllFreeAccountNumbersByType(@Param("accountType") AccountEnum accountType);
https://www.baeldung.com/spring-data-jpa-row-count

2024-11-07 21:11 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/enums/account/AccountEnum.java
> +    BUDGET("3388");
Да мы задаем префикс для каждого из счетов, 4200 000 0000 2345 и т.д. и для другого чтоб можно было понять что за счет визуально + у каждого будет уникальный номер в рамках префикса, 2222 0000 0000 2345 допустим тоже будет валидно при номере выше

2024-11-07 21:11 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +        String sql = properties.getAccountNumbers().getBatchSaveSQL();
Я хз, надо у нашего многоуважаемого лида уточнить этот момент, мне просто глаза мозолила)

2024-11-07 21:12 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    int countAllFreeAccountNumbersByType(@Param("accountType") AccountEnum accountType);
Я пытался так как описано, так как сущности муторные (embedded и т.д.) не работало

2024-11-08 19:10 UTC, mysosnovskaya requested changes

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        String accountNumber = freeAccountNumber.getId().getAccountNumber();
Для удобства можно в классе FreeAccountNumber сделать метод getAccountNumber, который вернет id.getAccountNumber(). Ну, если такой вызов планируется часто делать. Если один раз, то можно и в текущем виде оставить)

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +        String sql = properties.getAccountNumbers().getBatchSaveSQL();
Обычно так не делают) properties это про какие-то настройки приложения, когда что-то может измениться. А sql он один, который корректно работает. Тут ничего разного не придумаешь) Его можно в константы вынести или в отдельный класс с константами

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +            template.batchUpdate(sql, freeAccountNumbers, freeAccountNumbers.size(),
Вообще это логика репозитория и сервис не должен этим заниматься. 
1. Либо создай отдельный класс-репозиторий с JdbcTemplate 
2. Либо сделай через текущий репозиторий. По какой-то причине через saveAll не получилось сохранить?

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +            throw new RuntimeException();
Тут не поняла =) Почему пустое исключение?

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +            log.error("Error occurred while batch save! {}", dae.getMessage());
А стектрейс залогировать?)

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/generator/FreeAccountNumbersGeneratorSchedulerService.java
> +public class FreeAccountNumbersGeneratorSchedulerService {
FreeAccountNumbersGeneratorScheduler, сервис не нужно подписывать

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/generator/FreeAccountNumbersGeneratorSchedulerService.java
> +@Service
Здесь Component лучше подойдет, т.к. это всё-таки не сервисный слой. Шедулер использует сервисный слой, а сам находится как бы на уровень выше (условно)

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/generator/FreeAccountNumbersGeneratorSchedulerService.java
> +            int freeAccountNeeds = accountProperties.getAccountNumbers()
Очень неочевидная связь accountType с i. Если изменим порядок в перечислении, то все настройки сломаются? Подумай, как это можно красивее реализовать) Чтобы в yaml можно было указывать явно DEBIT 400

2024-11-08 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/service/generator/FreeAccountNumbersGeneratorSchedulerService.java
> +                        freeAccountNeeds - existingAccountsNumberByType);
Кстати говоря, java doc можно добавить)

2024-11-08 19:10 UTC, mysosnovskaya commented on src/test/java/faang/school/accountservice/service/generator/FreeAccountNumbersGeneratorSchedulerServiceIT.java
> +    public void whenMethodCalledThenCreatesAccountNumbersNeedsByPropertiesSettingsInSchedule(){
Можно ещё написать тест, когда в базе уже были какие-то свободные номера, чтобы проверить, что не сгенерируется больше нужного)

2024-11-08 19:15 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/service/account/FreeAccountNumbersService.java
> +            template.batchUpdate(sql, freeAccountNumbers, freeAccountNumbers.size(),
saveAll() не работал как задумано -> просто делал так: передавал список из 10 сущностей, он делал 10 select-ов, потом 10 insert-ов , итого кол-во сущностей х 2 обращений к базе, перепробовал всё помогло только это

2024-11-08 19:22 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepository.java
> +    int countAllFreeAccountNumbersByType(@Param("accountType") AccountEnum accountType);
Да всё работает!

2024-11-08 21:11 UTC, Silencemess1ah commented on src/test/java/faang/school/accountservice/service/generator/FreeAccountNumbersGeneratorSchedulerServiceIT.java
> +    public void whenMethodCalledThenCreatesAccountNumbersNeedsByPropertiesSettingsInSchedule(){
Это было весьма полезно... так как выяснилось что в методе который единичный не было обновления счетчика

2024-11-08 22:17 UTC, Silencemess1ah commented
Учел все замечания, логику yaml, SQL запроса, понял что неправильно работают: одиночный генератор создания аккаунта, создание аккаунта в аккаунт сервисе. поправил тесты, добавил немного тестов в свой чтобы удостовериться что лишнего ничего не создается.

2024-11-08 22:18 UTC, Silencemess1ah commented on src/main/java/faang/school/accountservice/service/generator/FreeAccountNumbersGeneratorSchedulerService.java
> +            int freeAccountNeeds = accountProperties.getAccountNumbers()
Пушка! Поменял на мапу, почему сразу не догадался не знаю(

2024-11-09 18:53 UTC, mysosnovskaya approved these changes
Отлично получилось 👍 И тест стал покрывать больше случаев, и в yaml стало гораздо более понятно. И даже баг нашел с помощью теста - точно не зря) Поправь только логирование исключения и можешь сам смержить этот ПР

2024-11-09 18:53 UTC, mysosnovskaya commented on src/main/java/faang/school/accountservice/repository/account/FreeAccountNumbersRepositoryImpl.java
> +            log.error("Error occurred while batch save! {}", (Object) dae.getStackTrace());
Если просто dae передашь, то стектрейс залоггируется =) Передавать dae.getStackTrace() не нужно

2024-11-09 20:06 UTC, merged