BJS2-27152 Savings Accounts and Tariffs
CorporationX/account_service pull request #285
Opened 2024-11-06 20:22 UTC by amilosh

2024-11-06 21:10 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savedSavingsAccount, currentRate, balance);
Всю жизнь работал с подходом, когда в сервис отдаем dto, все там внури делаем (внури transactioanal) и возвращаем в контроллер responseDto

И когда я извлекал savedSavingsAccount.getAccount().getId() я думал, что упадет Lazy Exception (мы то из транзакции уже вышли). Но спринг всё равно видит все лэйзи поля.
Не знаю как это работает и есть ли подводне камни. Но работает и я оставил так.

2024-11-06 21:10 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +        savingsAccount.setAccount(createdAccount);
Тут тоже протестил - все кейсы. Метод openAccount(account) использует вот эту текущую ранззакцию, и если в любом месте падает, то откатвается везде.

2024-11-06 21:10 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/TariffController.java
> +    }
Здесь тоже. Там tariffRate lazy, но в контроллере нормально в маппер передается

2024-11-06 21:10 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +
Сделал отдельный метод именно для создания сушности, чтобы не мучать оптимистическую блокировку.
А saveBalance(Balance balance) - оставил для апдейта сущности с опт. блок-й.

2024-11-06 21:10 UTC, amilosh commented on src/main/java/faang/school/accountservice/repository/SavingsAccountRepository.java
> +    double getCurrentRate(@Param("savingsAccountId") UUID savingsAccountId);
Это то что мы обсуждали на давнишнем мите, чтобы current rate не через стримы искать или доп. поле, а через sql запрос. Запрос чатом сгенерил.

2024-11-08 17:18 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savingsAccount, currentRate, balance);
Лучше через @Transient поле, потому что неизвестно, в каком другом месте могут понадобиться эти данные

2024-11-08 17:19 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +        foundTariff.getTariffRates().add(tariffRate);
Список точно не null, я надеюсь, ты его проинициализировал
Как минимум, он пустой

Значит, всё ок, два вызова - нормально

2024-11-08 17:55 UTC, 20cognosce requested changes

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/entity/savings_account/SavingsAccount.java
> +    @OneToOne
У тебя один к одному связь, это не лейзи поле, оно фетчится жадно всегда

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savedSavingsAccount, currentRate, balance);
@OneToOne - EAGER по дефолту

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savedSavingsAccount, currentRate, balance);
Почему столько логики тут
Только убрать лишнее, здесь работа с ДТО из/в сущности, и всё

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        SavingsAccount savedSavingsAccount = savingsAccountService.openSavingsAccount(account, savingsAccount, dto.getTariffId(), dto.getMoney().amount());
Выглядит криво

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        Balance balance = balanceService.findByAccountId(savingsAccount.getAccount().getId());
Нет, отписал

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/controller/TariffController.java
> +    }
Возможно new ArrayList<>() решает

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/SavingsAccountRepository.java
> +    double getCurrentRate(@Param("savingsAccountId") UUID savingsAccountId);
Это хорошо, а нельзя сразу жадно всё сфетчить, там много выходит связных сущностей у накопительного счета по тарифам? Не уверен, может целесообразнее было все тарифы всегда подтягивать

2024-11-08 17:55 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/account_V003__create_savings_account.sql
> +    created_at TIMESTAMP                  DEFAULT CURRENT_TIMESTAMP,
Тарифов и ставок наверно не так много + это статическая (справочная информация), почему бы не сделать им id bigint'ом и на старте приложения инициализировать базу заготовленными данными?

2024-11-08 17:55 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/account_V003__create_savings_account.sql
> +CREATE TABLE savings_account_tariff (
Не понятное наименование
Лучше 
tariff_to_savings_account_binding или
tariff_binding

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountAccrualService.java
> +        savingsAccounts.forEach(savingsAccount -> calculateAccrualsThreadPool.submit(() -> {
Пробелы между логическими блоками кода не помешали бы

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +
Не понял, зачем?
Как ты мучаешь блокировку...

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/repository/balance/BalanceRepository.java
> +    Optional<Balance> findByAccountId(@Param("accountId") UUID accountId);
1. Дай им разные имена, если с блокировкой - добавить это в имя метода
2. Зачем тебе @Query?
3. Включи полные логи и покажи момент начала транзакции, лок, обновление, снятие лока и закрытие транзакции хибернейтом

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +        savingsAccount.setLastCalculationDate(now);
Зачем так дату передавать в метод, почему здесь нельзя обновить
Или вообще аннотацией обновлять дату последнего изменения

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +    @Retryable(
Тебе не кажется, что ретрай внутри транзакции это странно
Наверно лучше на ретрай создавать новую транзакцию

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +        double multiplyValue = currentRate / 100;
Сразу в таком виде нельзя возвращать?

2024-11-08 17:55 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        saveBalance(balance);
Если ты уже захватил пессимистическую блокировку, зачем тебе еще и оптимистическая
Продебажь этот участок кода тщательно

2024-11-08 17:55 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/service/balance/BalanceServiceTest.java
>  class BalanceServiceTest {
Ну и без тестов не принимается

2024-11-08 17:55 UTC, 20cognosce commented on src/test/java/faang/school/accountservice/service/balance/BalanceServiceTest.java
>  class BalanceServiceTest {
А еще и с билдом поломанным

2024-11-08 19:01 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +
Там в методе
```
private Balance saveBalance(Balance balance) {
        try {
            balance = balanceRepository.save(balance);
            balanceRepository.flush();
        } catch (OptimisticLockingFailureException exception) {
            throw new BalanceHasBeenUpdatedException(balance.getId());
        }
        return balance;
    }
```
try catch создается, save, flush, OptimisticLockingFailureException - это всё равно во время первго сейва не будет работать, только ресурсы занимать
поэтмоу вынес в отдельнй метод

2024-11-08 19:08 UTC, amilosh commented on src/main/java/faang/school/accountservice/repository/SavingsAccountRepository.java
> +    double getCurrentRate(@Param("savingsAccountId") UUID savingsAccountId);
Я первый раз так и сделал. Но чтобы потом достать последний рэйт нужно по всем тарифам пройтиь и найти последний, а потом в этом тарифе тоже самое для рейтов сделать.
И ты сказал, давай лучше SQL запрос.

А связных сущнотей дам дна-две.

2024-11-08 19:25 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        SavingsAccount savedSavingsAccount = savingsAccountService.openSavingsAccount(account, savingsAccount, dto.getTariffId(), dto.getMoney().amount());
Если мы используем подход, чо передаем в сервисы только объекты сущностей и примитивы, то ут по другоому никак.
Account, SavingsAccount, Tariff, Balance - тут в любом случае пришлось бы 4 параметра делать.

2024-11-08 20:15 UTC, amilosh commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/account_V002__create_balance.sql
resolved

2024-11-08 20:16 UTC, amilosh commented on src/main/java/faang/school/accountservice/entity/savings_account/SavingsAccount.java
> +    private UUID id;
resolved

2024-11-08 20:16 UTC, amilosh commented on src/main/resources/db/changelog/changeset/account_V003__create_savings_account.sql
> +    rate       DOUBLE PRECISION NOT NULL,
resolved

2024-11-08 20:16 UTC, amilosh commented on src/main/java/faang/school/accountservice/entity/tariff/Tariff.java
> +}
resolved

2024-11-08 20:16 UTC, amilosh commented on src/main/java/faang/school/accountservice/dto/savings_account/OpenSavingsAccountDto.java
> +    private AccountType type;
resolved

2024-11-08 20:17 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savingsAccount, currentRate, balance);
Переделал на @transient

2024-11-08 20:27 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savingsAccount, currentRate, balance);
resolved

2024-11-08 20:32 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +        foundTariff.getTariffRates().add(tariffRate);
Да, во время создания добавляю как минимум один рейт, так что getTariffRates() не будет пустым.

2024-11-08 20:32 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +        foundTariff.getTariffRates().add(tariffRate);
resolved

2024-11-08 20:33 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    @Transactional(propagation = Propagation.MANDATORY)
resolved

2024-11-08 20:35 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +        savingsAccount.setAccount(createdAccount);
resolved

2024-11-08 20:37 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savedSavingsAccount, currentRate, balance);
сделал с пмощью @transient

2024-11-08 20:37 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        return savingsAccountMapper.toResponseDto(savedSavingsAccount, currentRate, balance);
resolved

2024-11-08 20:37 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +        Balance balance = balanceService.findByAccountId(savingsAccount.getAccount().getId());
resolved

2024-11-08 20:37 UTC, amilosh commented on src/main/java/faang/school/accountservice/controller/TariffController.java
> +    }
resolved

2024-11-08 20:48 UTC, amilosh commented on src/main/resources/db/changelog/changeset/account_V003__create_savings_account.sql
> +    created_at TIMESTAMP                  DEFAULT CURRENT_TIMESTAMP,
Поменял на BIGINT.
А заполение какие тарифы и ставки - оставил на меннеджеров аплика, которе через UI их создадут.

2024-11-08 20:49 UTC, amilosh commented on src/main/resources/db/changelog/changeset/account_V003__create_savings_account.sql
> +    created_at TIMESTAMP                  DEFAULT CURRENT_TIMESTAMP,
resolved

2024-11-08 20:53 UTC, amilosh commented on src/main/resources/db/changelog/changeset/account_V003__create_savings_account.sql
> +CREATE TABLE savings_account_tariff (
resolved

2024-11-08 20:55 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountAccrualService.java
> +        savingsAccounts.forEach(savingsAccount -> calculateAccrualsThreadPool.submit(() -> {
resolved

2024-11-08 21:00 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +        savingsAccount.setLastCalculationDate(now);
Чтобы вызвать 
LocalDate now = LocalDate.now();
только один раз, а не перед каждым сооздавать новый объект - всё равно будет одна и та же дата.

2024-11-08 21:13 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +        double multiplyValue = currentRate / 100;
getCurrentRate(savingsAccount.getId()); - используется в другом месте, чтобы вернуть на фронт 5.5%
а тут мне нужно 0.055 передать

а если getCurrentRate возвращать с деленным уже на 100 - то будет путаница, потому что rate - это сставка в процентах

2024-11-08 21:14 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        saveBalance(balance);
вот тут как раз и понадообился тот мой отдельный метод persistBalance(Balance balance) без блокировки

2024-11-08 21:15 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        saveBalance(balance);
поменял на persistBalance(balance)

2024-11-08 21:22 UTC, amilosh commented on src/main/java/faang/school/accountservice/repository/balance/BalanceRepository.java
> +    Optional<Balance> findByAccountId(@Param("accountId") UUID accountId);
1 и 2
я использую синтаксис spring data: findByAccount_Id() - и использую этот метод просто для доставаия баланса (без блокировок)
соответсвенно чтобы создать ещё один метод, но уже сс блокировкой - нужно создать метод с овым названием, но это новое название уже не будет в синтакисе spring data
поэтому я и сделал HQL

2024-11-10 19:17 UTC, amilosh commented on src/main/java/faang/school/accountservice/repository/balance/BalanceRepository.java
> +    Optional<Balance> findByAccountId(@Param("accountId") UUID accountId);
ok

2024-11-12 19:12 UTC, 20cognosce approved these changes

2024-11-12 19:12 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        }
orElseGet метод у Optional

2024-11-12 19:12 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        Optional<Balance> balanceOpt = balanceRepository.findBalanceByAccountId(account.getId());
Opt не надо прибавлять к имени

2024-11-12 19:12 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +                new ResourceNotFoundException(Balance.class, accountId));
Лучше .orElseThrow() переносить

2024-11-12 19:12 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    }
Убери этот метод, вызывай просто на репозитории save

2024-11-12 19:12 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountAccrualService.java
> +    private final ExecutorService calculateAccrualsThreadPool;
ExectorService != ThreadPool

2024-11-12 19:12 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +        TariffRate tariffRate = build(foundTariff, newRate);
Ты столько классов насоздавал, билдеров, в которых выполняются фактически 2 строчки
Лучше приватный метод, или прям тут

Ну ради двух строчек избыточно

2024-11-12 19:12 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +    }
Хорошо, но почему дублирование кода

2024-11-12 19:13 UTC, merged

2024-11-14 00:23 UTC, amilosh commented on src/main/resources/db/changelog/changeset/account_V004__create_savings_account.sql
> +    id          BIGINT      NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
Да, ты прав.
GENERATED ALWAYS AS IDENTITY UNIQUE - это нужно, если оздаем юзера через нэйтив инсерты.
А когда создаём из java кода, то используется jpa аннотация
@GeneratedValue(strategy = GenerationType.IDENTITY)
которая генерирует айдишки (по умолчанию инкрементно)

2024-11-14 00:26 UTC, amilosh commented on src/main/resources/db/changelog/changeset/account_V004__create_savings_account.sql
> +     CONSTRAINT fk_savings_account_account_id FOREIGN KEY (account_id) REFERENCES account (id)
поправил

2024-11-14 00:26 UTC, amilosh commented on src/main/resources/db/changelog/changeset/account_V004__create_savings_account.sql
> +    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
поправил

2024-11-14 00:31 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        }
сделал

2024-11-14 00:31 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        Optional<Balance> balanceOpt = balanceRepository.findBalanceByAccountId(account.getId());
сделал

2024-11-14 00:32 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +                new ResourceNotFoundException(Balance.class, accountId));
поправил

2024-11-14 00:33 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    }
сделал

2024-11-14 00:35 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountAccrualService.java
> +    private final ExecutorService calculateAccrualsThreadPool;
переименовал

2024-11-14 00:39 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/tariff/TariffService.java
> +        TariffRate tariffRate = build(foundTariff, newRate);
Удалил все билдеры.
Методы перенес в приватные.

2024-11-14 00:44 UTC, amilosh commented on src/main/java/faang/school/accountservice/service/savings_account/SavingsAccountService.java
> +    }
подформатировал