BJS2-27154 Кэшбеки
CorporationX/account_service pull request #289
Opened 2024-11-08 13:09 UTC by cemeh666

2024-11-08 13:10 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        AuthPayment payment = build(balanceId, balance, balance, money.amount(), Category.OTHER);
костыль, чтобы проект собирался

2024-11-10 09:04 UTC, sultan-inked commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +                .forEach(cashbackMerchant -> removeMerchantCashback(cashbackMerchant.getId()));
Возможно стоило бы прописать так, что бы Hibernate автоматически удалял связанные записи, не знаю какие проблемы может вызвать такой подход, но выглядит проще, чем плодить методы:
```java
@OneToMany(mappedBy = "cashbackTariff", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
private Set<CashbackOperationType> cashbackOperationTypes;

@OneToMany(mappedBy = "cashbackTariff", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
private Set<CashbackMerchant> cashbackMerchants;
```

2024-11-10 16:50 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +                .forEach(cashbackMerchant -> removeMerchantCashback(cashbackMerchant.getId()));
ох нет. удаление каскадом - это потеря контроля над работой приложения

2024-11-10 16:53 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +        cashbackTariff.setUpdatedAt(LocalDateTime.now());
при таком раскладе
@UpdateTimestamp
при создании записи, будет проставляться **updatedAt**, и в момент, когда тебе нужно при сохранении батча, чтобы время обновления было одним - эта анотация время всем записям разное поставит (были проблемы с этим при корректировки постов)

2024-11-10 16:54 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +        cashbackTariff.setCreatedAt(LocalDateTime.now());
так больше контроля

2024-11-10 16:57 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/repository/MerchantRepository.java
> +    Merchant findByProjectId(long projectId);
если их убрать, будет ошибка
```
error: cannot find symbol
            return merchantRepository.findByUserId(account.getUserId());
```

2024-11-12 20:11 UTC, 20cognosce requested changes

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        account.setCashbackTariff(null);
Может есть дефолтный с 0%

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +        balance.setCurrentBalance(currentBalance.add(cashback));
Поддерживаю

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    @Retryable(retryFor = {BalanceHasBeenUpdatedException.class})
Ретраи протестил?

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +        CashbackTariff cashbackTariff = findCashbackTariffById(id);
Ты запоминаешь id всех тарифов?
На имена переделать

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +    public CashbackTariff updateTariff(UUID id, CashbackTariff tariff) {
cashbackTariff 
tariff

Понятнее имена давай переменным, кто есть кто

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +        cashbackTariff.getCashbackMerchants()
Как у тарифа можно удалить пользователя?
Наверно у пользователя можно удалить тариф

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +        for (AuthPayment payment : payments) {
forEach

2024-11-12 20:11 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +            totalCashback = totalCashback.add(result);
В один момент ты выгребаешь из базы все оплаты за целый месяц по всем аккаунтам и начинаешь мегакалькуляцию

Я боюсь сервер не выдержит столько)))
И надорвётся

Подумай на тем, чтобы равномернее размазать нагрузку - как я предлагал, каждый день считать кэшбек например, может еще придумаешь вариант

2024-11-13 08:38 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    @PutMapping("/{id}/cashback-tariff/{tariffId}")
имя тарифа не уникально. сделал Patch

2024-11-13 08:54 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/entity/cacheback/CashbackTariff.java
> +    private Set<Account> accounts;
это убрал` Set<Account> accounts`
а вот на счёт жадной подгрузки, я лучше отдельный метод для этого сделал, чтобы только по надобности подгружать и их может быть неконтролируемо много или мало

2024-11-13 09:10 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +    project_id  BIGINT,
Добавил уникальные индексы. Предполагается, что всегда заполнен **user_id** или **project_id**  
проверка на это должна быть в сервисе при создании

2024-11-13 09:12 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +    updated_at  TIMESTAMP
что не так?

2024-11-13 09:13 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +    name        VARCHAR(255) NOT NULL,
нет условия, чтобы **name** был уникальным

2024-11-13 09:18 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +CREATE INDEX idx_cashback_tariff_created_at ON cashback_tariff (created_at);
да. скорее всего и не нужны индексы, так как не используются, но на скорость сортировки они же тоже влияют. не только же на точный поиск

2024-11-13 09:20 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +    CONSTRAINT fk_cashback_operation_type_cashback_tariff FOREIGN KEY (cashback_tariff_id) REFERENCES cashback_tariff(id)
лучше давать, чтобы потом можно было удалить по имени, да и потом найти в какой миграции он был создан

2024-11-13 09:21 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/controller/CashbackTariffController.java
> +    @PostMapping("/{tariffId}/tariff/attach-operation")
что не так? что именно переписать?

2024-11-13 09:24 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +CREATE INDEX idx_cashback_operation_type_cashback_tariff_id_operation_type ON cashback_operation_type(cashback_tariff_id, operation_type);
тут был расчёт, но нужно будет искать все операции по типу или же по конкретному тарифу и типу, но не пригодилось

2024-11-13 09:27 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +CREATE INDEX idx_account_status ON auth_payment(status);
да. статус уже лишний, если есть (status, created_at)

2024-11-13 09:32 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        account.setCashbackTariff(null);
зачем дефолтный? просто удаляем связь с тарифом

2024-11-13 09:41 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/balance/BalanceService.java
> +    @Retryable(retryFor = {BalanceHasBeenUpdatedException.class})
да. нашёл ошибку. если баланс не обновлять, то ретраи будут постоянно без результатно

2024-11-13 09:43 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +        CashbackTariff cashbackTariff = findCashbackTariffById(id);
не понимаю зачем на имена переделывать? обновление по id точнее и правильнее

2024-11-13 09:48 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +        cashbackTariff.getCashbackMerchants()
Нет. Это не пользователи, а продавцы и сами продавцы не знают про тарифы. 
знает таблица **cashback_merchant** которая ссылается на **cashback_tariff_id** и **merchant_id**

2024-11-13 10:02 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/cashback/CashbackTariffService.java
> +            totalCashback = totalCashback.add(result);
не так всё происходит.
я для каждого акаунта беру завершённые расходные операции
и для каждого одного акаунта считаю кешбек.
нагрузку на сервер можно регулировать размером **threadPool** и **batchSize** акаунтов

2024-11-13 10:06 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +        Executor executor = Executors.newFixedThreadPool(threadPool);
кажется не целесообразным менять на ежедневные проценты.
в банковских приложениях это происходит раз в месяц и противоречит условию задачи

2024-11-13 10:09 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +        } while (!accounts.isEmpty());
так а зачем вне в БД ходить дважды за акаунтами?
акаунты в себе содержат немного данных.
тут и есть сразу батчи и по условию задачи асинхронно считаем для каждого акаунта

> Это джоба должна пройтись по всем счетам и для каждого счета асинхронно/параллельно вычислять ежемесячный кэшбек

2024-11-13 19:02 UTC, 20cognosce requested changes
Видел же что билд упал, надо править тесты

2024-11-13 19:02 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +        } while (!accounts.isEmpty());
>Не понимаю, зачем тебе тут Future, никаких коллбеков нет, только для join, ну такое
Плюс запросы к базе в цикле вдобавок...

2024-11-14 06:39 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +    updated_at  TIMESTAMP
для **updated_at**  не нужен NOT NULL если ты об этом

2024-11-14 06:40 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/V006__account-service_cashback.sql
> +CREATE INDEX idx_cashback_tariff_created_at ON cashback_tariff (created_at);
что нет?

2024-11-14 06:44 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/service/account/AccountService.java
> +        account.setCashbackTariff(null);
я не понимаю, как ты хочешь, чтобы работало??
создать в БД запись с каким-то тарифом, но мы же в самом тарифе не храним процент

2024-11-14 09:12 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/controller/CashbackTariffController.java
> +    @GetMapping("/{id}/tariff")
что ты тут имеешь в виду?

> В составе DTO кэшбека всегда неси тариф, зачем плодить методы

поконкретнее

2024-11-14 10:09 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +        } while (!accounts.isEmpty());
переделал на получение id account

2024-11-14 10:10 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/controller/CashbackTariffController.java
> +    @GetMapping("/{id}/tariff")
переделал пути

2024-11-15 13:04 UTC, 20cognosce requested changes

2024-11-15 13:04 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +                batch.forEach(accountId -> executorService.execute(() -> {
Почему ты используешь один поток тред пула для одного аккаунта из твоего батча

Всего 1000 аккаунтов, 50 потоков, в батче 50 айдишников

Ты положил в каждый поток тред пула по одному айдишнику из первого батча, потоки вычисляют кэшбеки, все нормально

А 950 следующих стоят и ждут

Следующие 50 забрал и раскидал по потокам

900 стоят и ждут

Это не оптимально, в чём тут применение батча тогда вообще

2024-11-15 13:04 UTC, 20cognosce commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +        executorService = Executors.newFixedThreadPool(threadPool);
Тред пул должен соответствовать числу батчей и каждый поток должен принимать батч целиком

Тогда ты 1000 / 50 = 20 батчей сразу закинул в 20 потоков и все стартанули вычислять кэшбеки сразу.

50 элементов в цикле одного потока - ничто, по сравнению с ожиданием батчей в очереди, пока до отдельно батча дойдет цикл

2024-11-15 13:36 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +                batch.forEach(accountId -> executorService.execute(() -> {
я с тобой согласен, что это может быть не оптимальным решением, но это было одно из условий задачи. тут я ничего не придумал
![image](https://github.com/user-attachments/assets/ffaf3a78-6101-4626-9c17-59f32787deb1)

2024-11-15 13:36 UTC, cemeh666 commented on src/main/java/faang/school/accountservice/scheduler/CashbackScheduler.java
> +        executorService = Executors.newFixedThreadPool(threadPool);
переделал

2024-11-17 12:14 UTC, 20cognosce approved these changes

2024-11-17 12:14 UTC, merged