BJS2-41966 миграция
CorporationX/account_service pull request #300
Opened 2024-12-17 11:35 UTC by bozhedar

2024-12-18 09:51 UTC, Shakhaev approved these changes

2024-12-18 13:41 UTC, MiraGlaceon requested changes

2024-12-18 13:41 UTC, MiraGlaceon commented on src/main/resources/db/changelog/changeset/V001__account-service_account.sql
> +CREATE TABLE account
Желательно бы еще схему указывать при создании таблицы. На будущее знай. Таблицы тоже должны быть раскинуты по определенной логике в разные схемы, как мы раскидываем классы по разным пакетам

2024-12-18 13:41 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @Column(name = "user_id")
Можно повесить constraint на поле user_id и project_id. Потому что в реальном мире, должно быть заполнено что-то одно (если я не ошибаюсь, подправь, если не так). Поэтому нужно проверку, что одно поле заполнено, а другое обязательно null

2024-12-18 13:41 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    @Column(name = "payment_number", nullable = false, length = 20, unique = true)
Минимальную длину тоже нужно учитывать в 12ть цифр

2024-12-18 13:41 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +@Data
Давай используем только getter и setter и еще что-то из этой аннотации, если нужно. На сущности полный набор аннотаций из Data не нужен. Если, например, нужен метод toString(), то вполне его можно переопределить самому по paymentNumber

2024-12-21 19:23 UTC, MiraGlaceon requested changes

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/client/ProjectServiceClient.java
> +    @GetMapping("/project/{projectId}")
projects во множественном числе. Со стороны project_service тоже подправить нужно

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +@RequestMapping("/api/v1/accounts")
/api/v1 нужно вынести в конфигурацию, чтобы было по всему сервису. Посмотреть можно у Димы как он сделал в user_service

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    @GetMapping("/all/user/{userId}")
У тебя accounts уже множественное число, не стоит использовать all. И если получаешь юзера определенного счета, то нужно делать url с цепочкой. Например, accounts/{accountId}/user/{userId}. Так ты показываешь, что хочешь получить конкретного юзера конкретного счета

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/controller/AccountController.java
> +    @GetMapping("/all/project/{projectId}")
То же самое

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/dto/account/AccountDto.java
> +    private LocalDateTime createdAt;
Поля аудита не нужно передавать в DTO. DTO нужен, чтобы облегчить объект и передавать данные между слоями приложения. Если какие-то поля не предполагается использовать, то и в DTO их добавлять не нужно

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +@Table(name = "account", schema = "account_schema")
Приписку _schema делать не нужно. Достаточно account. Будет звучать как account.account, но можно оставить так, либо подобрать другое имя. Учитывай что еще будет лежать в этой схеме. Определенно еще balance, например. Тогда будет account.balance. Вообще по мимо счетов может быть и другие способы оплаты и кошельки. Можно дать схеме название credits. Но не думаю что это лучшее решение. Поразмысли с учетом того, какие таблицы должны быть в схеме

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/exception/account/AccountException.java
> +  public AccountException(String message) {
Имена ошибок должны говорить сами за себя. Сейчас у тебя понятно что ошибка по счетам, а что конкретно? Сделай конкретику, например, AccountNotValidException или AccountNotFoundException и тп

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        //метод для генерации номера платежного счета
А где генерируется номер счета и должен ли? Меня запутал этот комментарий. Думаю его нужно перенести, убрать или переформулировать

2024-12-21 19:23 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        return mapper.toDto(accountRepo.save(account));
У тебя уже сохранился счет и ты вызываешь маппер, чтобы лишний раз перевести сущность в DTO. У тебе же уже используется dto для сохранения. После сохранения там ничего нового не должно появиться. Про поля аудита написал выше

2024-12-23 16:08 UTC, bozhedar commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        //метод для генерации номера платежного счета
Сделал просто чтобы было удобнее навигироваться в коде тому кто будет с ним работать. По идее когда открывается счет, то нужно сгенерировать номер счета, но этим не я занимаюсь, по этому вместо заглушки чтобы не придумывать как метод будет называться оставил комментарий

2024-12-23 16:11 UTC, bozhedar commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        return mapper.toDto(accountRepo.save(account));
там номер счета в дто должен появится, в этот метод мы передаем дто без номера счета, но с нужными нам параметрами валюты, типа счета и его статуса, а уже обратно возвращается то же самое, но со сгенерированным номером счета

2024-12-25 15:12 UTC, frs717 commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    private Long balance;
Это же баланс счета? Тут лучше использовать другой тип BigDecimal. Значение может быть нецелым

2024-12-25 15:39 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/entity/account/Account.java
> +    private Long balance;
BigDecimal будет лучше. На будущее вероятно появится ссылка на баланс, но пока стоит сделать через этот тип

2024-12-25 15:40 UTC, MiraGlaceon approved these changes

2024-12-25 16:14 UTC, merged