Feature bc 5930
CorporationX/account_service pull request #32
Opened 2023-09-09 07:58 UTC by AntonRudnikovskiy

2023-09-10 12:42 UTC, kkkooolllyyyaaa requested changes
Покомментил)

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V007__indexes.sql
> +ON request(input_data)
Актуальные замечания с первого PR:
https://github.com/CorporationX/account_service/pull/11#pullrequestreview-1618818554

\+ забыл сказать, тут нужен ещё индекс на user_id

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V003__request.sql
> +);
замечания с первого PR)
https://github.com/CorporationX/account_service/pull/11#pullrequestreview-1618818554

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/enums/RequestType.java
> +}
Замечания с первого PR)
https://github.com/CorporationX/account_service/pull/11#pullrequestreview-1618818554

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/util/MapToJsonConverter.java
> +}
https://github.com/CorporationX/account_service/pull/11#pullrequestreview-1618818554

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/enums/RequestStatus.java
> +}
https://github.com/CorporationX/account_service/pull/11#pullrequestreview-1618818554

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/entity/Request.java
> +    private LocalDateTime updatedAt;
https://github.com/CorporationX/account_service/pull/11#pullrequestreview-1618818554

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/dto/RequestDto.java
> +    private RequestStatus requestStatus;
details еще стоит добавить

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/dto/RequestDto.java
> +    private Long lockValue;
string должно стать

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/RequestService.java
> +    }
Тут лучше принимать просто id, status, и status_details. И тут ещё в зависимости от статуса который пришёл нужно будет проставить active=false

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/RequestService.java
> +    public RequestDto getOrSaveRequest(RequestDto requestDto, Long requestId) {
transactional

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/RequestService.java
> +    public RequestDto changeStatus(RequestDto requestDto) {
transactional

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/RequestService.java
> +        return requestMapper.toDto(requestById.get());
не проверяется input_data. Если они не совпадают, нужно выкинуть исключение

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/RequestService.java
> +    public RequestDto getRequest(RequestDto requestDto) {
лучше принмать просто id, дто слишком тяжеловесно, и не удобно его строить каждый раз

2023-09-10 12:42 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/RequestService.java
> +        return requestMapper.toDto(requestById.get());
А, он даже не принимается. Давай в этом методе принимать сущность Request, и напишем еще метод build, который принимает несколкьо полей (или отдельный dto) и построить сущность Request

2023-09-10 16:59 UTC, EgorSelivanov approved these changes
К Коле добавить нечего)

2023-09-16 14:38 UTC, kkkooolllyyyaaa requested changes
Оставил один коммент

2023-09-16 14:38 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/RequestService.java
> +        return requestMapper.toDto(requestById.get());
Все ещё не првоеряется input. Если пришёл запрос с другим input, нужно выкинуть исключения и вернуть 409

2023-10-02 12:41 UTC, merged