Feature/bjs2 41964 - Накопительные счета и тарифы
CorporationX/account_service pull request #348
Opened 2024-12-29 14:20 UTC by frs717

2024-12-29 14:57 UTC, aplavina approved these changes

2025-01-10 04:10 UTC, MiraGlaceon requested changes

2025-01-10 04:10 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/controller/account/SavingAccountController.java
> +@RequestMapping("/accounts/saving")
Давай переделаем в /saving-accounts, как думаешь? Я считаю что так будет лучше. Хоть у нас накопительный счет это обычный счет с накопительным тарифом, можно вынести его в отдельный тип ресурсов, как преднастроенные счета. Хочу услышать твое мнение по этому поводу

2025-01-10 04:10 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/entity/account/SavingAccount.java
> +    @Version
Ты понимаешь какой смысл несет эта аннотация? Мне интересно, раз ты ее используешь

2025-01-10 04:10 UTC, MiraGlaceon commented on src/main/resources/application.yaml
> +  savings-account:
saving-accounts, а то везде по разному

2025-01-10 04:10 UTC, MiraGlaceon commented on src/main/resources/application.yaml
> +    cron: "0 * * * * *" # every hour
Точно каждый час? Перепроверь, я вижу каждую минуту

2025-01-12 06:16 UTC, frs717 commented on src/main/resources/application.yaml
> +    cron: "0 * * * * *" # every hour
Забыл изменить после локального теста. Надо поправить

2025-01-12 06:18 UTC, frs717 commented on src/main/java/faang/school/accountservice/entity/account/SavingAccount.java
> +    @Version
Для optimistic lock. Если в момент сохранения версия будет отличаться, то это значит, что запись была модифицирована в БД другим потоком. И при сохранении тогда бросится исключение

2025-01-12 06:19 UTC, frs717 commented on src/main/java/faang/school/accountservice/controller/account/SavingAccountController.java
> +@RequestMapping("/accounts/saving")
Согласен. Как будто отдельный ресурс - /saving-accounts - выглядит лучше. И url проще будет

2025-01-21 09:38 UTC, MiraGlaceon commented on src/main/java/faang/school/accountservice/entity/account/SavingAccount.java
> +    @Version
Про optimistic lock и хотел услышать

2025-01-21 09:39 UTC, MiraGlaceon approved these changes

2025-01-23 16:10 UTC, merged