BC-6031. Balance entity & rep + edit account entity
CorporationX/account_service pull request #38
Opened 2023-09-12 13:27 UTC by Dlakares

2023-09-12 15:53 UTC, Fxsh-pro approved these changes
Огонь

2023-09-18 20:33 UTC, Rvze reviewed
Поправить отношение таблиц

2023-09-18 20:33 UTC, Rvze commented on src/main/java/faang/school/accountservice/model/Balance.java
> +@Data
`@Data` не рекомендуется вешать на сущность, т.к. внутри содержит `@ToString` и `@EqualsAndHashCode`
Статья на эту тему - https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/

2023-09-18 20:33 UTC, Rvze commented on src/main/resources/db/changelog/changeset/V004__account-service_balance-table.sql
> +CONSTRAINT fk_balance_id REFERENCES balances(id);
это же не нужно. Ты же хранишь внешний ключ `account_id` в таблице `balances`

2023-09-18 20:33 UTC, Rvze commented on src/main/resources/db/changelog/changeset/V004__account-service_balance-table.sql
> +CONSTRAINT fk_balance_id REFERENCES balances(id);
так можно делать, но могут возникнуть трудности при обновлении данных, нужно учитывать что у тебя двунаправленная связь на уровне таблиц. Это излишнее усложнение кмк, достаточно одного внешнего ключа

2023-10-02 09:20 UTC, Rvze requested changes

2023-10-02 09:20 UTC, Rvze commented on src/main/java/faang/school/accountservice/model/Account.java
здесь можно было оставить ссылку на `Balance`.

2023-10-02 09:20 UTC, Rvze commented on src/main/java/faang/school/accountservice/model/Account.java
даже нужно, аккаунт ведь связан с балансом отношением один к одному. Но т.к. внешний ключ хранится в балансе, при обращении через аккаунт к балансу, прокси сгенерирует sql запрос с джионом к базе

2023-11-03 22:12 UTC, merged