Feature bc 5821
CorporationX/account_service pull request #4
Opened 2023-08-30 19:05 UTC by fereinn

2023-09-05 15:21 UTC, kkkooolllyyyaaa requested changes
Ещё пару комментов есть)

2023-09-05 15:21 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/model/Account.java
> +    private LocalDateTime closedAt;
Не можем Instant использовать? С LocalDateTime могут быть проблемы

2023-09-05 15:21 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/model/AccountStatus.java
> +    CLOSED
BLOCKED ещё можно)

2023-09-05 15:21 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/model/AccountType.java
> +    ESCROW_ACCOUNT
Чё то жестко) Давай просто DEBIT, SAVINGS, CURRENCY, CORPORATE. А то лишь путать будет

2023-09-05 15:21 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V002__account-service_account.sql
> +CREATE INDEX idx_account_project ON account(project_id);
Давай добавим условия WHERE NOT NULL

2023-09-06 05:00 UTC, khalyavinandrey commented on src/main/java/faang/school/accountservice/model/Account.java
> +    private AccountStatus status;
Да

2023-09-07 15:28 UTC, kkkooolllyyyaaa approved these changes
🔥

2023-09-07 15:28 UTC, merged