Medusa master bc 6058
CorporationX/account_service pull request #46
Opened 2023-09-14 18:38 UTC by Fxsh-pro

2023-09-14 18:39 UTC, Fxsh-pro commented
Там какие-то минорные конфликты, но я их лучше после апрува в ide поправлю, чтобы не поломать что-нибудь.

2023-09-16 15:05 UTC, kkkooolllyyyaaa requested changes
Покомментил)

2023-09-16 15:05 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V003__saving_account.sql
> +    tariff_history VARCHAR(2048),
Лучше TEXT

2023-09-16 15:05 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V003__saving_account.sql
> +    version BIGINT NOT NULL DEFAULT 0,
NOT NULL, и лучше без DEFAULT

2023-09-18 15:54 UTC, Fxsh-pro commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +                () -> new RuntimeException("No account with id: " + id)
Я это перепишу, когда в мастер вмёржусь, а то туда Андрей уже добавил его, не хочу у себя дописывать, чтобы потом конфликты были

2023-09-18 18:08 UTC, Fxsh-pro commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        var accounts = savingAccountRepository.findAll();
😦

2023-09-18 18:52 UTC, Fxsh-pro commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        var accounts = savingAccountRepository.findAll();
Я это позже поправлю, иначе другие задачи сделать не успею(
Коммент супер полезный, спасибо🫶

2023-09-24 12:41 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/dto/TariffDto.java
> +    private float currentRate;
ну дело не в количестве знаком, а в том, как устроен float внутри) они и на малом количестве знаков может начать лагать)

2023-09-24 12:42 UTC, kkkooolllyyyaaa approved these changes
Круто, что поправил)

2023-09-25 11:34 UTC, merged