Feature bc 5822
CorporationX/account_service pull request #5
Opened 2023-08-31 08:46 UTC by khalyavinandrey

2023-09-05 15:31 UTC, kkkooolllyyyaaa requested changes
Есть вопросики)

2023-09-05 15:31 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/dto/account/AccountDto.java
> +}
👍

2023-09-05 15:31 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/AccountService.java
> +        Account saved = accountRepository.save(account); // тут еще нужно будет сетить сгенерированный номер счета из другой таски
👍 будет ещё круче, если поставиь над строчкой TODO и номер тикета из команды медуз)

2023-09-05 15:31 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/util/validator/AccountServiceValidator.java
> +public class AccountServiceValidator {
Давай назовём лучше Checker всё таки, или даже ещё лучше:
`AccountOwnerChecker`, а то AccountServiceValidator это слишком общее название)

2023-09-05 15:31 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +    currency   VARCHAR(3)   NOT NULL,
можно просто CHARACTER

2023-09-05 15:31 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +    closed_at  timestamptz,
Харош, что именно timestamptz использовал, а не просто timestamp

2023-09-05 15:31 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +        )
На самом деле чеки довольно тяжеловесные, можно по идее на уровне приложения это провертяь)

2023-09-06 05:16 UTC, khalyavinandrey commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +    project_id BIGINT,
учту это в следующий раз, просто там уже замерджена таблица, где user_id и project_id

2023-09-06 05:19 UTC, khalyavinandrey commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +VALUES ('123456789013123', 1, null, 'CURRENT_ACCOUNT', 'USD', 'ACTIVE');
а у меня вся эта миграция для интеграционного теста, но ты тут отметил пару комментов по поводу самой таблицы и стоит ли мне первый свой PR, который уже замерджен, исправлять на основе твоих комментов?

2023-09-06 05:20 UTC, khalyavinandrey commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +    currency   VARCHAR(3)   NOT NULL,
это таблица для тест контейнера и тут просто скопировал таблицу, которая уже замерджена (BC-5820)

2023-09-06 05:21 UTC, khalyavinandrey commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +        )
это таблица для тест контейнера и тут просто скопировал таблицу, которая уже замерджена (BC-5820)

2023-09-07 15:30 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/dto/AccountDto.java
> +    private String number;
У тебя число, потому что у тебя генерация, конечный тип должен быть строкой

2023-09-07 15:31 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +VALUES ('123456789013123', 1, null, 'CURRENT_ACCOUNT', 'USD', 'ACTIVE');
Да, сори, я не заметил, что это тестконтейнер

2023-09-07 15:32 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/testcontainers/V001__account-service_get.sql
> +VALUES ('123456789013123', 1, null, 'CURRENT_ACCOUNT', 'USD', 'ACTIVE');
На счёт комментов, они не критичные, при желании в отдельной задачке можешь поменять)

2023-09-07 15:32 UTC, kkkooolllyyyaaa approved these changes
👍

2023-09-07 15:32 UTC, merged