Feature bc 5960
CorporationX/account_service pull request #70
Opened 2023-09-25 15:24 UTC by OneWayMy

2023-10-02 22:54 UTC, kkkooolllyyyaaa requested changes
🔥 
Качество кода заметно лучше стало, круто!
Оставил не совсем критичные комменты, + SpringBootTest c TestContainers и с SpringMvc было бы идеально конечно на уровне контроллера)

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/SavingsAccountController.java
> +}
🔥

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/TariffController.java
> +    @PatchMapping("/update")
Наверное можно Put и без "/update"

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/TariffController.java
> +        log.info("Received a request to retrieve a tariff with ID: {}", id);
Придирка конечно, но в соседнем контроллере писал "id", а тут "ID", лучше везде одинаково)

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/TariffController.java
> +    @GetMapping("/tariffs")
"api/v1/tariff/tariffs"? ну сомнительно, думаю можно либо /list, либо оставить просто Get

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/enums/TariffType.java
> +    CUSTOM("custom");
🤯

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/exception/handler/GlobalExceptionHandler.java
> +}
🔥

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        Account account = accountService.getAccountById(accountId);
Т.е. нужно сначала счёт создать, а потом уже только накопительный?

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        accountToSave.setTariffHistory(new ArrayList<>(List.of(currentTariff)));
😄

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        accountToSave.setTariffHistory(new ArrayList<>(List.of(currentTariff)));
Тебе думаю нужно было просто вернуть результат метода save c 58 строчки. Тогда там по идее вернулся бы объект с заполненным списоком

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +            savingsAccount.setUpdatedAt(LocalDateTime.now());
Это Hibernate всё сам обновит в БД?

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +    public SavingsAccountResponseDto getSavingsAccountByOwnerIdAndOwnerType(long ownerId, OwnerType ownerType) {
наверное можно назвать просто getSavingsAccountByOwner

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        return savingsAccount.getTariffHistory().get(currentTariffIndex).getTariff();
.last() такой функции нету?

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/TariffService.java
> +        newTariff.setRateHistory(new ArrayList<>(List.of(assignedRate)));
Тут тоже без этого нельзя? Просто вернуть результат save c 45 строчки?

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/TariffService.java
> +    public Tariff getTariffBy(TariffType tariffType) {
Не оч, что методы одинаково называются, при это принимают и возвращают разные вещи, не очевидно может быть в коде. В SavingsAccountService тоже был такой пример

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/TariffService.java
> +        Page<Tariff> page = tariffRepository.findAll(pageable);
👍

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V005__account-service_saving-account.sql
> +    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
UNIQUE не лишнее?

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V005__account-service_saving-account.sql
> +    last_interest_date timestamptz DEFAULT current_timestamp,
лучше без дефолта. Если без этого поля вставим или обновим, то поле будет с неверным значением

2023-10-02 22:54 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V005__account-service_saving-account.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
тоже лучше без дефолтов. Ниже тоже. Hibernate же сам удобно ставит эти поля, на уровне БД этой логикой нагружать излишне мне кажется)

2023-10-07 13:07 UTC, OneWayMy commented on src/main/java/faang/school/accountservice/controller/TariffController.java
> +        log.info("Received a request to retrieve a tariff with ID: {}", id);
все правильно все правильно)

2023-10-07 13:11 UTC, OneWayMy commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        Account account = accountService.getAccountById(accountId);
Я просто вижу так, что накопительный счет это как *копилка* у твоего банковского аккаунта, могу на депозит с основного счета кинуть на сбер. счет.
Или идея была не такая?

2023-10-07 14:44 UTC, OneWayMy commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        accountToSave.setTariffHistory(new ArrayList<>(List.of(currentTariff)));
Я пытался но он возвращается хибернейтом в конце транзакции, а мне нужно вернуть ДТО, и при мапинге оно начинается ругатся что лист еще пустой к сожалению, как я понимаю.
![image](https://github.com/CorporationX/account_service/assets/135334723/b1aae071-6b3f-4fb5-a71c-8f89b68a27ad)

2023-10-07 14:59 UTC, OneWayMy commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +            savingsAccount.setUpdatedAt(LocalDateTime.now());
Незнаю это вопрос или утверждение) Но вроде да, я в бд смотрел.
Я в методе достаю сбер.счет после чего присваюваю ему тариф, и метод assignTariffToSavingsAccount транзакционный и если вызвать из не транзакционного метода транзакционный метод то 1-й метод откроет новую транзакцию, и хибернейт будет следить за изменения обьектов внутри транзакции и будет изменять поля.
Я могу ошибатся и где то будут ошибки но вроде как работает

2023-10-07 15:05 UTC, OneWayMy commented on src/main/java/faang/school/accountservice/service/SavingsAccountService.java
> +        return savingsAccount.getTariffHistory().get(currentTariffIndex).getTariff();
Если ты имел ввиду есть ли у коллекций метод last() то вроде как нету, я погуглил, а если нужно такой создать то дай знать

2023-10-07 15:05 UTC, OneWayMy commented on src/main/java/faang/school/accountservice/service/TariffService.java
> +        newTariff.setRateHistory(new ArrayList<>(List.of(assignedRate)));
Как я писал выше, и как пишут люди на StackOverFlow что транзакция еще не завершилась по этому обновления еще не будет, а мапить в Дто нужно

2023-10-07 15:15 UTC, OneWayMy commented on src/main/resources/db/changelog/changeset/V005__account-service_saving-account.sql
> +    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
Честно сказать даже незнаю, почти в каждой миграции стоит UNIQUE, был бы рад если помог с этим)

2023-10-07 15:20 UTC, OneWayMy commented on src/main/resources/db/changelog/changeset/V005__account-service_saving-account.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
тоесть в миграциях все timestamptz лучше не ставить как default?
Я просто думал что если ставишь аннотацию @CreatingTimestamp то нужно и в миграции прописать DEFAULT  что бы при создании сущности в бд оно автоматически заполнялось

2024-12-22 20:42 UTC, closed without merging