Feature bc 5738 balance audit
CorporationX/account_service pull request #91
Opened 2023-10-10 17:32 UTC by M1hasMAD

2023-10-11 21:07 UTC, kkkooolllyyyaaa requested changes
Есть моментики)

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/BalanceAuditController.java
> +    }
Я думаю тут стоит сделать "account/{id}/balance/history". Сначала именно account/{id}, и потом только баланс.

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/BalanceAuditController.java
> +    }
Аа, ля, у тебя тут получение конкретной версии баланса по его id  в БД (не по id счета)

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/BalanceAuditController.java
> +    }
Хз, зачем такая ручка может вообще потребоваться. Я предлагаю переписать на пагинированную ручку, которая возвращает сразу список балансов (типо история)

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/BalanceAuditService.java
> +public class BalanceAuditService {
Я думаю не обязательно это делать отдельным сервисом, а точнее даже нежелательно. Я думаю стоит тупо заинджектить в BalanceService, и там всю логику реализовать. Типо например при создании баланса, у тебя и аудит записывается. Также при обновлении баланса у тебя новая запись в аудите)

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
> +    balance_audit_version INT NOT NULL,
Эта комбинация вполне может быть хорошим primary ley. id генерируемый думаю не нужен в этом случае)

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
> +    actual_amount NUMERIC(10, 2),
NOT NULL

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
> +    audit_timestamp timestamptz DEFAULT current_timestamp,
created_at можно назвать) и без дефолта, дефолтом hiber займётся

2023-10-11 21:07 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
> +CREATE INDEX idx_balance_id ON balance_audit (balance_id);
думаю на operation_id тоже можно индекс сделать

2023-10-15 22:39 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
> +    balance_audit_version INT NOT NULL,
Нет, у тебя баланс будет содержать несколько аудитных записей. Т.е. каждая операция создаёт запись в аудитном балансе. Поэтому несколько записей с одним balance_id не могут существовать если primary_key (balance_id). Нужно второе поле, идеально подходит баланс. С каждым увеличинием баланса создаётся запись

2023-10-15 22:44 UTC, kkkooolllyyyaaa requested changes
👌, но стоит версионирование сделать думаю

2023-10-15 22:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        balanceAudit.setVersion(1);
версия же должна инкрементироваться не?

2023-10-15 22:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        balanceAudit.setOperationId(1L);
// TODO можно поставить

2023-10-15 22:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        log.info("Balance audit was taken successfully by balance id: {} ", balanceId);
лишнее

2023-10-15 22:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        List<BalanceAudit> balanceAudits = getBalanceAuditsById(balanceId);
стоит отсортировать по убыванию версий. Сначала новые записи, потом старые

2023-10-15 22:44 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        return audits;
условие лишнее. Если пустой список, то можно его и вернуть

2023-10-15 22:44 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
А где primary key?)

2023-10-16 11:20 UTC, M1hasMAD commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        balanceAudit.setVersion(1);
по идее должна, и есть аннотация @version, но у нас у всех такая проблема, что версия просто не инкрементируется, при каком-либо действии с балансом (до этого парни уже сетили вручную версию баланса)

2023-10-16 12:06 UTC, M1hasMAD commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
вообщем, я понял в чем заключаются идея создания айдишки для аудита, то есть у нас есть баланс и мы при каждой операции с ним - делаем новую запись, то беж новый аудит, но я не догоняю один момент, если у нас balance_id в таблице balance тоже Primary Key, и в таблице balance_aydit он тоже Primary Key, то он будет брать balance_id из таблицы balance и так как в таблице balance_aydit он тоже Primary Key -> будут создаваться новые (уникальные) айдишники (аудиты) от одного и того же баланса (от balance_id), примерно так?🥲

2023-10-17 17:22 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
Нет, у balance_audit у тебя будет составной первичный ключ `primary key (balance_id, version);` И так как версию постоянно увеличивается, записи не будут конфликтовать

2023-10-17 17:22 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/BalanceService.java
> +        balanceAudit.setVersion(1);
Тогда нужно версию balance.version

2023-10-17 17:23 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V008__account-service_balance_audit.sql
> +    balance_id bigint PRIMARY KEY,
объяснил в соседнем комменте как нужно, pk неправильный

2023-10-20 00:31 UTC, kkkooolllyyyaaa approved these changes
🔥

2023-10-20 00:31 UTC, merged