Feature/bc 6322
CorporationX/account_service pull request #92
Opened 2023-10-11 09:54 UTC by zhugalcf

2023-10-11 22:24 UTC, kkkooolllyyyaaa requested changes
есть парочка мини комментов

2023-10-11 22:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/controller/PaymentController.java
> +        paymentService.createPayment(paymentDto);
можно лог кинуть)

2023-10-11 22:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/kafka/PaymentListener.java
> +        if (operationType.equals(PaymentStatus.REFUND.name())) {
else if?) ну и на else стоит хотя бы лог кинуть что ли)

2023-10-11 22:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/PaymentService.java
> +                .orElseThrow(() -> new RequestNotFoundException("Request not found"));
? Странно чёт) ты же уже получил request через getOrSave

2023-10-11 22:24 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/PaymentService.java
> +        BigDecimal amount = BigDecimal.valueOf ((Double) request.getInputData().get("amount"));
лучше прочитать стрингу) Double в общем случае модет потерять точность

2023-10-12 09:48 UTC, zhugalcf commented on src/main/java/faang/school/accountservice/service/PaymentService.java
> +                .orElseThrow(() -> new RequestNotFoundException("Request not found"));
Я не правильно подумал, я думал что один поток может зайти создать реквест и остановиться, потом второй так же зайти и так как реквест уже создан получить его же, первый поток потом продолжит работу и авторизует баланс а потом второй повторно его авторизует что не правильно, и идея была такая что вызовом получения реквеста из репозитория потоки будут работать в транзакции и такого не произойдет, но я теперь понял что мы же вызываем методы из requestServise которые тоже transactional и соответсвенно это будет одна транзакция и даже если два потока авторизуют баланс то на апдейте статуса один из них поймает оптимистик лок и транзакция откатится, я правильно понимаю?

2023-10-15 22:32 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/accountservice/service/PaymentService.java
> +                .orElseThrow(() -> new RequestNotFoundException("Request not found"));
Да, именно так

2023-10-15 22:33 UTC, kkkooolllyyyaaa approved these changes
👍

2023-10-15 22:33 UTC, merged